### PR TITLE
[client,sdl] fix constructor, initialize pointers

### PR DESCRIPTION
**Pull request by akallabeth**
some initialization might fail, so initialize them beforehand.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test again...

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Comment by akallabeth** [comment]
@freerdp-bot test properly

**Comment by akallabeth** [comment]
@freerdp-bot and again...

**Comment by akallabeth** [comment]
@freerdp-bot come on, test!

**Review by mfleisz — APPROVED** [review]

**Pull request merged**
