### PR TITLE
Fixed color pointer decoding.

### PR DESCRIPTION
**Pull request by akallabeth**
The AND mask was wrongly applied for color pointer updates, inverting white pointers and making black ones invisible.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@akallabeth I'm not convinced that this is really the proper fix for that.

**Comment by nfedera** [comment]
@akallabeth I'm not convinced either. Was this tested against e.g. Windows 7 with different mouse pointer themes? Also this should be tested against Windows XP with different pointer themes.

**Comment by nfedera** [comment]
Also check https://msdn.microsoft.com/en-us/library/windows/hardware/ff556138(v=vs.85).aspx

**Comment by akallabeth** [comment]
@bmiklautz @nfedera Ok, I think I got the right solution now. Had a server and client bug. Server did send an invalid mask (all fields 0xFF) and client decoding routine expected the mask field to always be available.

**Comment by bmiklautz** [comment]
@akallabeth make sense.

**Comment by bmiklautz** [comment]
+1

**Comment by mfleisz** [comment]
+1

**Comment by hardening** [comment]
With my little knowledge of the subject I'd tend to +1. Anyway I'd really like to have @nfedera's opinion on this (our mouse pointer specialist !) before merging.

**Comment by nfedera** [comment]
+1 LGTM

**Pull request merged**
