### PR TITLE
RAILS server implementation refactored

### PR DESCRIPTION
**Pull request by kubistika**
Again, refactored version of  #5763 (that can be closed):
* Fixes for some of bugs in server side
* Fix in gfx: wrong pdu type that caused mstsc to close the connection when using RAILS with HiDef.
* Fix bug in `update_send_new_or_existing_notification_icons`  (it checked the version field value without first checking it is present in the payload.
* Keep extendedSpiSupported synced between server and client.

### CODE REVIEW

**Comment by akallabeth** [comment]
@kubistika hmm, looks like you need to rebase this one, looks like you started on the wrong branch.

**Comment by kubistika** [comment]
@akallabeth yes, I’ll rebase tomorrow

**Comment by kubistika** [comment]
@akallabeth i rebased on master.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
