### PR TITLE
Added expert settings /tune and /tune-list

### PR DESCRIPTION
**Pull request by akallabeth**
Add these options to easily manipulate `rdpSettings` for ricers (and debugging purposes)

### CODE REVIEW

**Comment by kubistika** [comment]
This is great!
LGTM

**Comment by floppym** [comment]
With `xfreerdp /tune-list` I see the following output after the list of options.
```
[14:46:59:934] [19496:19496] [ERROR][com.freerdp.client.x11] - error: server hostname was not specified with /v:<server>[:port]
[14:46:59:934] [19496:19496] [ERROR][com.winpr.sync.wait] - invalid hHandle.
```
Enabling `/tune-list` should probably stop option processing and exit early.

**Comment by akallabeth** [comment]
@bmiklautz @hardening what do you think about these options?

**Comment by akallabeth** [comment]
@bmiklautz @hardening @mfleisz anyone want to merge this one?

**Pull request merged**
