### PR TITLE
[ci] Add fuzzing workflow

### PR DESCRIPTION
**Pull request by ligurio**
Patch adds a fuzzing workflow to GH Actions. Workflow will guarantee that building fuzzing tests is healthy.

### CODE REVIEW

**Comment by akallabeth** [comment]
@ligurio got some 403 in the fuzzer run, is that expected?

**Comment by akallabeth** [comment]
@ligurio sure?
```
ERROR - Unable to download from: https://storage.googleapis.com/freerdp-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/freerdp_TestFuzzCryptoCertificateDataSetPEM/public.zip. Code: 403. Content: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details></Error>".
```

does not sound like a `404` but missing credentials?

**Comment by ligurio** [comment]
workflow was copy-pasted from https://github.com/tarantool/tarantool/blob/master/.github/workflows/fuzzing.yml and there are no such warnings/errors in workflow output (see https://github.com/tarantool/tarantool/actions/runs/5199245805/jobs/9376391325) because we provide seed corpus for every test (see https://github.com/google/oss-fuzz/blob/1d3c33738aab048af01c72303252179cbe0e860b/projects/tarantool/build.sh#L91-L99). I suspect these warnings will gone after adding seed corpus for freerdp tests too.

```
2023-06-07 11:19:03,548 - root - INFO - Removing unaffected fuzz targets.
2023-06-07 11:19:03,552 - root - DEBUG - Diffing against base_commit: 116df1d70cf768b2cc8569074b2f6715ef84860f.
2023-06-07 11:19:03,553 - root - INFO - Diffing against 116df1d70cf768b2cc8569074b2f6715ef84860f.
2023-06-07 11:19:03,556 - root - INFO - Files changed in PR: ['.github/actions/environment/action.yml', '.github/workflows/publish-module-api-doc.yaml']
2023-06-07 11:19:03,564 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): storage.googleapis.com:443
2023-06-07 11:19:03,660 - urllib3.connectionpool - DEBUG - [https://storage.googleapis.com:443](https://storage.googleapis.com/) "GET /oss-fuzz-coverage/latest_report_info/tarantool.json HTTP/1.1" 200 315
2023-06-07 11:19:03,663 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): storage.googleapis.com:443
2023-06-07 11:19:03,728 - urllib3.connectionpool - DEBUG - [https://storage.googleapis.com:443](https://storage.googleapis.com/) "GET /oss-fuzz-coverage/tarantool/fuzzer_stats/20230607/datetime_strptime_fuzzer.json HTTP/1.1" 200 43853
2023-06-07 11:19:03,739 - root - INFO - Fuzz target datetime_strptime_fuzzer is affected by: ['src/lib/core/assoc.h', 'src/lib/core/datetime.c', 'src/lib/core/diag.c', 'src/lib/core/error_payload.c', 'src/lib/core/exception.cc', 'src/lib/core/reflection.h', 'src/lib/core/tweaks.c', 'src/lib/core/tweaks.h', 'src/lib/core/util.c', 'src/lib/salad/mhash.h', 'src/lib/tzcode/localtime.c', 'src/lib/tzcode/strptime.c', 'src/lib/tzcode/timezone.c', 'test/fuzz/datetime_strptime_fuzzer.cc', 'third_party/PMurHash.c', 'third_party/c-dt/dt_core.c', 'third_party/c-dt/dt_util.c']
2023-06-07 11:19:03,740 - root - INFO - Fuzz target datetime_strptime_fuzzer is not affected.
```

**Comment by ligurio** [comment]
There is a doc for GH action - https://google.github.io/oss-fuzz/getting-started/continuous-integration/

**Comment by hardening** [comment]
@freerdp-bot can you test that please ?

**Pull request merged**
