### PR TITLE
Added command line option /cert-tofu

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by bmiklautz** [comment]
@akallabeth tofu = trust on first use? :)

**Comment by realjiangms** [comment]
If just want to accept any cert, what's the difference if I use /cert-ignore?

**Comment by bmiklautz** [comment]
@realjiangms the certificate is saved when encountered for the first time so the real difference is that key changes can be detected.

**Comment by realjiangms** [comment]
@bmiklautz Thanks. That makes sense

**Pull request merged**
