### PR TITLE
[libuwac] fix keyboard "sticky" keys when entering window

### PR DESCRIPTION
**Pull request by manio**
The commit is fixing the following problem:
When the freerdp window gets keyboard focus and is notified, it wrongly process keys which are *held*, not a freshly pressed.

The comment in the code explains it more.

### CODE REVIEW

**Comment by manio** [comment]
Oh this is wrong. Have to work more about it...

**Comment by manio** [comment]
The change seems to be working fine... but I have sometimes the situation, that when I enter a freerdp window and start typing I have some modifier key active and I have to press all modifier keys to have it return to normal state...
I am setting this to draft and will test it for some longer period...

**Comment by manio** [comment]
Hi again,
I tested it for some time and think it's ready for merge.
Switching from Draft to ready...

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by manio** [comment]
Thank you

**Pull request merged**
