### PR TITLE
Fix building against current ffmpeg

### PR DESCRIPTION
**Pull request by h3xx**
The AV_ prefixed constants have been available and recommended since
[ffmpeg@def97856de6021965db86c25a732d78689bd6bb0 (2015-07-07)](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=def97856de6021965db86c25a732d78689bd6bb0), or version
2.8.

The non-prefixed constants are set to be removed in the next ffmpeg
release, and were removed in
[ffmpeg@302554835e39b79b977ed60c9afe81b44590dfef (2016-12-05)](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=302554835e39b79b977ed60c9afe81b44590dfef).

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot can you test that ?

**Comment by h3xx** [comment]
Fixed. Thanks for the review.

Want me to squash?

**Comment by h3xx** [comment]
@freerdp-bot can you please run the CI build?

**Comment by hardening** [comment]
@freerdp-bot test again please

**Pull request merged**
