### PR TITLE
Fixed http gateway body length read.

### PR DESCRIPTION
**Pull request by akallabeth**
@mmattes looks like I've found it, `bodyLength` is usually `0` in the responses, then use the length actually read.

### CODE REVIEW

**Comment by mmattes** [comment]
@akallabeth for what was this? The request I made in the irc channel? If so then I unfortunately got disconnected and could not read any reply. I changed this local but it did not have any effect to my problem.

**Comment by akallabeth** [comment]
@mmattes That was an issue I had testing with `http` gateway

**Comment by mmattes** [comment]
@akallabeth unfortunately this does not work for me, i will have another look may i can find something else what causes the disconnect

**Comment by mmattes** [comment]
@akallabeth cool, seems all the changes you did also solved my problems :+1:

**Pull request merged**
