### PR TITLE
Japanese patch #4905

### PR DESCRIPTION
**Pull request by FeLvi-zzz**
I added Japanese translation.

### CODE REVIEW

**Comment by FeLvi-zzz** [comment]
@freerdp-bot test

**Comment by FeLvi-zzz** [comment]
@freerdp-bot can you test that please ?

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
Ok, looks like you have a typo in the xml, please check that.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
Thank you for this fix.

**Pull request merged**
