### PR TITLE
Fixed surface alignment.

### LINKED ISSUE #3576: Regression: Wrong alignment calculation
Actually this is not a real regression. Because the code before color conversion fix was also wrong.

Code in xf_CreateSurface:
···
    surface->gdi.scanline = surface->gdi.width \* GetBytesPerPixel(
                                surface->gdi.format);

```
    surface->gdi.scanline += (xfc->scanline_pad / 8);
    surface->gdi.scanline -= (surface->gdi.scanline % (xfc->scanline_pad / 8));
```

···

The above code is going to align scanline to scanline_pad
But if scanline_pad is 4(32/8), and width is already multiple of 4bytes, e.g. 5120(1280*4), it will become 5124, which looks not as expected

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #3576

### CODE REVIEW

**Comment by realjiangms** [comment]
The code looks good. 
In X11 lib there's more efficient method:

(((nbytes) + ((pad) - 1)) & ~(long)((pad) - 1))

But it only apply to alignment of power of 2.

**Comment by realjiangms** [comment]
Would you mind also fix other places?

    cacheEntry->scanline = (cacheEntry->width + (cacheEntry->width % 4)) * 4;
in gdi_SurfaceToCache

**Comment by realjiangms** [comment]
Can we get this fix checked in?
I think we need approval from some reviewer with write access ;)

**Comment by akallabeth** [comment]
@hardening @bmiklautz @mfleisz @nfedera Could you have a look?

**Pull request merged**
