### PR TITLE
region: add a ref counter on REGION16_DATA to harden frees of empty_region

### PR DESCRIPTION
**Pull request by hardening**

### CODE REVIEW

**Comment by akallabeth** [comment]
@hardening don´t really see the point in keeping a reference counter that is not used at all.
Nothing against adding one once it is possible to share region data, but until then better simply remove the data if not needed.

**Comment by hardening** [comment]
@akallabeth well it's used to not free the empty region data

**Comment by bmiklautz** [comment]
@hardening did you hit any issue with region?

**Comment by hardening** [comment]
> @hardening did you hit any issue with region?

nope it's more an alternative to https://github.com/FreeRDP/FreeRDP/pull/6333

**Pull request closed without merging**
