### PR TITLE
add /smart-sizing:WxH and /window-position:XxY for windows client

### PR DESCRIPTION
**Pull request by garbb**

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot test that please.

**Comment by hardening** [comment]
@garbb you should run a `clang-format` on your changes before submitting, that addresses most of the remarks for the code quality checker

**Comment by garbb** [comment]
Thanks for the information. I will look into this. Still new to this process.

**Comment by hardening** [comment]
@freerdp-bot do the final test please

**Review by hardening — APPROVED** [review]
LGTM

**Pull request merged**
