### PR TITLE
allow /p option without value

### PR DESCRIPTION
**Pull request by tchernomax**
If /p is used without value the password is asked by
freerdp_passphrase_read (in command line)

### CODE REVIEW

**Comment by akallabeth** [comment]
@maxime1986 May I ask what is wrong with just using ```/from-stdin``` instead of ```/p```?

**Comment by maxime1986** [comment]
I don't have admin access to the RDP server I am connecting to.
From my tests it appears (but I am not sure) that this server doesn't support /sec:nla nor /sec:tls, only /sec:rdp.

To connect to this server I tried `xfreerdp /d:mydomain /u:myusername /from-stdin /app:'||calc' /v:myserver.net` but xfreerdp never asked for the password.
`client_cli_authenticate_raw` nor `freerdp_passphrase_read` was called.

The comment on `client_cli_authenticate_raw` say:
> Callback set in the rdp_freerdp structure, and used to get the user's password, if required to establish the connection.

The *if required to establish the connection* makes me think this only work when NLA is supported.
So I make this patch to clarify things and be able force xfreerdp to ask for the password from stdin.

My interpretation may be wrong. If that so, could you explain to me how to **force** xfreerdp to ask for the password with /from-stdin ?

**Comment by akallabeth** [comment]
@maxime1986 I see, looks like you're right. Still, would be better to fix ```/from-stdin``` than to kind of misuse ```/p```.

**Comment by maxime1986** [comment]
@akallabeth with /sec:rdp is it possible to configure a server to allow client to log in without password (something like guest account) ?
If it's the case, I think /from-stdin can't be fixed because it will not know if it has to ask for a password or not.

Maybe /from-stdin with /sec:rdp should alway ask for password, and disable it if the user leave it blank ?

What do you think ?

**Comment by maxime1986** [comment]
If you think it's better to stay with /from-stdin, is `transport_connect_tls` and `transport_connect_rdp` good places to add `client_cli_authenticate` (or similar) ?

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by akallabeth** [comment]
@maxime1986 Sorry, don't remember the exact call graph, would have to dig into that myself.

**Comment by akallabeth** [comment]
@tchernomax I've refactored your idea as an extension to ```/from-stdin``` in #4229.

**Pull request closed without merging**
