### PR TITLE
Enable display scaling in client

### PR DESCRIPTION
**Pull request by colemickens**
This is the same pull request as #2438, but with a cleaned up history and rebased to master.

I hope this is okay to do, the other one seemed relatively dead, it's been 29 days since the last reply other than myself.

@irichter is this okay with you?

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by colemickens** [comment]
Should I trigger this to be re-tested as I rebase it, @bmiklautz ?

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by colemickens** [comment]
ping?

**Comment by bmiklautz** [comment]
@colemickens my comments from the first pull request still stand... - I'd recommend check the input values according to the documentation.

**Comment by colemickens** [comment]
Oops, I missed that, I'll take a look at adding that. Thanks.

**Comment by akallabeth** [comment]
@colemickens @llyzs has put the core functionality (without command line stuff) of your pull to #2846.

**Comment by colemickens** [comment]
@akallabeth how is that used/usable without the corresponding CLI changes? Tried skimming the commits but it didn't make immediate sense to me.

**Comment by akallabeth** [comment]
@colemickens You can not directly use it right now, another pull for the command line is required.

**Comment by acelan** [comment]
hello, any updates?

**Comment by akallabeth** [comment]
@acelan The pull needs rebasing and the input values are not checked. When this is done, we'd merge.

**Comment by colemickens** [comment]
The last time I rebased this, I flat out couldn't get it to work. The initial hidpi patch that was taken was written slightly differently than @irichter's original implementation and I couldn't reconcile them. I'll try again.

Closing this for now. If I get it rebased and working I'll send a new PR.

**Comment by colemickens** [comment]
Continued: https://github.com/FreeRDP/FreeRDP/pull/3111

**Pull request closed without merging**
