### PR TITLE
X11 event lock

### PR DESCRIPTION
**Pull request by akallabeth**
* Fixes X11 event lock issues (see #5908 )
* Use const arguments in event handling code
* Use appropriate type in event handling code to avoid misuse

### CODE REVIEW

**Comment by akallabeth** [comment]
@user-72632 I´ve refactored the event handling code and think to have fixed the issue, could you give this branch a try and confirm?

**Comment by user-72632** [comment]
@akallabeth sorry, I can't seem to build your branch. Lately, I have been having trouble just building master due to multiple definition of `rail_send_pdu' in proxy. I have been just waiting for the nightlies to check on things because I have not had time to look into all the problems. Thanks for looking into this.

**Comment by akallabeth** [comment]
@user-72632 how do you build? this sounds strange as we build server & proxy quite often ourselfes.

**Comment by user-72632** [comment]
I don't want to bother @akallabeth with this but here is my problems. I use a custom bash script to build and have been for years so I know it works. All builds when using WITH_SERVER=ON do not build to completion. I have attached build logs for Ubuntu 16.04 and Debian 10. When I do not use that directive it builds fine except for the many pragma warnings in all Ubuntu 16.04 builds which I assume is from an older gcc, but should still be fixed. From the errors, it looks to be in the proxy code/headers.

I could never get your branch to compile, don't know why sorry.

Ubuntu 16.04 build log with errors and pragma warnings:

[ubuntu-16.04-out-of-source-freerdp-build-with-errors-log.txt](https://github.com/FreeRDP/FreeRDP/files/4267935/ubuntu-16.04-out-of-source-freerdp-build-with-errors-log.txt)

Debian 10 build log with errors:

[debian-10-out-of-source-freerdp-build-with-errors-log.txt](https://github.com/FreeRDP/FreeRDP/files/4267938/debian-10-out-of-source-freerdp-build-with-errors-log.txt)

HTH

**Comment by user-72632** [comment]
Good news! I did manage to compile the downloaded zip file of your branch and test it. Using my test case it did make it through the entire transfer the first time! I noticed a couple things during the transfer; although the reported transfer speed looked about the same as the previous times, the actual wall clock of the transfer seemed a little longer than the previous transfers. I also noticed that the bitrate during the transfer stayed even and orderly as opposed to the bursty nature of the previous transfers, which I believe is a good thong.

I never did get your git branch to compile. Looking into it a little deeper it appears there are some dependencies that I may not have that you are using. Not sure what the difference is in the git clone of your branch and the downloaded zip file is though.

In any event, thanks for all your work on this problem which appears to be fixed!

**Comment by akallabeth** [comment]
@user-72632 interesting, just built current master with your cmake command line and do not get such errors, debian 10 here

**Comment by user-72632** [comment]
Yes, that is. How are you syncing up with the latest dependencies required? For example, are you grepping from a Jenkins workspace or something else in order to stay current with the latest dependencies. The documentation for that has been out of date for a while now.

**Comment by akallabeth** [comment]
@user-72632 well, gstreamer is only used by tsmf.
Rest depends on options you activate, have a look at the nightly debian package in the repo.

**Pull request merged**
