### PR TITLE
allow ffmpeg usage on Windows without pkgconfig

### PR DESCRIPTION
**Pull request by eronnen**
Allow compiling FreeRDP with Ffmpeg h264 subsystem without pkgconfig (like openh264)

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@eronnen could you clarify what this pr should do?
```
find_package(PkgConfig QUIET)
  if (PKG_CONFIG_FOUND)
...
endif()
```
already takes care of not using `pkg-config` if it is not found.

**Comment by eronnen** [comment]
@akallabeth When I'm building on Windows or Android I have `pkg-config` installed, but specifically for `ffmpeg` it doesn't work, for example the binaries in https://github.com/BtbN/FFmpeg-Builds/releases don't contain `pkg-config` files, so I just copied the logic from https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindOpenH264.cmake#L10 which does work on Windows and Android.

**Comment by akallabeth** [comment]
@eronnen then you can always set the paths manually.

**Comment by eronnen** [comment]
@akallabeth why set the paths manually? it's not a trivial task on windows. Is there any necessity for the `pkg-config` files in `FindFFmpeg.cmake`? it's an equivalent usage to `FindOpenH264.cmake` which doesn't require `pkg-config`...

**Comment by akallabeth** [comment]
@eronnen because you installed `pkg-config` and do not want to use it.

**Comment by eronnen** [comment]
@akallabeth  I have `pkg-config` installed since it's required by other things, but unfortunately `FFmpeg` public builds on windows don't support it.

I changed the diff to 

```
if (UNIX AND NOT ANDROID)
  find_package(PkgConfig QUIET)
  pkg_check_modules(AVCODEC QUIET libavcodec)
  pkg_check_modules(AVUTIL QUIET libavutil)
  pkg_check_modules(AVRESAMPLE QUIET libavresample)
  pkg_check_modules(SWRESAMPLE QUIET libswresample)
endif (UNIX AND NOT ANDROID)
```

does that make more sense? (it's completely identical to https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindOpenH264.cmake#L10)

**Comment by akallabeth** [comment]
actually no, because `openh264` works differently. (we use `pkg-config` for `ffmpeg` on windows too)

**Pull request closed without merging**
