### PR TITLE
Fixed AAC encoding for microphone

### PR DESCRIPTION
**Pull request by akallabeth**
* Fixed b-frame interval for FFMPEG
* Fixed sample size for FAAC

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by hardening — APPROVED** [review]
Not the best expert but LGTM

**Comment by vscfreire** [comment]
Hi @akallabeth, as you know, I'm always interested in sound subsystem fixes, optimizations and improvements, as I use lots of video/sound/mic over FreeRDP. Can you confirm that you tested this fixes with Windows? I'm asking because I've done several tests with this and AAC and the mic sound is still garbled. PCM works perfect, but AAC has lots of distortion. The first few tries it seemed a little better than before this fix, but to be sincere, I reverted the fixes and it sounds the same.

**Comment by akallabeth** [comment]
@vscfreire yes, tested against windows 8 to 10 (and server 2016 and 2019)
no distortions (and especially no increasing delay) with these patches.
tested with integrated sound recorder app.
* Which kind of distortions do you have? (maybe attach some sample record)?
* Which backend do you use (ffmpeg or faac)
* Which os do you use on the client side?

**Comment by vscfreire** [comment]
- [AACRecordingTest.zip](https://github.com/FreeRDP/FreeRDP/files/6842295/AACRecordingTest.zip)
- ffmpeg - tried the latest minors of 4.2.4, 4.3.2 and 4.4.0, all had the same kind of distortions
- Windows 10 19043.1110 on the client, Windows Server 2016 on the server

Used Audacity to record the sample, if I pressed a second time on the Record, the session would also disconnect. With PCM, not only the recorded sound is perfect, but the session doesn't disconnect if I record again.

**Comment by akallabeth** [comment]
@vscfreire ok, weired. did you try with `faac` instead of `ffmpeg` too? (different encoder, so you can rule out issues there)
will do a recheck of the windows client, mac and linux do work fine with `faac` and `ffmpeg` (but there is some format conversion issue with some `ffmpeg` builds)

**Pull request merged**
