### PR TITLE
Implement pen functionality for X11

### PR DESCRIPTION
**Pull request by digitalsignalperson**
# Description

Implements pen with pressure, eraser, and hover. 
https://github.com/FreeRDP/FreeRDP/issues/7260

image

# Testing
How to test per the above picture:
- have an X11 desktop with a tablet and pen/stylus that has a tip and an eraser (e.g. MPP pens, like microsoft surface)
- use xfreerdp to connect to a windows machine with powerpoint, and use the `+multitouch` option
- in powerpoint, pick the black pen and make it as thick as possible 
image
- zoom in to 400% to make the pressure sensitivity obvious
- draw a line varying the pressure and see the thickness of the line be affected
- reduce the line thickness and try writing some words. Ensure that the writing is smooth and nothing skips
- hover the pen above the screen and move it around - notice the cursor is a black dot that follows the pen around
- flip over to the eraser and hover it over the screen. observe it have the eraser tip cursor like shown here:
image
- try erasing some of your previous lines
- switch back and forth with pen and eraser like you normally would writing and observe inking/erasing working as expected

Known issues:
- After using the eraser and going from pen down to hovering, the hover icon might switch over to the black dot, but pressing the eraser back into the screen will continue to use the eraser properly. This was somewhat mitigated by trying to force an UPDATE | CANCEL immediately after pen up, but it impacted performance of writing (skips parts if writing fast). There something tricky about managing the state transition with penFlags for using the eraser (PEN_FLAG_INVERTED). See the 2nd commit for additional context.

Exiting the hover state feels a little hacky because X11 does not give you any event to say "pen proximity is away from screen". It simply stops giving you motion events. So exiting the hover state was done whenever any other non-hover input event happened.

In my testing, I had to add pen hover for switching back and forth with the pen tip and eraser tip to work. On a regular windows device like a surface pro, you always see the pen hover cursors before and after any inking or erasing events, so I think it makes sense.

# Design notes

Pen behaviour is very similar to multitouch, except while X11 gives explicit events for XI_TouchBegin, XI_TouchUpdate, and XI_TouchEnd, as far as I could see for pen stuff you only get XI_ButtonPress, XI_Motion, and XI_ButtonRelease, and it's up to you to correctly interpret what's going on. Furthermore, a challenge is that pen not only has a active state, but a hovering state. So a complete picture would be PenHoverBegin, PenHoverUpdate, PenHoverEnd, PenDrawBegin, PenDrawUpdate, PenDrawEnd, all while complying with [[MS-RDPEI] 3.1.1.1 Touch Contact State Transitions](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpei/797930c0-d5ca-4da5-a801-97813d3b750e)

Some helpful tools to see what all the states are before starting coding:
- `libinput debug-events`
- `xinput test-xi2 --root`
 
Possibly useful observations from xinput:
- I see `EVENT type 1 (DeviceChanged)` every time between switching to a different input device (mouse, touch, pen, keyboard)
- Initially only a "ipts 045E:001F Pen Pen (0)" was seen on my Surface Pro 5 (surface linux kernel with ipts), but on first time using the eraser I got a HierarchyChanged event where a "ipts ... Pen Eraser ..."  device was added.
    - **should probably detect HierarchyChanged and re-initialize xf_input_init when that happens**

Additional info and notes:
- Browsing various X11 touch/stylus implementations, they all seem to rely on the fact that pressure is always the 3rd valuator value. In my implementation, I used this index, but we can also do a string comparison because the valuator name should have "Pressure" in it.
- max_pressure must be determined from querying the input devices, so this should also be refreshed whenever devices are added/removed
- rdpei has MAX_PEN_CONTACTS = 4 so simultaneous pen contacts are apparently possible, but directly on my Surface Pro 5 in windows 10 this does not seem to work with the 2 pens I have. It may need special devices like Surface Hub or similar.

Also here's a branch for the first commit of the patch on 2.10.0: https://github.com/digitalsignalperson/FreeRDP/tree/2.10.0_archlinux-pendev3

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Review by hardening — APPROVED** [review]
Looks good to me, thanks for the contribution

**Comment by hardening** [comment]
@freerdp-bot can you test again seems like TestConnect failed for no reason !

**Comment by akallabeth** [comment]
@freerdp-bot come on, test properly please

**Comment by digitalsignalperson** [comment]
I just pushed another commit fixing these issues 
- -Wreturn-type (was missing a return 0)
- -Wunused-variable
- and removed the temporary comment

https://github.com/digitalsignalperson/FreeRDP/commit/c4e03e0dafeef310f745f8e1076ca8755ed87c8e
Do I need to open a new PR to add it?

I'm not sure why my scan-build said no new issues but the CI build identified them.

**Comment by akallabeth** [comment]
@digitalsignalperson please a new pr yes

**Comment by ichaoX** [comment]
Hi, I recently tested [freerdp-nightly](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=bookworm,label=pkg-deb/) but it seems to recognize my device as a mouse.

```shell
$ xsetwacom list
Wacom HID 524D Pen stylus       	id: 9	type: STYLUS    
Wacom HID 524D Pen eraser       	id: 15	type: ERASER    
Wacom HID 524D Finger touch     	id: 10	type: TOUCH     
Wacom One by Wacom M Pen stylus 	id: 16	type: STYLUS    
Wacom One by Wacom M Pen eraser 	id: 17	type: ERASER   
```

I think it may be that this part of the code is not compatible with my device name.

https://github.com/FreeRDP/FreeRDP/blob/9c7a541d9c0acb9728cebf344b363f7ea797f920/client/X11/xf_input.c#L145-L165

It should ideally be case-insensitive to match "Pen stylus".

**Comment by digitalsignalperson** [comment]
@ichaoX it might work changing `strstr` to `strcasestr`. However some other stuff broke here that I'm not sure if it's been fixed: https://github.com/FreeRDP/FreeRDP/pull/9086#issuecomment-1603171372
We should document the current status here: https://github.com/FreeRDP/FreeRDP/issues/7260

**Pull request merged**
