### PR TITLE
Improve monitor support

### PR DESCRIPTION
**Pull request by davewheel**
Here's some changes with monitor support in FreeRDP with both client and server-side improvements.

Sponsored by: Wheel Systems (http://www.wheelsystems.com)

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot could you test this please ?

**Comment by hardening** [comment]
LGTM +1.

**Comment by akallabeth** [comment]
LGTM, +1

**Comment by mfleisz** [comment]
+1

**Pull request merged**
