### PR TITLE
Add command line option to override action script path

### PR DESCRIPTION
**Pull request by volth**
It makes ```"/usr/share/freerdp/action.sh"``` overridable with ```/action-script:<filename>``` command line switch
Fix for #3744

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test
Anyone knowledgeable around that knows why this was hard coded in the first place?

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by volth** [comment]
Ok.
But I would keep ```/usr/share/freerdp/action.sh``` as default.
Changing the default is a breaking change and I am not the only user of the feature out there, other people 
already placed their scripts at ```/usr/share/freerdp/action.sh``` (e.g. https://github.com/FreeRDP/FreeRDP/pull/3457#issuecomment-254855937)

**Comment by akallabeth** [comment]
@volth The default is not set this way, the struct just contains a human readable representation of it (if required)

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@bmiklautz You agree with these changes?

**Comment by bmiklautz** [comment]
@volth I share your considerations that people already use this feature. However as mentioned it was more for development but if a command line parameter is available it's "visible" and I could think it's more used as well (once the format is documented ;). Therefore I'd rather have a sensible path in the .config directory than  /usr/share/freerdp/action.sh which isn't usually writable by users.

**Comment by bmiklautz** [comment]
thanks.

**Pull request merged**
