### PR TITLE
Split h264 subsystems in different files

### PR DESCRIPTION
**Pull request by hardening**

### CODE REVIEW

**Comment by hardening** [comment]
@akallabeth fixed TAG declaration and I've checked the other files

**Comment by akallabeth** [comment]
@hardening Compilation on my side fails, looks like you forgot an include in ```h264_openh264.c```

**Comment by hardening** [comment]
@akallabeth arf you're damn right, I guess it means that openh264 is not installed on the CI...

**Comment by hardening** [comment]
That should be ok now.

**Comment by hardening** [comment]
anyone to merge it ?

**Pull request merged**
