### PR TITLE
Fix colors on big endian

### PR DESCRIPTION
**Pull request by ondrejholy**
Let's fix the colors on big endian finally https://github.com/FreeRDP/FreeRDP/issues/2520. See commit descriptions...

Tested all combinations of 16/24/32 depth of X11 and /bpp:16/24/32 on systems with little/big endian. It seems it is working correctly, just /bpp:32 doesn't work correctly on X11 with 32 depth, but this is a problem even with master, see https://github.com/FreeRDP/FreeRDP/issues/4134. I did not test with /bpp:8 and lower systematically, but it seems that there are still some minor issues...

### CODE REVIEW

**Comment by ondrejholy** [comment]
@akallabeth To be honest, I've never tried that options, but I will try them...

**Comment by ondrejholy** [comment]
I tried xfreerdp /u:... /p:... /v:... /rfx and xfreerdp /u:... /p:... /v:... /gfx:RFX (isn't this the same as /rfx?) on big endian with 16/24/32 depth of X11 and it seems working correctly. I did not try AVC420|AVC444, because I don't see any available h264 codec in s360x repositories...

**Comment by hardening** [comment]
@akallabeth feel free to merge it if it seems ok for you

**Comment by akallabeth** [comment]
@ondrejholy No, ```/rfx``` uses old style transport, ```/gfx``` uses the newer gfx channel transport. Codec wise they are (mostly) the same though. As for H264 options, openh264 works quite fine and for a test a custom compile should suffice (although I assume it is working too, if any GFX option is working)

**Comment by akallabeth** [comment]
@ondrejholy Ok, looks good, I'll merge it. Just another test I forgot to mention: did you try ```/gdi:sw``` too?

**Comment by ondrejholy** [comment]
@akallabeth Great, thanks! Yes, I forgot to mention that I tested everything also with /gdi:sw/hw.

**Pull request merged**
