### PR TITLE
Build system improvements and changes

### PR DESCRIPTION
**Pull request by bmiklautz**
* get rid of FREERDP_MONOLITHIC_BUILD 
*  cleanup and improve exports (split into freerdp, freerdp-server, freerdp-client)
* don't install unnecessary linker archives when building with STATIC_CHANNELS
* add new command line option /buildconfig

### CODE REVIEW

**Comment by akallabeth** [comment]
LGTM, +1

**Comment by HenryJacques** [comment]
@bmiklautz why did you remove MONOLITHIC_BUILD?
We frequently use it!

Thanks

**Comment by bmiklautz** [comment]
@HenryJacques the functionality MONOLITHIC_BUILD offered is default since a "while" (see commit removed0313ca3622baec53425b749e65caa202015894de). There is no non monolithic build anymore. The cmake option was only kept for compatibility.

**Comment by bmiklautz** [comment]
@HenryJacques just make clear this is on master.

**Comment by HenryJacques** [comment]
@bmiklautz  yes you're right. My mistake. I checked with the dev and we only use static libs now.

**Comment by hardening** [comment]
+1

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Pull request merged**
