### PR TITLE
Fix variable passsed to HashCallback with MIC.

### PR DESCRIPTION
**Pull request by oshogbo**
Fix value where the MessageIntegrityCheck is stored.
The value in the context is not set yet and we need one from
authentication message.

### CODE REVIEW

**Comment by mfleisz** [comment]
@akallabeth Just had a quick look over the code and it is true that context->MessageIntegrityCheck is never initialized/set before the callback is called. However I agree that the proposed fix doesn't look like a real solution to that problem ...

**Comment by akallabeth** [comment]
@mfleisz Looks like it should be initialized at the end of `ntlm_read_AuthenticateMessage` in client mode?

**Comment by mfleisz** [comment]
@akallabeth Yeah I guess a CopyMemory should to the trick there (as it is already done for the other fields). 
For the server side I think it should be enough to ensure that `nltm_compute_message_integrity_check` is called before `ntlm_compute_XX_v2_response` in `ntlm_server_AuthenticateComplete`?

**Comment by akallabeth** [comment]
@oshogbo Could you adjust the pull according to the changes discussed?

**Comment by oshogbo** [comment]
Yes I plan to do so just - need some more time also to test it. ;)
Thanks for your patience.

**Comment by oshogbo** [comment]
I did a little bit research and it turns out we cant ensure that nltm_compute_message_integrity_check is called before ntlm_compute_XX_v2_response in ntlm_server_AuthenticateComplete because it's depends on them.

The SessionBaseKey is calculated based on NTLM hash. The KeyExchangeKey is a copy of SessionBaseKey. The RandomSessionKey is generated base on the KeyExchangeKey. The ExportedSessionKey is a copy of the RandomSessionKey. Finally to calculate MIC we use ExportedSesssionKey which is based on SessionBaseKey which i just proved.

This is the chicken and egg problem IMHO. I would stay with this version of code.

**Comment by akallabeth** [comment]
@oshogbo So, then `context->MessageIntegrityCheck` is unused? Would remove it then to avoid confusion.

**Comment by oshogbo** [comment]
@akallabeth Done.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
