### PR TITLE
Backport TLS1.2 enforcement and version control from master to stable2.0

### PR DESCRIPTION
**Pull request by sivagudivadaz**
backported FreeRDP#7987
backported FreeRDP#8048

Changes in this PR are backports/cherry-picks that add a new flag: `enforce-tlsv1_2` to the stable2.0 branch. 

### Testing notes: 
- [ ]  Enable both TLS1.2 and TLS1.3 protocols on a windows 2019 server and attempt to connect - the connection should fail with 

`transport_connect_tls:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]` (This is because windows 2019 server has experimental support for TLS1.3)

- [ ] With the same setup, attempt to connect again but pass the `enforce-tlsv1_2` flag and the connection should succeed.

## This is how are pull requests handled by FreeRDP
1. Every new pull request needs to build and pass the unit tests at https://ci.freerdp.com

## Preparations before creating a pull
* Rebase your branch to current master, no merges allowed!
* Try to clean up your commit history, group changes to commits
* Check your formatting! A _clang-format_ script can be found at ```.clang-format```
  * The cmake target ```clangformat``` reformats the whole codebase
* Optional (but higly recommended)
  * Run a clang scanbuild before and after your changes to avoid introducing new bugs
  * Run your compiler at pedantic level to check for new warnings

### CODE REVIEW

**Comment by pnowack** [comment]
Always please cherry-pick backports to preserve the original author. It's usually seen rude to take over the authorship here.  

Also update the changelog (You can do that one in its own commit).

**Comment by sivagudivadaz** [comment]
Is it fine if I backport my original changes and cherry-pick the other commit ? Don't want to bring in all the changes from my cherry-pick

**Comment by pnowack** [comment]
> Is it fine if I backport my original changes and cherry-pick the other Author's commit ?

Yes, that's fine.

**Comment by pnowack** [comment]
@freerdp-bot Would you be so kind and test this MR?

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Pull request merged**
