### PR TITLE
Manpage and /help update

### PR DESCRIPTION
**Pull request by ondrejholy**
I made manpage update https://github.com/FreeRDP/FreeRDP/pull/4129 for stable-1.0 recently. I was asked by @bmiklautz to make manpage update also for master. So here is a proposal, I hope you will like it. See commit descriptions for details what is changed...

### CODE REVIEW

**Comment by ondrejholy** [comment]
Is possible to find somewhere what exactly failed? I just see "windows_msbuild_vs2010 ? win32,vs2010 completed with result FAILURE" in the Console output, but can't find more details...

**Comment by bmiklautz** [comment]
@ondrejholy   https://ci.freerdp.com/job/windows_msbuild_vs2010/413/arch=win32,label=vs2010/console
```
  ..\..\..\source\client\common\cmdline.c(243): error C2146: syntax error : missing ';' before
  identifier 'overlong'
  [C:\jenkins-freerdp\workspace\windows_msbuild_vs2010\arch\win32\label\vs2010\build\client\common\freerdp-client.vcxproj]

```

**Comment by ondrejholy** [comment]
@bmiklautz Ha, thanks, should be ok now and rebased to master :-)

**Comment by ondrejholy** [comment]
Hmm, it isn't but I suppose that `ERROR: Error fetching remote repo 'origin'` is not my fault...

**Comment by akallabeth** [comment]
@hardening @bmiklautz Any objections merging this one?

**Pull request merged**
