### PR TITLE
[locale,keyboard] fix keyboard mapping on apple

### PR DESCRIPTION
**Pull request by akallabeth**
fix the client side mapping for x11 keycodes on apple

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test properly!

**Review by hardening — APPROVED** [review]
Looks ok for me

**Comment by bmiklautz** [comment]
Works!  The real fix was the missing `keycode - 8`.

**Review by bmiklautz — APPROVED** [review]

**Pull request merged**
