### PR TITLE
Fix pkg-config check for libswscale

### PR DESCRIPTION
**Pull request by floppym**

### CODE REVIEW

**Comment by akallabeth** [comment]
@floppym where did you need the lib prefix for pkgconfig?
But there seems to be an issue with the find_path below indeed.

**Comment by floppym** [comment]
ffmpeg installs `libswscale.pc`, not `swscale.pc`. A quick test confirms this:
```
% pkg-config --libs swscale
Package swscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `swscale.pc'
to the PKG_CONFIG_PATH environment variable
Package 'swscale', required by 'virtual:world', not found
% pkg-config --libs libswscale
-lswscale
```
Also, you can confirm this by comparing the cmake output with/without my patch:
```
% cmake -DWITH_SWSCALE=ON -B build
...
-- Checking for module 'swscale'
--   Package 'swscale', required by 'virtual:world', not found
```
```
% cmake -DWITH_SWSCALE=ON -B build
...
-- Checking for module 'libswscale'
--   Found libswscale, version 5.5.100
```

**Comment by akallabeth** [comment]
@floppym I'm asking because detection works on my dev machine (afk, so can not verify which pc file it detects)
So, which os / version? Will check tomorrow.

**Comment by floppym** [comment]
This is on Gentoo Linux with ffmpeg-4.2.1 installed.
```
% cat /usr/lib64/pkgconfig/libswscale.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=/usr/include

Name: libswscale
Description: FFmpeg image rescaling library
Version: 5.5.100
Requires:
Requires.private: libavutil >= 56.31.100
Conflicts:
Libs: -L${libdir}  -lswscale
Libs.private: -lm
Cflags: -I${includedir}
```

**Comment by floppym** [comment]
My guess is that is that the pkgconfig check fails on your dev machine, but cmake is able to find the header/library in the default location via find_path / find_library anyway.

**Comment by akallabeth** [comment]
@floppym thank you, you were right. Fixed the whole script and opened a new pr.

**Pull request closed without merging**
