### PR TITLE
Fixed CLIPRDR_FILEDESCRIPTOR

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by mfleisz** [comment]
+1

**Comment by akallabeth** [comment]
@awakecoding @bmiklautz @hardening Any objections / suggestions for this pull?

**Comment by hardening** [comment]
@akallabeth no objections, but I don't understand what's the point of this PR...

**Comment by akallabeth** [comment]
@hardening I'm working on some clipboard file related stuff and this (incomplete) struct was an issue.

**Pull request merged**
