### PR TITLE
Silenced VerifyX509Certificate logging.

### PR DESCRIPTION
**Pull request by akallabeth**
Now only writing log entries if something was an actual
error, otherwise stay silent.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by akallabeth** [comment]
@awakecoding @bmiklautz @hardening Any objections to this pull? It reduces the (unnecessary) log messages when using ```ExternalCertificateManagement``` and adds warnings for broken settings / callbacks.

**Comment by mfleisz** [comment]
+1

**Comment by bmiklautz** [comment]
+1

**Pull request merged**
