### PR TITLE
winpr/clipboard: Also save lastWriteTime for FILEDESCRIPTORW

### PR DESCRIPTION
**Pull request by pnowack**
Quoting the commit message here:

```
Currently, when a local uri-list is converted into a FILEDESCRIPTORW
list, WinPR doesn't submit the last write time for each file.
The result of this is that the last write time of each file on the
other peer will have the current time and not the actual last write
time that is present on the peer, where the files were copied from.

Fix this by also writing the last write time in addition to the
FD_WRITESTIME flag.
```

Tested with the stable-2.0 branch, but should also work fine with current master.

### CODE REVIEW

**Comment by pnowack** [comment]
test

**Comment by pnowack** [comment]
Seems that the `FD_SHOWPROGRESSUI` flag has been renamed on the master branch to `FD_PROGRESSUI`.

@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by akallabeth — APPROVED** [review]
LGTM

**Pull request merged**
