### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by hardening — APPROVED** [review]
Looks ok for me even if the CI doesn't like

**Comment by akallabeth** [comment]
@freerdp-bot test
@hardening yes, need to update SDK/NDK

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@hardening needed to update default `JRE` to `>=11` for this to work

**Pull request merged**
