### PR TITLE
Server/shadow: Protect X operations on shared subystem X11 display with X11 display lock

### PR DESCRIPTION
**Pull request by realjiangms**

### CODE REVIEW

**Comment by realjiangms** [comment]
Lack of X11 Display lock could cause deadlock in X operation eventually

**Comment by bmiklautz** [comment]
@realjiangms did you encounter any dead lock?

**Comment by realjiangms** [comment]
Yes, when I'm testing the mouse draw back fix with an environment that latency > 200ms.
The backtrace shows deadlock happen in XReply(). It seems X11 always cause deadlock if we don't protect XDisplay with XLockDisplay.

**Comment by realjiangms** [comment]
The blocked threads are mouse input and screen capture

**Comment by bmiklautz** [comment]
@realjiangms thanks!

**Pull request merged**
