### PR TITLE
Clear codec buffer resize fix

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by hardening** [comment]
There's misc occurrences of "const UINT32 DstFormat", I don't see the point for these changes.

**Comment by akallabeth** [comment]
@hardening Well, just to ensure that it is not accidentally changed in the function.

**Comment by hardening** [comment]
@akallabeth really I don't see the point to add a const modifier on a value that is passed by copy...

**Comment by akallabeth** [comment]
@hardening A guarantee for the compiler that the value must not be changed within the function body. May be redundant but if it is there it is less likely to be overwritten by accident. (which was the point, I was tracing a invalid colour format, and once there it does not hurt to have it.)

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@hardening @mfleisz Ok, removed the const.

**Pull request merged**
