### PR TITLE
Use freerdp_settings_[s|g]et* api to access proxy vaiables.

### LINKED ISSUE #6414: memory leak in proxy code
```
Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x4cc4f7 in calloc /var/tmp/paludis/build/dev-libs-compiler-rt-10.0.1/work/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x7f51d693ce90 in proxy_parse_uri /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:356:28
    #2 0x7f51d6939a8c in proxy_read_environment /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:284:4
    #3 0x7f51d69393c0 in proxy_prepare /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:79:3
    #4 0x7f51d6950b27 in transport_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/transport.c:419:7
    #5 0x7f51d684d4cf in nego_tcp_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:302:25
    #6 0x7f51d684e874 in nego_transport_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:317:7
    #7 0x7f51d684ddd9 in nego_attempt_nla /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:457:7
    #8 0x7f51d68456c2 in nego_send /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:817:3
    #9 0x7f51d684469a in nego_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:185:4
    #10 0x7f51d6905465 in rdp_client_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/connection.c:333:7
    #11 0x7f51d68c7e14 in freerdp_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/freerdp.c:197:11
    #12 0x592e84 in xf_client_thread /home/sss/install/git/work/FreeRDP/client/X11/xf_client.c:1524:11
    #13 0x7f51d62d893b in thread_launcher /home/sss/install/git/work/FreeRDP/winpr/libwinpr/thread/thread.c:327:7
    #14 0x7f51d608353e  (/usr/x86_64-pc-linux-gnu/lib/libpthread.so.0+0x953e)

SUMMARY: AddressSanitizer: 14 byte(s) leaked in 1 allocation(s).


```

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #6414

### CODE REVIEW

**Comment by sss123next** [comment]
```
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[19:04:32:971] [19458:19465] [DEBUG][com.freerdp.core.nego] - Attempting NLA security

Thread 2 "xfreerdp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff154c700 (LWP 19465)]
0x00007ffff6dad825 in __strlen_avx2 () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
(gdb) where
#0  0x00007ffff6dad825 in __strlen_avx2 () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x000000000044700e in __interceptor_strdup (s=0xd <error: Cannot access memory at address 0xd>) at /var/tmp/paludis/build/dev-libs-compiler-rt-10.0.1/work/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:448
#2  0x00007ffff70bb484 in _strdup (strSource=0xd <error: Cannot access memory at address 0xd>) at crt/string.c:45
#3  0x00007ffff75056e4 in freerdp_settings_set_string_ (settings=0x62e000000400, id=2016, val=0xd <error: Cannot access memory at address 0xd>, cleanup=1) at common/settings_getters.c:2599
#4  0x00007ffff750794a in freerdp_settings_set_string (settings=0x62e000000400, id=2016, val=0xd <error: Cannot access memory at address 0xd>) at common/settings_getters.c:2773
#5  0x00007ffff76dba5b in proxy_parse_uri (settings=0x62e000000400, uri=0x60300005fbc7 "192.168.0.254:3128") at core/proxy.c:360
#6  0x00007ffff76d86f9 in proxy_read_environment (settings=0x62e000000400, envname=0x7ffff794b040 <str> "https_proxy") at core/proxy.c:285
#7  0x00007ffff76d82db in proxy_prepare (settings=0x62e000000400, lpPeerHostname=0x7ffff154a540, lpPeerPort=0x7ffff154a530, lpProxyUsername=0x7ffff154a560, lpProxyPassword=0x7ffff154a580) at core/proxy.c:79
#8  0x00007ffff76ef4b8 in transport_connect (transport=0x611000000180, hostname=0x602000005650 "192.168.1.115", port=3389, timeout=15) at core/transport.c:419
#9  0x00007ffff75ec4b0 in nego_tcp_connect (nego=0x60f0000004f0) at core/nego.c:302
#10 0x00007ffff75ed855 in nego_transport_connect (nego=0x60f0000004f0) at core/nego.c:317
#11 0x00007ffff75ecdba in nego_attempt_nla (nego=0x60f0000004f0) at core/nego.c:457
#12 0x00007ffff75e46a3 in nego_send (nego=0x60f0000004f0) at core/nego.c:817
#13 0x00007ffff75e367b in nego_connect (nego=0x60f0000004f0) at core/nego.c:185
#14 0x00007ffff76a4406 in rdp_client_connect (rdp=0x614000000240) at core/connection.c:333
#15 0x00007ffff7666df5 in freerdp_connect (instance=0x616000000380) at core/freerdp.c:197
#16 0x0000000000592e85 in xf_client_thread (param=0x616000000380) at xf_client.c:1524
#17 0x00007ffff707793c in thread_launcher (arg=0x6110000007c0) at thread/thread.c:327
#18 0x00007ffff6e2253f in start_thread () from /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0
#19 0x00007ffff6d4a3b3 in clone () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6

```

**Comment by akallabeth** [comment]
@sss123next good catch, updated the pr.

**Comment by sss123next** [comment]
```
[ 46%] Building C object libfreerdp/CMakeFiles/freerdp.dir/core/proxy.c.o
cd /home/sss/install/git/work/FreeRDP/libfreerdp && /usr/host/bin/ccache /usr/host/bin/clang -DBUILD_TESTING -DCMAKE_BUILD_TYPE=Debug -DEXT_PATH=\"/usr/local/lib64/freerdp3/extensions\" -DFREERDP_EXPORTS -DFREERDP_TEST_EXPORTS -DHAVE_CONFIG_H -DSWSCALE_FOUND=1 -DWINPR_EXPORTS -DWITH_OPENSSL -DWITH_WAYLAND -DWITH_X11 -DWITH_XKBFILE -D_FILE_OFFSET_BITS=64 -Dfreerdp_EXPORTS -I/home/sss/install/git/work/FreeRDP -I/home/sss/install/git/work/FreeRDP/include -I/home/sss/install/git/work/FreeRDP/winpr/include -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -g -fsanitize=address -fPIC -o CMakeFiles/freerdp.dir/core/proxy.c.o -c /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c
/home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:351:10: error: read-only variable is not assignable
                *pport = '\0';
                ~~~~~~ ^
1 error generated.


```

**Comment by sss123next** [comment]
do not rush ), this is not so urgent )

**Pull request merged**
