### PR TITLE
Fix build with newer uclibc versions

### PR DESCRIPTION
**Pull request by baruchsiach**
uClibc master branch, as well as uclibc-ng add eventfd_{read,write}
definitions. Instead of testing for __UCLIBC__, have cmake explicitly check
for the existence of eventfd_read and save the result in
WITH_EVENTFD_GLIBC_EXT.

Fixes build errors like:

.../winpr/libwinpr/synch/event.c:120:12: error: static declaration of 'eventfd_read' follows non-static declaration
 static int eventfd_read(int fd, eventfd_t* value)
            ^
In file included from .../winpr/libwinpr/synch/event.c:39:0:
.../usr/include/sys/eventfd.h:37:12: note: previous declaration of 'eventfd_read' was here
 extern int eventfd_read (int __fd, eventfd_t *__value);
            ^
.../winpr/libwinpr/synch/event.c:125:12: error: static declaration of 'eventfd_write' follows non-static declaration
 static int eventfd_write(int fd, eventfd_t value)
            ^
In file included from .../winpr/libwinpr/synch/event.c:39:0:
.../usr/include/sys/eventfd.h:40:12: note: previous declaration of 'eventfd_write' was here
 extern int eventfd_write (int __fd, eventfd_t __value);

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot please test that my friend

**Comment by hardening** [comment]
LGTM

**Comment by hardening** [comment]
If someone wants to +1, feel free to also merge it.

**Comment by bmiklautz** [comment]
@baruchsiach if uClibc and uclibc-ng now also have  eventfd_{read,write} what about renaming 
 WITH_EVENTFD_GLIBC_EXT to  WITH_EVENTFD_EXT or so since GLIBC isn't the only one that supports this functions.
Otherwise +1.

**Comment by baruchsiach** [comment]
@bmiklautz `eventfd_{read,write}` are documented  "Additional glibc features" in the [eventfd(2)](http://man7.org/linux/man-pages/man2/eventfd.2.html) man page. So I think `WITH_EVENTFD_GLIBC_EXT` is appropriate here, while `WITH_EVENTFD_EXT` sounds too generic to me. But I have no problem changing that if you insist.

**Comment by hardening** [comment]
@baruchsiach I think @bmiklautz idea was "we have eventfd_[read|write] native support" and that's it, no matter if it's a Glibc extension or not...

**Comment by baruchsiach** [comment]
@hardening @bmiklautz So is `WITH_EVENTFD_READ_WRITE` OK?

**Comment by hardening** [comment]
@baruchsiach WITH_EVENTFD_READ_WRITE looks good to me.

**Comment by bmiklautz** [comment]
@baruchsiach WITH_EVENTFD_READ_WRITE looks perfect ;).
@hardening thank you for clarifying.

**Comment by baruchsiach** [comment]
Sent an update PR at https://github.com/FreeRDP/FreeRDP/pull/2584

**Pull request closed without merging**
