### PR TITLE
Smartcard logon rdp

### PR DESCRIPTION
**Pull request by informatimago**
Added /smartcard-logon:rdp option.
cf. https://github.com/informatimago/FreeRDP/wiki/smartcard-logon (it will be copied to FreeRDP/FreeRDP wiki once the merge is completed).

Basically; sets the autologin flag which along the smartcard redirection allows MS-Windows to use Smartcard Logon.

This patch only works with RDP negotiation.

The /smartcard option can be given several times and allows to select the smartcard readers that are redirected (some card or smartcard readers can interfere with the Smartcard Logon process.

### CODE REVIEW

**Comment by akallabeth** [comment]
@informatimago sorry for the late reply.
Could you clean up this pull a bit? 
* Introducing another layer of function abstractions does not seem like a really good idea
* What are you trying to achieve with the filter in smartcard?

**Comment by informatimago** [comment]
@akallabeth 

# layer of function abstractions

I'm not sure what you're refering to with "layer of function
abstractions", but if it's the str.c module, this let us avoid
duplicating code just because of WCHAR vs. char.  There is a lot of code duplication
(and worse, alternative that are implemented only in *A or *W but not both for no
apparent reason).  This all could be avoided by the systematic use of such a string
abstration.

Actually, it should probably be generalized even more, and augmented
to deal with the problem of the various string list formats (arrays of
strings, arrays of pointers to strings, msz, WLinkedList of strings,
etc).  All those different representations for the same thing lead to
a lot of duplicated code, and the associated risk of bugs.

One clear improvement that would have to be made, is to generalize
wrappers for strings, so that functions such as
LinkedList_StringHasSubstring could take as arguments strings in
different formats, and process them generically, instead of hardwiring
a specific format for each argument.  We can see the same problem in
some of the sspi API where some functions are actually mixed, taking
both *W or *A strings.

Note that the alternative of having two copies of the same functions,
one using char (or BYTE), and another WCHAR wouldn't be a problem to
write (we could generate both version from the same emacs lisp macro).
But it would be a maintainance headache, since most people aren't able
to deal with code generating code (otherwise you'd write it in lisp,
not in C ;-)).  I don't think this is a better solution.

# The purpose of the smartcard filter is to deal with the following problem we have:

- we are using IAS-ECC Smartcard to perform the smartcard logon,

- at the same time, we are using a token that is identified as a
  smartcard too, but it doesn't contain IAS-ECC files (this token is a
  pre-requisite in our use case, since it's used to establish an IPsec
  tunnel).

The problem is that when Windows sees this token smartcard, with the wrong files,
it rejects the smartcard logon, and switches to the login dialog.

Also, even without this bug, it is not necessary and it is preferable to avoid
redirect this token to the remote Windows.

So the filter feature allows the user to select what Smartcard will be redirected.
See more details at: https://github.com/informatimago/FreeRDP/wiki/smartcard-logon

**Comment by informatimago** [comment]
@akallabeth 
For example, to implement the compare function, we could write:

```
#define GENERATE_CONTAINS(T, TCHAR)                                     \
    BOOL contains ## T (TCHAR * string, char * substring)               \
    {                                                                   \
        int wlen = strlen ## T(string);                                 \
        int slen = strlen(substring);                                   \
        int end = wlen - slen;                                          \
        int i = 0;                                                      \
        for (i = 0; i < end; i ++ )                                     \
        {                                                               \
            if (ncompare ## T(string + i, substring, slen) == 0)        \
            {                                                           \
                return TRUE;                                            \
            }                                                           \
        }                                                               \
        return FALSE;                                                   \
    } 

GENERATE_CONTAINS(A, char)
GENERATE_CONTAINS(W, WCHAR)

BOOL contains (int widechar, BYTE * string, char * substring)
{
    if (widechar)
    {
        return containsW((WCHAR*)string,substring);
    }
    else
    {
        return containsA((char*)string,substring);
    }
}

```
So granted, containsA and containsW would be more efficient than a contain that uses the funs, but do we really need to exchange the few cycles spared, against the additionnal maintainance work represented by the duplicated code in the C sources or the C macro complexity?   And this doesn't remove the need for a dispatching contains function anyways.

**Comment by akallabeth** [comment]
@informatimago yes, but it will needlessly break API stuff (we already struggle to keep it somewhat stable)

**Comment by informatimago** [comment]
@akallabeth Please, tell me how you would prefer me to write it.  I understand that you want to avoid the use of the funs structure with the low level alternative functions for char or WCHAR.  Is the use of macros to generate alternate *A and *W functions the prefered way?

**Comment by akallabeth** [comment]
@informatimago Best avoid adding these functions. You have either `WCHAR` or `char` you're working with. Conversion functions are already there `ConvertFromUnicode` as well as comparison functions.

**Comment by gofish543** [comment]
When I pull this repo and attempt to compile the merging branch I get the following errors...
sudo xargs rm < install_manifest.txt > /dev/null; cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON . | grep smartcard; sudo cmake --build . --target install | grep smartcard;
An error occurred while redirecting file 'install_manifest.txt'
open: No such file or directory
FREERDP_VERSION=2.0.0-dev3
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
[1/51] Building C object channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o
FAILED: channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o 
/usr/bin/cc -DFREERDP_EXPORTS -DHAVE_CONFIG_H -DNDEBUG -DWINPR_EXPORTS -DWITH_OPENSSL -D_FILE_OFFSET_BITS=64 -I. -Iinclude -Iwinpr/include -Irdtk/include -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -O3 -DNDEBUG -fPIC -MD -MT channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o -MF channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o.d -o channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o   -c channels/smartcard/client/str.c
channels/smartcard/client/str.c: In function ‘towide’:
channels/smartcard/client/str.c:35:31: warning: pointer targets in passing argument 3 of ‘ConvertToUnicode’ differ in signedness [-Wpointer-sign]
In file included from channels/smartcard/client/str.c:24:0:
channels/smartcard/client/str.c:35:2: error: too many arguments to function ‘ConvertToUnicode’
In file included from channels/smartcard/client/str.c:24:0:
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:51:5: error: conflicting types for ‘compare’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:82:5: note: previous declaration of ‘compare’ was here
channels/smartcard/client/str.c: In function ‘compare’:
channels/smartcard/client/str.c:58:27: warning: passing argument 1 of ‘compareW’ from incompatible pointer type [-Wincompatible-pointer-types]
channels/smartcard/client/str.c:46:5: note: expected ‘BYTE * {aka unsigned char *}’ but argument is of type ‘WCHAR * {aka short unsigned int *}’
channels/smartcard/client/str.c:58:44: warning: passing argument 2 of ‘compareW’ from incompatible pointer type [-Wincompatible-pointer-types]
channels/smartcard/client/str.c:46:5: note: expected ‘BYTE * {aka unsigned char *}’ but argument is of type ‘WCHAR * {aka short unsigned int *}’
channels/smartcard/client/str.c: In function ‘ncompareW’:
channels/smartcard/client/str.c:80:42: error: expected ‘)’ before ‘;’ token
channels/smartcard/client/str.c:80:17: warning: passing argument 1 of ‘wcsncmp’ from incompatible pointer type [-Wincompatible-pointer-types]
                 from channels/smartcard/client/str.c:24:
channels/smartcard/client/str.c:80:25: warning: passing argument 2 of ‘wcsncmp’ from incompatible pointer type [-Wincompatible-pointer-types]
                 from channels/smartcard/client/str.c:24:
channels/smartcard/client/str.c:81:1: error: expected ‘;’ before ‘}’ token
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:83:5: error: conflicting types for ‘ncompare’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:99:5: note: previous declaration of ‘ncompare’ was here
channels/smartcard/client/str.c: In function ‘containsA’:
channels/smartcard/client/str.c:107:13: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c:107:13: note: each undeclared identifier is reported only once for each function it appears in
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:123:6: error: conflicting types for ‘contains’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:126:6: note: previous declaration of ‘contains’ was here
channels/smartcard/client/str.c: In function ‘contains’:
channels/smartcard/client/str.c:125:13: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:142:6: error: conflicting types for ‘ncopy’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:111:6: note: previous declaration of ‘ncopy’ was here
channels/smartcard/client/str.c: In function ‘ncopy’:
channels/smartcard/client/str.c:148:3: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:152:6: error: conflicting types for ‘LinkedList_StringHasSubstring’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:143:6: note: previous declaration of ‘LinkedList_StringHasSubstring’ was here
channels/smartcard/client/str.c: In function ‘LinkedList_StringHasSubstring’:
channels/smartcard/client/str.c:158:16: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszFilterStrings’:
channels/smartcard/client/str.c:169:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:167:28: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:169:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:173:9: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszStringsPrint’:
channels/smartcard/client/str.c:221:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:219:41: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:221:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:228:21: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszStringsLog’:
channels/smartcard/client/str.c:236:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:234:45: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:236:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:249:21: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszSize’:
channels/smartcard/client/str.c:263:11: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c:267:1: warning: control reaches end of non-void function [-Wreturn-type]

**Comment by gofish543** [comment]
When I attempt to compile this branch the following errors occur...
gofish543@Pavilion-gofish543 ~/FreeRDPSmartCard> 
sudo xargs rm < install_manifest.txt; cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON . | grep smartcard; sudo cmake --build . --target install | grep smartcard;
An error occurred while redirecting file 'install_manifest.txt'
open: No such file or directory
FREERDP_VERSION=2.0.0-dev3
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
[5/46] Building C object channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o
FAILED: channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o 
/usr/bin/cc -DFREERDP_EXPORTS -DHAVE_CONFIG_H -DNDEBUG -DWINPR_EXPORTS -DWITH_OPENSSL -D_FILE_OFFSET_BITS=64 -I. -Iinclude -Iwinpr/include -Irdtk/include -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -O3 -DNDEBUG -fPIC -MD -MT channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o -MF channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o.d -o channels/smartcard/client/CMakeFiles/smartcard-client.dir/str.c.o   -c channels/smartcard/client/str.c
channels/smartcard/client/str.c: In function ‘towide’:
channels/smartcard/client/str.c:35:31: warning: pointer targets in passing argument 3 of ‘ConvertToUnicode’ differ in signedness [-Wpointer-sign]
In file included from channels/smartcard/client/str.c:24:0:
channels/smartcard/client/str.c:35:2: error: too many arguments to function ‘ConvertToUnicode’
In file included from channels/smartcard/client/str.c:24:0:
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:51:5: error: conflicting types for ‘compare’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:82:5: note: previous declaration of ‘compare’ was here
channels/smartcard/client/str.c: In function ‘compare’:
channels/smartcard/client/str.c:58:27: warning: passing argument 1 of ‘compareW’ from incompatible pointer type [-Wincompatible-pointer-types]
channels/smartcard/client/str.c:46:5: note: expected ‘BYTE * {aka unsigned char *}’ but argument is of type ‘WCHAR * {aka short unsigned int *}’
channels/smartcard/client/str.c:58:44: warning: passing argument 2 of ‘compareW’ from incompatible pointer type [-Wincompatible-pointer-types]
channels/smartcard/client/str.c:46:5: note: expected ‘BYTE * {aka unsigned char *}’ but argument is of type ‘WCHAR * {aka short unsigned int *}’
channels/smartcard/client/str.c: In function ‘ncompareW’:
channels/smartcard/client/str.c:80:42: error: expected ‘)’ before ‘;’ token
channels/smartcard/client/str.c:80:17: warning: passing argument 1 of ‘wcsncmp’ from incompatible pointer type [-Wincompatible-pointer-types]
                 from channels/smartcard/client/str.c:24:
channels/smartcard/client/str.c:80:25: warning: passing argument 2 of ‘wcsncmp’ from incompatible pointer type [-Wincompatible-pointer-types]
                 from channels/smartcard/client/str.c:24:
channels/smartcard/client/str.c:81:1: error: expected ‘;’ before ‘}’ token
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:83:5: error: conflicting types for ‘ncompare’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:99:5: note: previous declaration of ‘ncompare’ was here
channels/smartcard/client/str.c: In function ‘containsA’:
channels/smartcard/client/str.c:107:13: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c:107:13: note: each undeclared identifier is reported only once for each function it appears in
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:123:6: error: conflicting types for ‘contains’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:126:6: note: previous declaration of ‘contains’ was here
channels/smartcard/client/str.c: In function ‘contains’:
channels/smartcard/client/str.c:125:13: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:142:6: error: conflicting types for ‘ncopy’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:111:6: note: previous declaration of ‘ncopy’ was here
channels/smartcard/client/str.c: In function ‘ncopy’:
channels/smartcard/client/str.c:148:3: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: At top level:
channels/smartcard/client/str.c:152:6: error: conflicting types for ‘LinkedList_StringHasSubstring’
In file included from channels/smartcard/client/str.c:28:0:
channels/smartcard/client/str.h:143:6: note: previous declaration of ‘LinkedList_StringHasSubstring’ was here
channels/smartcard/client/str.c: In function ‘LinkedList_StringHasSubstring’:
channels/smartcard/client/str.c:158:16: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszFilterStrings’:
channels/smartcard/client/str.c:169:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:167:28: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:169:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:173:9: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszStringsPrint’:
channels/smartcard/client/str.c:221:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:219:41: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:221:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:228:21: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszStringsLog’:
channels/smartcard/client/str.c:236:7: error: ‘widechar’ redeclared as different kind of symbol
channels/smartcard/client/str.c:234:45: note: previous definition of ‘widechar’ was here
channels/smartcard/client/str.c:236:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
channels/smartcard/client/str.c:249:21: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c: In function ‘mszSize’:
channels/smartcard/client/str.c:263:11: error: ‘funs’ undeclared (first use in this function); did you mean ‘puts’?
channels/smartcard/client/str.c:267:1: warning: control reaches end of non-void function [-Wreturn-type]
gofish543@Pavilion-gofish543 ~/FreeRDPSmartCard>

**Comment by gofish543** [comment]
What is the status of this pull request?

**Comment by akallabeth** [comment]
@gofish543 waiting for rebase/cleanup

**Comment by informatimago** [comment]
> On 21 Aug 2018, at 09:41, akallabeth <notifications@github.com> wrote:
> 
> @gofish543 <https://github.com/gofish543> waiting for rebase/cleanup
> 
> 
Cleanup done; I’m starting the rebase.

-- 
__Pascal J. Bourguignon__

**Comment by akallabeth** [comment]
@informatimago Would drop the `str.c` stuff, it is a lot of code that is not actually used and duplicates existing functions.

**Comment by informatimago** [comment]
@akallabeth 
mszFilterStrings calls:
- ncopy
- LinkedList_StringHasSubstring calls:
     - LinkedList_Enumerator_Reset
     - LinkedList_Enumerator_MoveNext
     - LinkedList_Enumerator_Current
     - contains calls:
          - ncompare calls:
               - towide

mszFilterStrings is an ESSENTIAL function to implement the feature in smartcard_operations.c that will allow us to use smartcard logon with MS-Window, preventing the forward of non-smartcard tokens that prevent MS-Windows to perform the login successfull.  Without it, the smartcard-logon-rdp has no point in being merged.




mszSize is used in TestStr.c
mszStringsLog is used in smartcard_operations.c

compare and mszStringsPrint are not currently used.  I will remove them as requested.

**Comment by akallabeth** [comment]
@informatimago `LinkedList` stuff can be replaced with the list functions already supplied by WinPR. No need to reimplement that.

**Comment by informatimago** [comment]
@akallabeth I agree with you that it's a little silly to have half a dozen different formats for lists of strings.  But it's not me who decided to write this program in C instead of Common Lisp. Now, of course, I could convert msz lists into LinkedLists and enumerate the strings in the LinkedList, but for that I would have to enumerate the msz list already!  And it wouldn't be very efficient, since we don't have a garbage collector, we'd have to free all the duplicated strings and the LinkedList after the enumeration.

**Comment by informatimago** [comment]
Rebased in  Smartcard logon rdp 3 #4823

**Pull request closed without merging**
