### PR TITLE
Implemented switchable transport layer

### PR DESCRIPTION
**Pull request by akallabeth**
Superseeds #6324

### CODE REVIEW

**Comment by akallabeth** [comment]
@sss123next I´ve cleaned up your pr a bit and implemented something that passes the usual connection tests.
I´ve removed the proxy callback as that is not required (just ensure that `FreeRDP_ProxyType == PROXY_TYPE_IGNORE` in settings when overriding the backend)

This is a first draft, still need to implement the chain to allow setting the backend dynamically (usually more than 1 transport is in use, so add some cache in the upper layers to set that on creation)

**Comment by sss123next** [comment]
do you need any assistance from me ?, it is blocker right now in my project, so i can work on full time  for this task.

**Comment by sss123next** [comment]
you dropped `DataHandler` which is essential for async io implementation.

**Comment by akallabeth** [comment]
@sss123next I´ve added `transport_parse_pdu` to check if a whole PDU is available to the exported functions.
This way you can async read a whole PDU and notify the freerdp main loop if it is available (which then reads it with your own `ReadBytes` function)

**Comment by sss123next** [comment]
yes something like this, thx.
also ii cannot push to your branch.
```
ANG= git push akallabeth-repo external_io
ERROR: Permission to akallabeth/FreeRDP.git denied to sss123next.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

i have dropped connect/accept nla/rdp, also i have eliminated tls code duplication which is removed requirement to hook connect/accept nla

but i cannot push it ...

**Pull request closed without merging**
