### PR TITLE
Mac fixes

### PR DESCRIPTION
**Pull request by akallabeth**
* Reenabled mac server compilation
* Fixed missing channel defines to configuration header
* Fixed function collistions in ```color.h``` but keep the symbols on non apple systems.

### CODE REVIEW

**Comment by bmiklautz** [comment]
regarding commit  8f27b1a what was the problem without the definitions? - Haven't seen any issues without.

**Comment by akallabeth** [comment]
There are some checks in parts of the code for that defined. Mostly in the server part, but they were never defined previously

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@lemonmojo would that do (related to #3810)?

**Comment by akallabeth** [comment]
@mfleisz @hardening @bmiklautz anyone want to merge?

**Pull request merged**
