### PR TITLE
add ffmpeg option to android build script

### PR DESCRIPTION
**Pull request by eronnen**
Allowing to compile FreeRDP on android using FFmpeg's backend

### CODE REVIEW

**Comment by akallabeth** [comment]
@eronnen looks like the compilation script for `FFMpeg` is missing?

**Comment by eronnen** [comment]
@akallabeth I added now a script to build ffmpeg if needed, I tested it with ndk r23b

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@eronnen thank you for this helpful enhancement!

**Pull request merged**
