### PR TITLE
client/cliprdr_file: Do not destroy FUSE session while using it

### PR DESCRIPTION
**Pull request by pnowack**
Quoting the commit message here:
```
When invalidating inodes, it is obligatory, that the session was not
destroyed yet.
So, in case of the FUSE loop stops before the session stops wait with
the destroyal of the session, until it is clear, that it is not used
anymore.
```

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by pnowack** [comment]
@freerdp-bot Please do another test!

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Pull request merged**
