### PR TITLE
Fixed #6014: XFCE minimized state

### LINKED ISSUE #6014: Unable to minimize remoteapp window.
Launch MS word as remoteapp.  Client minimize icon on the upper right corner of MS word window.  Expect to minimize windows.  Actual: MS word flashes screen one time and window stays on display.  If I use the linux menu from taskbar, minimize function works.

1) Using remoteapp /app option to launch MS word
2) click minimize icon on the upper right corner of MS word window

Expected:
MS word window should minimize, actual: window stay on display and there is a flashing on the MS word window one time.  This seems to be the windows takes the action to minimize and then it un-minimizes.

**Application details**
* Version of FreeRDP - Master branch as of 3/31/2020
* Command line used - client/X11/xfreerdp /u:<user> /p:<PWD> /v:<host ip> /cert-ignore /app:'C:\Program Files (x86)\Microsoft Office\Office16\WINWORD.exe'

* OS version connecting to - windows server 2016
 
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - RHEL 7.6
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] RHEL 7.6

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by roland65** [comment]
Hi,
I tested the patch in Ubuntu 20.04 with XFCE 4.14 and a Windows 10 guest in KVM/QEMU. Now, I'm able to minimize and unminimize a RemoteApp window as expected. I also tested with GNOME 3.36 desktop and I see no regression.
So, to me, the patch is OK.
Thanks,
RB

**Comment by rbreaves** [comment]
To note - this fix would have made it into 2.3.0. The ubuntu 18.04 repo still references 2.2.0 as of today.

**Comment by rbreaves** [comment]
As mentioned in the original thread I just tested 2.3.2 and with XFCE, plank, xfwm4 version 4.12.4, ubuntu 18.04 (galliumOS 3.1) and this ppa remmina-ppa-team/remmina-next-daily it still fails to minimize apps initialized via remoteapp. Please re-open this issue ticket.

Also the RDP source was a recent stable release of Windows 10 (not on a dev channel).

**Comment by akallabeth** [comment]
@rbreaves does it work on master? the fix has been merged to master, not `2.3.2`

**Pull request merged**
