### PR TITLE
fix HTTP proxy CONNECT header

### PR DESCRIPTION
**Pull request by akarl10**
https://github.com/FreeRDP/FreeRDP/commit/edeea86dd1ebed7364b0a43d1ef6c6495148f1c7 broke http proxy connect. This fixes that

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot can you test please ?

**Review by MartinHaimberger — CHANGES_REQUESTED** [review]
Size of the connect char array is 1 short (including trailing '\0") should be 9.

Also the http header (not your fault) seems to be one char short to include the '\0' if CRLF are two chars ..

**Comment by akarl10** [comment]
> Size of the connect char array is 1 short (including trailing '\0") should be 9.
> 
> Also the http header (not your fault) seems to be one char short to include the '\0' if CRLF are two chars ..

I think this was the reason why it was not obvious why it failed: a few lines later the char is written with
`Stream_Write(s, connect, ARRAYSIZE(connect));` The \0 would be written too. With [8] we hide that fact that on the "last" position there is a \0 (the string is not malloc'ed so there should not be any leak or any other issue.

**Comment by akarl10** [comment]
actually this push is not ready.. I found the next \0 in the username transmission...

I will change to strlen since this is more readable

**Comment by MartinHaimberger** [comment]
@akarl10 true, but this code is still ugly, would be better the string big enought for trailing '\0' and we use strlen or ARRAYSIZE - 1

**Comment by hardening** [comment]
@freerdp-bot can you test again please ?

**Review by MartinHaimberger — APPROVED** [review]
Nice work, much better readable.
LGTM

**Pull request merged**
