### PR TITLE
Clipboard file fixes

### PR DESCRIPTION
**Pull request by akallabeth**
* Fixes bugs in common clipboard code for creation of file contents messages.
* Fixes windows client file copy support.
* Refactoring of windows clipboard, error checks added.

### CODE REVIEW

**Comment by mfleisz** [comment]
+1

**Comment by mfleisz** [comment]
+1

**Comment by hardening** [comment]
LGTM

**Comment by akallabeth** [comment]
@awakecoding @bmiklautz @hardening Any objections to merging this?

**Pull request merged**
