### PR TITLE
wfreerdp-client: make keyboard work when /parent-window is provided

### PR DESCRIPTION
**Pull request by StefanKoell**
when starting wfreerdp.exe with /parent-window argument containing the window handle, no keyboard events were processed. This PR checks if the focused window/control is the one passed on using the argument and processes the keyboard events properly.

I've tested keyboard input with and without /parent-window argument.

See https://github.com/FreeRDP/FreeRDP/issues/7747

### CODE REVIEW

**Comment by StefanKoell** [comment]
@awakecoding @akallabeth would you mind checking my code. I'm not very familiar with C/C++, especially when it comes to naming and error handling.

Thanks!

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by awakecoding** [comment]
@akallabeth on my side everything looks good, this fixes reparenting of wfreerdp, it's an old issue that has been there for a while

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@StefanKoell thank you for your fix!
@awakecoding yes, looks good for me too. thanks.

**Pull request merged**
