### PR TITLE
remotefx: don't require data messages to come all in one chunk

### PR DESCRIPTION
**Pull request by hardening**
The spec doesn't require that FRAME_BEGIN, REGION, TILESET, and FRAME_END come all in one
chunk. This patch adds the necessary state saving.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
Please don't merge for now, I still have some fixes for this one.

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@hardening remove the WIP in the title once you are done :)

**Comment by hardening** [comment]
@akallabeth @bmiklautz ok this time

**Pull request merged**
