### PR TITLE
Fixed right shift on 32bit platforms.

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by hendwolt** [comment]
I do still suggest, to set the appropriate compiler options, to make fileStat.st_size a uint64 value:
-D_FILE_OFFSET_BITS=64
instead of casting.

**Comment by ilammy** [comment]
I'm just curious why exactly is that an issue if file size is 32-bit?

I know that signed overflow when left-shifting is undefined, and there is an issue with right shifting negative values (which are never transformed to zero when shifted right by any amount). However, both of these are actual whether off_t is 32-bit signed integer or 64-bit signed integer. And file sizes should never be negative in the first place.

I believe the issue is with that off_t is _signed_, so if we are going to split it into low and high parts we should cast it to something unsigned for the bit magic to work. But I don't understand what issue this fixes.

**Comment by hendwolt** [comment]
If off_t is a 32-bit type the maximum file size, that can be handled by this program, is limited to 4GB. 
But 32-bit (Linux) systems are capable of handling much larger files. But this works only, if **all** involved programs and libraries use the switch  "_FILE_OFFSET_BITS=64" to make off_t a 64-bit type.
See https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html for more details.

**Comment by akallabeth** [comment]
@hendwolt Not sure this can be added without side effects. Read the docs and this only works if the system provides 64 bit file support, correct?

**Comment by hendwolt** [comment]
@akallabeth 
This flag _FILE_OFFSET_BITS=64 is necessary on 32-bit Linux systems. They usually provide "Large File Support" for many years. On 64-bit Linux this flag is simply ignored; according to the GNU documentation. 
I am not sure about other platforms and if it works for other compilers like clang.
I'm currently using the patch attached to #3913 to build freerdp for openSUSE Tumbleweed i586 on OBS (only for gcc) and it works for me.

Without the patch: If a program with a 32-bit off_t "hits" a file larger than 4GB, the function, that should fill the structure "fileStat", will not do this, but return an error instead (EOVERFLOW).

**Comment by akallabeth** [comment]
@hendwolt Added the define for linux systems only, hope that fixes this :)

**Comment by akallabeth** [comment]
This fixes #3939 where multiple users already confirm that the issue is fixed with this pull.

**Comment by hardening** [comment]
Everyone agrees, let's merge it.

**Pull request merged**
