### PR TITLE
Fix certificate and private key checks for smartcard logon

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Review by mfleisz — APPROVED** [review]
LGTM

**Review by hardening — APPROVED** [review]
Looks ok even if I don't see what it fixes

**Comment by akallabeth** [comment]
@hardening you set the temporary files to a temporary variable with 2 error aborts and only afterward you set the files to the info structure. so if a write fails the files will not be cleaned up

**Comment by akallabeth** [comment]
@hardening also, current master crashes if you run `/smartcard-logon:cert:<certfile>` without a key (and vice versa)

**Pull request merged**
