### PR TITLE
fix memory leaks

### PR DESCRIPTION
**Pull request by kubistika**

### CODE REVIEW

**Comment by kubistika** [comment]
@akallabeth @hardening regarding the second commit, the library has `key_free` method but it is not exported for use (FREERDP_LOCAL)

**Comment by kubistika** [comment]
@akallabeth this is really important because those leaks made the proxy go out of memory after uptime of some weeks

**Comment by kubistika** [comment]
Those are 2 more leaks that I wasn't sure if they're false positives or real leaks, I'd really appreciate help with those ^^ 

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f92aef06ce6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
    #1 0x7f92ae67bba0 in gdi_CreateSurface /home/plex/git/kubistika/FreeRDP/libfreerdp/gdi/gfx.c:947
    #2 0x557f6e7051e6 in pf_rdpgfx_create_surface /home/plex/git/kubistika/FreeRDP/server/proxy/pf_rdpgfx.c:158
    #3 0x7f92aeb4ba3b in rdpgfx_recv_create_surface_pdu /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:695
    #4 0x7f92aeb55bd0 in rdpgfx_recv_pdu /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:1578
    #5 0x7f92aeb56dcb in rdpgfx_on_data_received /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:1719
    #6 0x7f92aeb9340f in dvcman_receive_channel_data /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:650
    #7 0x7f92aeb956dc in drdynvc_process_data /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1085
    #8 0x7f92aeb95cca in drdynvc_order_recv /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1168
    #9 0x7f92aeb96910 in drdynvc_virtual_channel_client_thread /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1320
    #10 0x7f92ae3e662b in thread_launcher /home/plex/git/kubistika/FreeRDP/winpr/libwinpr/thread/thread.c:327
    #11 0x7f92ae05a668 in start_thread /build/glibc-4WA41p/glibc-2.30/nptl/pthread_create.c:479

Indirect leak of 3145768 byte(s) in 1 object(s) allocated from:
    #0 0x7f92aef06ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x7f92ae417698 in _aligned_offset_malloc /home/plex/git/kubistika/FreeRDP/winpr/libwinpr/crt/alignment.c:104
    #2 0x7f92ae417587 in _aligned_malloc /home/plex/git/kubistika/FreeRDP/winpr/libwinpr/crt/alignment.c:61
    #3 0x7f92ae67c15a in gdi_CreateSurface /home/plex/git/kubistika/FreeRDP/libfreerdp/gdi/gfx.c:984
    #4 0x557f6e7051e6 in pf_rdpgfx_create_surface /home/plex/git/kubistika/FreeRDP/server/proxy/pf_rdpgfx.c:158
    #5 0x7f92aeb4ba3b in rdpgfx_recv_create_surface_pdu /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:695
    #6 0x7f92aeb55bd0 in rdpgfx_recv_pdu /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:1578
    #7 0x7f92aeb56dcb in rdpgfx_on_data_received /home/plex/git/kubistika/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:1719
    #8 0x7f92aeb9340f in dvcman_receive_channel_data /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:650
    #9 0x7f92aeb956dc in drdynvc_process_data /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1085
    #10 0x7f92aeb95cca in drdynvc_order_recv /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1168
    #11 0x7f92aeb96910 in drdynvc_virtual_channel_client_thread /home/plex/git/kubistika/FreeRDP/channels/drdynvc/client/drdynvc_main.c:1320
    #12 0x7f92ae3e662b in thread_launcher /home/plex/git/kubistika/FreeRDP/winpr/libwinpr/thread/thread.c:327
    #13 0x7f92ae05a668 in start_thread /build/glibc-4WA41p/glibc-2.30/nptl/pthread_create.c:479

**Comment by kubistika** [comment]
Nevermind, i found it and I’ll add another commit to fix it in sunday

**Comment by kubistika** [comment]
@akallabeth can you please check why the CI failed? I think the ci agent messed up

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
