### PR TITLE
fix a bunch of warnings

### PR DESCRIPTION
**Pull request by hardening**
This kills almost all warnings here

### CODE REVIEW

**Comment by akallabeth** [comment]
@hardening Did you see #5325? Might be a good idea to merge that one before fixing stuff already handled ;)

**Comment by hardening** [comment]
@akallabeth rebased with your warning PR applied

**Comment by akallabeth** [comment]
@hardening if I see this correct, then the only remaininig changes are `#if 0` ?
Would opt for keeping these warnings or removing the functions all togeher (as they have never been used)

**Comment by hardening** [comment]
@akallabeth well we have some working code that is just not used, but may be used in the future, better keep it IMHO

**Comment by akallabeth** [comment]
@hardening Then I´m leaning toward letting these warnings stand (unused function) as that way the code at least compiles

**Pull request closed without merging**
