### PR TITLE
rdpgfx: Add WITH_DEBUG_RDPGFX cmake option

### PR DESCRIPTION
**Pull request by kubistika**
Those logs spams a lot, so I added a cmake option `WITH_DEBUG_RDPGFX` that decides whether they'll be written or not.

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot would you test this PR please ?

**Comment by kubistika** [comment]
@akallabeth got it, added the logger to the macro 
that means that in the server, that currently does not have a `wlog` instance in its `rdpgfxPrivateContext`, I didn't use the macro, just `#ifdef WITH_DEBUG_RDPGFX`

**Comment by akallabeth** [comment]
@kubistika thx. There is also WLog_Get(TAG) which returns the logger (same as the WLog_DBG macro uses)

**Comment by akallabeth** [comment]
Would also be nice to revert the WLog_ERR calls ;)

**Comment by kubistika** [comment]
@akallabeth done

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
