### PR TITLE
Assist fix

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@lemonmojo ok, you´re lucky I did have a little time.
this should fix the issue and I´ve added your incident example as unit test.

**Comment by lemonmojo** [comment]
@akallabeth Thx! Will give it a spin tomorrow.

**Comment by lemonmojo** [comment]
@akallabeth no nice unfortunately. 😢
Here's what address sanitizer has got to say about it:
Screenshot 2024-01-05 at 10 41 44

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@lemonmojo looks like you did not test the latest changes yet?

**Comment by lemonmojo** [comment]
@akallabeth Yeah, I'll try to give it a shot tomorrow.

**Comment by lemonmojo** [comment]
@akallabeth Still no good 😢
Screenshot 2024-01-09 at 09 56 16

**Comment by akallabeth** [comment]
@lemonmojo ok, now I got it, thx ;)

**Comment by lemonmojo** [comment]
@akallabeth still crashes at the very same line. 😭

**Comment by akallabeth** [comment]
@lemonmojo ok, the reset `_settings->TargetNetPorts = NULL;` after item copy in `freerdp_settings_copy` was missing.
resulted in `freerdp_target_net_adresses_reset` freeing up the source settings instead of the target.

**Comment by lemonmojo** [comment]
@akallabeth No more crash! 🥳

**Pull request merged**
