### PR TITLE
Uncommented code to add subdirectory "Windows" if NOT WIN32

### PR DESCRIPTION
**Pull request by CodeAbyss**
Uncommented code to add subdirectory "Windows" if NOT WIN32

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@CodeAbyss Looks like there are some additional changes necessary to build the deactivated server components.

**Comment by CodeAbyss** [comment]
@akallabeth From the build logs, the build is failing due to " _..\..\..\source\server\Windows\wf_mirage.c(97): error C2065: 'TAG' : undeclared identifier_"

**Comment by akallabeth** [comment]
@CodeAbyss Yes, but this is your pull, so the changes must pass the pull request tester ;) As for the CR/LF stuff, what is the issue exactly?

**Comment by CodeAbyss** [comment]
@akallabeth [https://github.com/FreeRDP/FreeRDP/blob/master/server/Windows/wf_mirage.c](https://github.com/FreeRDP/FreeRDP/blob/master/server/Windows/wf_mirage.c) Just opening this file for edit and checking preview, shows that the entire file has been edited with same code. I tried inserting the macro definintion for _TAG_ but it would show huge diff.

**Comment by akallabeth** [comment]
@CodeAbyss Then better use a editor which handles that better ;) E.g. Notepad++/Notepadqq does not reformat/alter the file on opening.

**Comment by adityasood11** [comment]
Sorry for intervening. But i uncommented add_subdirectory("windows") and i have been dealing with the errors now.  Some of the errors i have rectified by seeing some pull requests and looking at some codes.
I eradicated TAG error by adding TAG macro definition in wf_mirage.c .

**Comment by adityasood11** [comment]
I am left with these errors now.  

image

I looked for related issues and pull requests but did not find any.

**Pull request closed without merging**
