### PR TITLE
Added TAG macro definition

### PR DESCRIPTION
**Pull request by Abhineet-Ayan-Verma**
Fixed TAG undeclared identifier error

### CODE REVIEW

**Comment by Abhineet-Ayan-Verma** [comment]
[wf_mirage.txt](https://github.com/FreeRDP/FreeRDP/files/789369/wf_mirage.txt)

Added TAG macro definition

**Comment by akallabeth** [comment]
@freerdp-bot test
@Abhineet-Ayan-Verma could you please put such changes as in #3792 #3793 #3794 into a single pull in the future? Thank you.

**Comment by Abhineet-Ayan-Verma** [comment]
@akallabeth - Sure. (_I am a newbie in committing and creating pull requests._) You won't get multiple independent similar pull requests from me.

**Comment by akallabeth** [comment]
@Abhineet-Ayan-Verma No problem, everybody has to start somewhere, thank you for your contributions anyway ;)

**Pull request merged**
