### PR TITLE
Added support for OpenH264 1.6

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by hardening** [comment]
As far as I know about OpenH264, it looks good to me

**Comment by HenryJacques** [comment]
@akallabeth : does it still continue to work with 1.5.1?
thanks

**Comment by akallabeth** [comment]
@HenryJacques Yes. Also compiled against every version since 1.3 (did not test connections with these old versions though)

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
