### PR TITLE
Improve length checks in parse_uri_to_local_file

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by pnowack** [comment]
Changes themselves look good to me.

Nit: Would though use the word `Fix`, instead of `Improve`, in the commit message, because it would be in my opinion more precise (since previously we were able to run into out-of-bounds situations, and the word 'improve' itself does not imply in what direction things are 'improved' (or changed)).

**Comment by pnowack** [comment]
> Nit: Would though use the word Fix, instead of Improve, in the commit message, because it would be in my opinion more precise (since previously we were able to run into out-of-bounds situations, and the word 'improve' itself does not imply in what direction things are 'improved' (or changed)).

`Fix out of bounds reads in parse_uri_to_local_file` should be precise enough here.

**Comment by akallabeth** [comment]
@pnowack if you could add a positive review then we can merge ;)

**Review by pnowack — APPROVED** [review]
Thanks!

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
