### PR TITLE
Fix include path in freerdp-client.pc

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot would you be smart enough to test this ?

**Comment by hardening** [comment]
This LGTM, @bmiklautz any opinion ?

**Comment by bmiklautz** [comment]
@hardening the extra / definitely doesn't hurt. 
+1

**Comment by bmiklautz** [comment]
I'll also review the other .pc file and check if similar issues exist.

**Comment by bmiklautz** [comment]
@TingPing thanks for pointing that out.

**Pull request merged**
