### PR TITLE
Add the possibility to redirect specific smartcard readers

### PR DESCRIPTION
**Pull request by HenryJacques**
Until now, /smartcard: had the behaviour to redirect every connected readers. It didn't matter what you used after the parameter /smartcard:xxxx:yyyy.

With this patch you can:
- use /smartcard: "as is" (without argument) to continue to redirect every readers
- use /smartcard:"Reader name" (you have to repeat that for every reader you want to redirect)

The reader name is exactly the one returned by libpcsclite, e.g.

root@host:# opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Xiring Leo V2 (12547854125036) 00 00
1    Yes             Xiring Leo V2 (52412506854712) 01 00

(Thanks to A. Aing for this PR)

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by HenryJacques** [comment]
@bmiklautz so what do you think about this PR?

Thanks!

**Comment by akallabeth** [comment]
@HenryJacques This pull looks nice, but when I try to connect with a specific name, the smartcard channel gets loaded twice. This does not happen when using ```/smartcard``` without argument.

**Comment by HenryJacques** [comment]
@akallabeth will check into that.

**Comment by HenryJacques** [comment]
@akallabeth 

I've just checked what you said.

Until this PR, using /smartcard or /smartcard: (with the colon) didn't make any difference.
With this PR, /smartcard has no effect anymore (that's why you don't see the channel loaded).
If you want to redirect all readers, you'd have to use /smartcard:

Anyway, even without this PR, the behaviour you're describing was already there. The PR didn't introduce that.

Can you check that?

**Comment by akallabeth** [comment]
@HenryJacques Ok, can confirm this behavior. Would suggest to change the commandline handling back to the old one again (the ```:``` is a argument delimiter, so it is bad behavior for ```/smartcard``` and ```/smartcard:``` to behave differently).

**Comment by HenryJacques** [comment]
@akallabeth I've changed the command line handling in my branch.
However since I've forked the FreeRDP master branch, some changes have been made in the same files.
How can I rebase with master (using the github web interface)?
Or should I make a new PR?

Thanks

**Comment by akallabeth** [comment]
@HenryJacques You can rebase your branch locally with ```git fetch --all``` and ```git rebase upstream/master``` assuming you have configured the freerdp repository at ```upstream```. Then you have to force push the branch and you should be set. Using the web interface I don't know if it can be done.

**Comment by HenryJacques** [comment]
@akallabeth thanks for the hint.
However I am not used to the git command line and I'm more used to work directly on the web interface.
Anyway this is what I got:

```
user@host:~/git/FreeRDP# git branch -a
  master
* remotes/origin/smartcard
  smartcard
  remotes/origin/HEAD -> origin/master
  remotes/origin/channels
  remotes/origin/master
  remotes/origin/smartcard
  remotes/origin/stable-1.0
  remotes/origin/stable-1.1
  remotes/origin/tsg
  remotes/origin/winpr
  remotes/origin/winpr_cleanup
  remotes/origin/xrdp-ng
user@host:~/git/FreeRDP# git fetch --all
Fetching origin
user@host:~/git/FreeRDP# git rebase origin/master
warning: refname 'remotes/origin/smartcard' is ambiguous.
Current branch remotes/origin/smartcard is up to date.
```

Not sure what to do :/
Sorry for asking basic questions, I've done some research on Internet but didn't found a satisfactory answer...

Thanks in advance.

**Comment by akallabeth** [comment]
@HenryJacques Ah, well in that case you first have to add freerdp to your remotes ```git remote add upstream https://github.com/freerdp/freerdp``` that adds upstream to your remotes. After that ```git fetch upstream``` and ```git rebase upstream/master```

**Comment by HenryJacques** [comment]
@akallabeth 
almost there, thanks for the tip.

I've been able to rebase (with a conflict that I've been able to resolve)

```
user@host:~/git/FreeRDP# git rebase --continue
client/common/cmdline.c: needs merge
You must edit all merge conflicts and then
mark them as resolved using git add
user@host:~/git/FreeRDP# git add client/common/cmdline.c
user@host:~/git/FreeRDP# git rebase --continue
Applying: keep original behaviour with empty smartcard argument
user@host:~/git/FreeRDP# git push -f
Username:
Password:
Everything up-to-date
```

I suppose I have to do something else now because there is no change on my github repository...
Thank you for your help

**Comment by akallabeth** [comment]
@HenryJacques Sorry for the delay, missed your response. Looks like something did not work. Have a look at the git manual here: ```https://git-scm.com/book/en/v1/Git-Branching-Rebasing```

**Comment by HenryJacques** [comment]
@akallabeth no problem at all. You're not here to teach me git ;)
I'll look into that.

**Comment by HenryJacques** [comment]
@akallabeth hum.... I did something. Was that ok?

**Comment by akallabeth** [comment]
@HenryJacques No, looks like you did a merge...

**Comment by HenryJacques** [comment]
@akallabeth  That's what I was afraid of.... Will do another PR.

**Comment by HenryJacques** [comment]
@akallabeth I did another PR #3126 
I hope this time it is ok ;)

**Pull request closed without merging**
