### PR TITLE
libfreerdp-codec: Make region16_rects() handle NULL nbRects

### PR DESCRIPTION
**Pull request by nathankidd**
Now matches header documentation.  Also cleans up related doc grammar.

### CODE REVIEW

**Comment by akallabeth** [comment]
Looks good, but if you are at it, could you fix the ```assert(region->data)``` too? It is already checked the line below.

**Comment by hardening** [comment]
+1

Yeah the assert must be removed. And the return statement should be return NULL and not 0 (cosmetic).

I'm wondering why I did it this way (having nbrect optionnal) as it makes no sense to do it in two steps when one suffice (I mean calling region16_n_rects(r), then region_rects(r, NULL)).

**Comment by hardening** [comment]
@freerdp-bot it looks good but would you test a compilation of this, please ?

**Comment by nathankidd** [comment]
Good points, I added the assert and NULL changes.

It makes some sense to handle the NULL nbRects case.  Consider an API like:

`MyRectFrob(int nRects, RECTANGLE_16* rects)` 

It needs to extract the number of rects and the rects pointer separately.  Handling NULL means one doesn't need to have extra stack variables to catch the values and can just inline
`MyRectFrob(region16_n_rects(region), region16_rects(region, NULL))`

**Comment by hardening** [comment]
Well stack variables are there for free. And I can't see any real case where you would get the number of rectangles to not use them immediately after that.

**Pull request merged**
