### PR TITLE
WinPR::Clipboard: FIX text/uri-list format bug(#7904)

### PR DESCRIPTION
**Pull request by KangLin**
See:
  GTK: https://docs.gtk.org/glib/struct.Uri.html
  uri syntax: https://www.rfc-editor.org/rfc/rfc3986#section-3
  uri-lists format: https://www.rfc-editor.org/rfc/rfc2483#section-5

### CODE REVIEW

**Review by hardening — APPROVED** [review]
Looks good, but I'm not the expert.
I've only gave a quick look but I've not seen anything about `\r\n` and `\n` in the given specs

**Comment by hardening** [comment]
@freerdp-bot can you test please ?

**Comment by KangLin** [comment]
> Looks good, but I'm not the expert. I've only gave a quick look but I've not seen anything about `\r\n` and `\n` in the given specs

The format of text/uri-list resources is:

    1) Any lines beginning with the '#' character are comment lines
        and are ignored during processing. (Note that URIs may contain
        the '#' character, so it is only a comment character when it is
        the first character on a line.)

    2) The remaining non-comment lines shall be URIs (URNs or URLs),
        encoded according to the URL or URN specifications ([RFC2141](https://www.rfc-editor.org/rfc/rfc2141),
        [RFC1738](https://www.rfc-editor.org/rfc/rfc1738) and [RFC2396](https://www.rfc-editor.org/rfc/rfc2396)). Each URI shall appear on one and only one
        line. Very long URIs are not broken in the text/uri-list format.
        Content-transfer-encodings may be used to enforce line length
        limitations.

    3) As for all text/* formats, lines are terminated with a CRLF pair.

**Comment by KangLin** [comment]
> Refer to this link for build results (access rights to CI server needed): https://ci.freerdp.com//job/PullRequestTester/7891/

https://ci.freerdp.com/job/code-quality-checker/3597/

I don't know what's wrong?

**Comment by mfleisz** [comment]
@KangLin have you run `clang-format`?

**Comment by KangLin** [comment]
> @KangLin have you run `clang-format`?

Please tell how do I. I never used it. I am do it in WINDOWS?

How logon https://ci.freerdp.com//job/PullRequestTester/7891/ ? I am not user name and password.

**Comment by amazingfate** [comment]
> > @KangLin have you run `clang-format`?
> 
> Please tell how do I. I never used it. I am do it in WINDOWS?
> 
> How logon https://ci.freerdp.com//job/PullRequestTester/7891/ ? I am not user name and password.

There is already a file `.clang-format` in the source dir, so just a command `clang-format -style=file -i winpr/libwinpr/clipboard/posix.c` will format your code.

**Comment by KangLin** [comment]
@amazingfate  Thanks

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
