### PR TITLE
Added option to remap scancodes

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by ravenlost** [comment]
Something's not right. Tried compiling this new revision with the same options as my already installed FreeRDP (2.2.0). I based myself on the output of `xfreerdp /buildconfig`. 

Now, my KB is working a lot less. My up/down/left/right arrows no longer work for instance.. 

This is how I run xfreerdp:
```
/opt/freerdp/bin/xfreerdp /u:username /v:192.168.x.x /f /bpp:8 /gfx:avc444 /network:auto -fonts -wallpaper -themes -aero -window-drag -menu-anims
```
Any ideas ? I also tried adding `/kbd:0x00011009` (Canadian Multilingual), but it doesn't seem to change anything.. 

These are my compile options:

```
cmake -Wno-dev -GNinja  \
	-DWITH_ALSA=ON \
	-DWITH_CAIRO=OFF \
	-DWITH_CCACHE=ON \
	-DWITH_CHANNELS=ON \
	-DWITH_CLANG_FORMAT=ON \
	-DWITH_CLIENT_AVAILABLE=1 \
	-DWITH_CLIENT_CHANNELS_AVAILABLE=1 \
	-DWITH_CLIENT_CHANNELS=ON \
	-DWITH_CLIENT_COMMON=ON \
	-DWITH_CLIENT_INTERFACE=OFF \
	-DWITH_CLIENT=ON \
	-DWITH_CUPS=ON \
	-DWITH_DEBUG_ALL=OFF \
	-DWITH_DEBUG_CAPABILITIES=OFF \
	-DWITH_DEBUG_CERTIFICATE=OFF \
	-DWITH_DEBUG_CHANNELS=OFF \
	-DWITH_DEBUG_CLIPRDR=OFF \
	-DWITH_DEBUG_DVC=OFF \
	-DWITH_DEBUG_KBD=OFF \
	-DWITH_DEBUG_LICENSE=OFF \
	-DWITH_DEBUG_MUTEX=OFF \
	-DWITH_DEBUG_NEGO=OFF \
	-DWITH_DEBUG_NLA=OFF \
	-DWITH_DEBUG_NTLM=OFF \
	-DWITH_DEBUG_RAIL=OFF \
	-DWITH_DEBUG_RDPDR=OFF \
	-DWITH_DEBUG_RDPEI=OFF \
	-DWITH_DEBUG_RDPGFX=OFF \
	-DWITH_DEBUG_RDP=OFF \
	-DWITH_DEBUG_REDIR=OFF \
	-DWITH_DEBUG_RFX=OFF \
	-DWITH_DEBUG_RINGBUFFER=OFF \
	-DWITH_DEBUG_SCARD=OFF \
	-DWITH_DEBUG_SND=OFF \
	-DWITH_DEBUG_SVC=OFF \
	-DWITH_DEBUG_SYMBOLS=OFF \
	-DWITH_DEBUG_THREADS=OFF \
	-DWITH_DEBUG_TIMEZONE=OFF \
	-DWITH_DEBUG_TRANSPORT=OFF \
	-DWITH_DEBUG_TSG=OFF \
	-DWITH_DEBUG_TSMF_AVAILABLE=0 \
	-DWITH_DEBUG_TSMF=OFF \
	-DWITH_DEBUG_TSMF=OFF \
	-DWITH_DEBUG_URBDRC=OFF \
	-DWITH_DEBUG_WND=OFF \
	-DWITH_DEBUG_X11_CLIPRDR=OFF \
	-DWITH_DEBUG_X11_LOCAL_MOVESIZE=OFF \
	-DWITH_DEBUG_X11=OFF \
	-DWITH_DEBUG_XV=OFF \
	-DWITH_DSP_EXPERIMENTAL=OFF \
	-DWITH_DSP_FFMPEG=ON \
	-DWITH_EVENTFD_READ_WRITE=1 \
	-DWITH_FAAC=OFF \
	-DWITH_FAAD2=OFF \
	-DWITH_FFMPEG=TRUE \
	-DWITH_FFMPEG=TRUE \
	-DWITH_GFX_H264=ON \
	-DWITH_GPROF=OFF \
	-DWITH_GSM=OFF \
	-DWITH_GSSAPI=OFF \
	-DWITH_ICU=OFF \
	-DWITH_IPP=OFF \
	-DWITH_JPEG=ON \
	-DWITH_LAME=OFF \
	-DWITH_LIBRARY_VERSIONING=ON \
	-DWITH_LIBSYSTEMD=ON \
	-DWITH_MACAUDIO_AVAILABLE=0 \
	-DWITH_MACAUDIO=OFF \
	-DWITH_MACAUDIO=OFF \
	-DWITH_MANPAGES=ON \
	-DWITH_MBEDTLS=OFF \
	-DWITH_OPENCL=OFF \
	-DWITH_OPENH264=OFF \
	-DWITH_OPENSLES=OFF \
	-DWITH_OPENSSL=ON \
	-DWITH_OSS=ON \
	-DWITH_PAM=ON \
	-DWITH_PCSC=ON \
	-DWITH_PROFILER=OFF \
	-DWITH_PROXY_MODULES=OFF \
	-DWITH_PROXY=ON \
	-DWITH_PULSE=ON \
	-DWITH_SAMPLE=OFF \
	-DWITH_SANITIZE_ADDRESS_AVAILABLE=1 \
	-DWITH_SANITIZE_ADDRESS=OFF \
	-DWITH_SANITIZE_MEMORY_AVAILABLE=1 \
	-DWITH_SANITIZE_MEMORY=OFF \
	-DWITH_SANITIZE_THREAD_AVAILABLE=1 \
	-DWITH_SANITIZE_THREAD=OFF \
	-DWITH_SERVER_CHANNELS=ON \
	-DWITH_SERVER_INTERFACE=ON \
	-DWITH_SERVER=ON \
	-DWITH_SHADOW=ON \
	-DWITH_SMARTCARD_INSPECT=OFF \
	-DWITH_SOXR=OFF \
	-DWITH_SSE2=ON \
	-DWITH_SWSCALE=ON \
	-DWITH_THIRD_PARTY=OFF \
	-DWITH_VAAPI=ON \
	-DWITH_VALGRIND_MEMCHECK_AVAILABLE=1 \
	-DWITH_VALGRIND_MEMCHECK=OFF \
	-DWITH_WAYLAND=ON \
	-DWITH_WINPR_TOOLS=ON \
	-DWITH_X11=ON \
	-DWITH_X264=OFF \
	-DWITH_XCURSOR=ON \
	-DWITH_XDAMAGE=ON \
	-DWITH_XEXT=ON \
	-DWITH_XFIXES=ON \
	-DWITH_XINERAMA=ON \
	-DWITH_XI=ON \
	-DWITH_XKBFILE=ON \
	-DWITH_XRANDR=ON \
	-DWITH_XRENDER=ON \
	-DWITH_XSHM=ON \
	-DWITH_XTEST=ON \
	-DWITH_XV=ON \
	-DWITH_ZLIB=ON \
	-DCMAKE_INSTALL_PREFIX=/opt/freerdp .
```

The output of this new FreeRDP buildconfig:
```
[raven@Papounix Downloads]$ /opt/freerdp/bin/xfreerdp /buildconfig 
This is FreeRDP version 3.0.0-dev (4743e489e)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.0
Target architecture: x64
```

**Comment by akallabeth** [comment]
yes, you overdo the compilation option thing. check e.g. `packaging/deb/freerdp-nightly/rules` for sane options

**Comment by ravenlost** [comment]
> yes, you overdo the compilation option thing. check e.g. `packaging/deb/freerdp-nightly/rules` for sane options

I just tried compiling the the same as in that rules files. Precisely :

```
cmake -Wno-dev -GNinja  \
	-DCMAKE_SKIP_RPATH=FALSE \
	-DCMAKE_SKIP_INSTALL_RPATH=FALSE \
	-DWITH_PULSE=ON \
	-DWITH_CHANNELS=ON \
	-DBUILTIN_CHANNELS=ON \
	-DWITH_CUPS=ON \
	-DWITH_PCSC=ON \
	-DWITH_GSTREAMER_0_10=ON \
	-DWITH_FFMPEG=ON \
	-DWITH_DSP_FFMPEG=ON \
	-DCHANNEL_URBDRC=ON \
	-DCHANNEL_URBDRC_CLIENT=ON \
	-DWITH_SERVER=ON \
	-DWITH_CAIRO=ON \
	-DBUILD_TESTING=OFF \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DCMAKE_INSTALL_PREFIX=/opt/freerdp/ \
	-DCMAKE_INSTALL_INCLUDEDIR=include \
	-DCMAKE_INSTALL_LIBDIR=lib .
```

And I've got the same behaviour... My "windows" key doesn't work also, and I noticed that my "down" arrow will actually move my cursor UP. 

Strange... what am I missing here?

**Comment by ravenlost** [comment]
I've also tried compiling it with the basic settings mentionned in [https://github.com/FreeRDP/FreeRDP/wiki/Compilation](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) :

`cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DCMAKE_INSTALL_PREFIX=/opt/freerdp .`

Same issue... :(

**Comment by akallabeth** [comment]
@ravenlost sorry, had a little bug in there. Updated the pull request, so now you can use it.
`cmake -GNinja -DWITH_DEBUG_KBD=ON .` might be a good idea to allow dumping keyboard scancodes with `/log-filters:com.freerdp.locale:trace`

**Comment by ravenlost** [comment]
> @ravenlost sorry, had a little bug in there. Updated the pull request, so now you can use it.
> `cmake -GNinja -DWITH_DEBUG_KBD=ON .` might be a good idea to allow dumping keyboard scancodes with `/log-filters:com.freerdp.locale:trace`

Awesome. I managed to compile it (just tried with recommended initial configs and added `-DWITH_DEBUG_KBD=ON`) and now my keyboard seems to behave normally. Thanks for this. Now, I've yet to figure out the scancodes...  I'd need to add something like `/kbd-remap:0xd6=0xa9,etc.` if I understand correctly ? Thanks a million!!

**Comment by ravenlost** [comment]
> > @ravenlost sorry, had a little bug in there. Updated the pull request, so now you can use it.

Also, from reading your code with a friend, it seems I should have an output of "remapped scandode..." when I run xfreerdp with debug... Although I see all [DEBUG] outputs, I don't see that at all. As if "remapped = 0" ?

image

Shouldn't see 2 "remapped .." outputs ? My last try was with `/kbd-remap:31=56,5E=29`

**Comment by akallabeth** [comment]
sorry for the confusion, the input parsing expects hex syntax `0x29` or it will interpret the value decimal based.

**Review by ravenlost — APPROVED** [review]
This is working great. I've had no issues so far. Using an **Apple** Canadian Multilingual Standard Layout:
image

Using this to connect to various Windows Desktop and Server RDP sessions. It's working flawlessly!!!
Remmaped my slash and ugrave keys to swap them (damn Apple KB don't use the same scancodes!) and also my Print screen (F13) key: 
`/kbd-remap:0x56=0x29,0x29=0x56,0x64=0x54`

**Comment by hardening** [comment]
Just an eagle eye remark: the PR is interesting and seem to do the job, but anyway I feel like there's a limited and fixed number of cases to treat. I mean, the root cause of the bug is probably a misdetection of @ravenlost  's keyboard layout, not that we need the possibility to remap any key...

**Comment by akallabeth** [comment]
@hardening that is true, that should be fixed, but that also assumes that all keyboards have such a (public) mapping and there are no custom ones (remapped keys, some differences between windows and linux mapping that are desired, ...) so that this option may actually be useful for those.

**Comment by ravenlost** [comment]
> @hardening that is true, that should be fixed, but that also assumes that all keyboards have such a (public) mapping and there are no custom ones (remapped keys, some differences between windows and linux mapping that are desired, ...) so that this option may actually be useful for those.

I think the problem (probably?) relies with the fact that a **PC** Canadian Multilingual KB doesn't send the same scancodes as an **APPLE** Canadian Multilingual KB. Windows probably as a driver or something that recognizes my KB to be an Apple KB, thus changes itself the mappings. In Linux, however, it gives you what it receives. So, in Linux, I also had the problem of swapped slash and ugrave, and my PrintScreen (F13) not working! In order to fix it in Linux, I also had to force a remap! See: [https://wiki.archlinux.org/index.php/Apple_Keyboard](https://wiki.archlinux.org/index.php/Apple_Keyboard) _("If you use a Canadian multilingual layout...")_

So, I truly believe this new functionality is a MUST to be merged in master! The power of Linux, to me at least, is that it allows unlimited possibilities and flexibility with any hardware! We have a fix which I don't think involves much and gives that flexibility. 

Hoping to see this get merged into master sooner than later ;)

Thanks again for this great work!

**Comment by ravenlost** [comment]
Just wondering, is this going to get pulled into the main FreeRDP branch afterall ? It needs 1 approving review (which I've done, but don't think I count as a reviewer :p). Cheers! Pat

**Review by mfleisz — APPROVED** [review]
LGTM

**Pull request merged**
