### PR TITLE
Change version suffix separator from '-' to '~'.

### PR DESCRIPTION
**Pull request by nastasi**
Changing the suffix separator from '-' to '~' you will obtain a correct versions comparison.
Currently '2.0.0-dev' > '2.0.0'.
With the '~' suffix separator you obtains '2.0.0~dev' < '2.0.0'.
Tested on debian, ubuntu and freebsd.
On debian/ubuntu: **dpkg --compare-versions _&lt;ver1>_  _&lt;operator>_ _&lt;ver2>_**
Example:
```bash
$ dpkg --compare-versions 2.0.0-dev '>' 2.0.0
$ echo $?
0
$ dpkg --compare-versions 2.0.0~dev '>' 2.0.0
$ echo $?
1
```

### CODE REVIEW

**Comment by hardening** [comment]
Is it me or it looks like a hack ? I guess applications that need it can parse a version number, can't they ?

**Comment by nastasi** [comment]
@hardening `~` seems to be the common way to add a suffix to a version and have the suffixed version **less then** the not-suffixed. If I'm packaging your packaging (like it is) and you are releasing a not-suffixed version and I packaged it my system will not update it.

**Comment by antenore** [comment]
@hardening I confirm the same behavior on FreeBSD and Fedora, and moving to ~ it won't change your life I think ;-) , on the contrary in the packaging world the - as suffix is a disaster, except if you really mean that 2.0.0-dev is less updated than 2.0.0

```
2.0.0-dev < 2.0.0 < 2.0.0~dev
```
My 2¢

**Comment by antenore** [comment]
> 2.0.0-dev < 2.0.0 < 2.0.0~dev

well... the other way around, sorry

2.0.0-dev > 2.0.0 > 2.0.0~dev

**Comment by hardening** [comment]
Ok, sorry I read too fast the first statement. That's just a matter of packaging names, so I guess that if @bmiklautz is ok we (he) should merge that.

**Comment by hardening** [comment]
BTW @freerdp-bot  can you test that too ?

**Comment by nastasi** [comment]
freerdp-bot is lazy ...

**Comment by nastasi** [comment]
Hi all, RedHat/Fedora people told me that '~' in the release name is a problem, I retire the PR, sorry for the waste of time.

**Comment by bmiklautz** [comment]
@nastasi the -dev doesn't have anything todo with the packaging itself. It is rather a "hint" for users and developers. When packaging you can set the package name/version to whatever you want.

**Pull request closed without merging**
