### PR TITLE
Added WINPR_ASSERT

### PR DESCRIPTION
**Pull request by akallabeth**
Added a WinPR macro that can be used for WinPR and FreeRDP to
replace standard C assert.
It is more verbose and logs issues to WLog which makes it easier
for us to trace problems in the field.
@hardening what do you think about this?

### CODE REVIEW

**Comment by hardening** [comment]
Adding a cmake option to expand WINPR_ASSERT to void would make it fantastic

**Comment by akallabeth** [comment]
@hardening can do that, but I´d keep the log entry

**Comment by akallabeth** [comment]
@hardening merging as is, we can improve what we find lacking with another pr.

**Comment by akallabeth** [comment]
@hardening merged as is, we can improve the implementation with another pr if we find it lacking somewhere.

**Pull request merged**
