### PR TITLE
Fixed GDI_BITMAP, now using custom deallocation function.

### PR DESCRIPTION
**Pull request by akallabeth**
gdi_surface_bits: Now properly discarding old bitmap before creating a new one.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@akallabeth the CreateBitmap was rather modeled after https://msdn.microsoft.com/en-us/library/windows/desktop/dd183485(v=vs.85).aspx that's why there isn't a custom function.
When changing the function we basically getting less compatible to the drawing functions on Windows.

**Comment by bmiklautz** [comment]
@akallabeth what was the initial problem that this change is necessary? - All graphic related memory should be allocated aligned anyways.

**Comment by akallabeth** [comment]
@bmiklautz Yes, but that way it is not possible to use an existing bitmap as destination buffer for GDI

**Comment by akallabeth** [comment]
@hardening @awakecoding @bmiklautz Any objections / suggestions on this one?

**Comment by hardening** [comment]
I'm not a GDI specialist, but it looks good to me, +1.

**Comment by bmiklautz** [comment]
+1. Nice idea. Get's much more flexible.

**Pull request merged**
