### PR TITLE
Mac Fullscreen + window title

### PR DESCRIPTION
**Pull request by nschneider**
* Set Mac window title according to command line
* Handle fullscreen command line switch

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@nschneider for testing. Just run the mac client with /f for full screen and for window title just check if the title is set?

**Comment by hardening** [comment]
any news on this PR, if it works perhaps we could merge it ?

**Comment by akallabeth** [comment]
Just tested, code is working.
Will reformat the patch and merge. (TAB / Space mixups)

**Pull request closed without merging**
