### PR TITLE
Correct typos and formatting errors in format strings

### PR DESCRIPTION
**Pull request by ehdgks0627**
In several files, fixed typos in format strings that were causing unexpected output and formatting issues.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Review by akallabeth — APPROVED** [review]
LGTM, nice fixes, really appreciated

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by ehdgks0627** [comment]
Revert unnecessary whitespace changes

**Comment by akallabeth** [comment]
@ehdgks0627 looks like the changes need another `git clang-format`

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Pull request merged**
