### PR TITLE
h264: set the encoder MaxBitrate field.

### PR DESCRIPTION
**Pull request by llyzs**

### CODE REVIEW

**Comment by llyzs** [comment]
Don't merge - some additional changes required.

**Comment by MartinHaimberger** [comment]
@llyzs I dont know if this change is a good idea. after some research this bitrate is used for frame skipping (if encoded frame exeeds this rate, the frame will get dropped) UNSPECIFIED_BIT_RATE disables this behavior.

**Comment by llyzs** [comment]
@MartinHaimberger 

There is another field bEnableFrameSkip set to 0, does that work?

**Comment by MartinHaimberger** [comment]
@llyzs  We use bEnableFrameSkip with 0 and UNSPECIFIED_BIT_RATE, with this settings we got what we wanted ....

**Comment by llyzs** [comment]
@MartinHaimberger 

I think I will just expose a new field instead of setting it to the same as BitRate so that we can tune it outside of the freerdp core.

**Pull request closed without merging**
