### PR TITLE
Added /kbd-scancode-list

### PR DESCRIPTION
**Pull request by akallabeth**
Prints a listing of hexadecimal scancodes and the mapping to VK_*

### CODE REVIEW

**Comment by antenore** [comment]
Lovely!

It works perfectly @akallabeth

**Comment by ipatch** [comment]
hello 👋,

i started the following discussion yesterday, 

https://github.com/FreeRDP/FreeRDP/discussions/8823#discussioncomment-5397077

and from searching through this repo to hopefully get a working solution for my question i came across this PR. i also read up the kbd documentation in the wiki, and noticed there were no cli examples for remapping a key, nor did i see any examples running the below command

```
xfreerdp /help
```

also when running the above command in the _help_ output, i see no mention of this flag. i installed xfreerdp, freerdp via my distro's package manager. distro being arch linux with the following output,

```
yay -Ss freerdp
```
```
community/freerdp 2:2.10.0-2 (1.6 MiB 6.1 MiB) (Installed)
    Free implementation of the Remote Desktop Protocol (RDP)
```

and when i run `xfreerdp /kbd-scancode-list` i get the below output

```
[11:11:58:953] [2300692:2300692] [WARN][com.freerdp.client.common.cmdline] - ----------------------------------------
[11:11:58:959] [2300692:2300692] [WARN][com.freerdp.client.common.cmdline] - Using deprecated command-line interface!
[11:11:58:959] [2300692:2300692] [WARN][com.freerdp.client.common.cmdline] - This will be removed with FreeRDP 3!
[11:11:58:959] [2300692:2300692] [WARN][com.freerdp.client.common.cmdline] - ----------------------------------------
[11:11:58:959] [2300692:2300692] [WARN][com.freerdp.client.common.compatibility] - /kbd-scancode-list -> /v:/kbd-scancode-list
[11:11:58:959] [2300692:2300692] [WARN][com.freerdp.client.common.compatibility] -
[11:11:58:960] [2300692:2300694] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: capin
[11:11:58:316] [2300692:2300694] [ERROR][com.freerdp.core] - connect
[11:11:58:316] [2300692:2300694] [ERROR][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_FAILED [0x00020006]
```

i'll attempt to try and build from source to see if it makes a difference, and check if this is possibly an issue with the arch linux packaging of _freerdp_ but i think i'll leave a comment on this issue for posterity.

looking forward to hopefully being able to add a custom key mapping for my setup. 🤞

**Comment by akallabeth** [comment]
@ipatch this is only for builds from `master` , not backported to stable releases yet

**Comment by ipatch** [comment]
> @ipatch this is only for builds from `master` , not backported to stable releases yet

thank you. 🙏

**Pull request merged**
