### PR TITLE
winpr: KB3148851: Updates to Russian Time Zones for 2016

### PR DESCRIPTION
**Pull request by rjcorrig**
Patches Windows Time Zone database to the April 2016 update provided by KB3148851.
Details: https://support.microsoft.com/en-us/kb/3148851

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot it looks good (AFAICT) but could you test it, thank you.

**Comment by bmiklautz** [comment]
@rjcorrig did you modify timezone.c directly or re-created it scripts/TimeZones.cs?

**Comment by rjcorrig** [comment]
@bmiklautz  I recreated it from TimeZones.cs on my Windows 7 workstation after applying the KB3148851 patch, then copy/pasted the generated tables into timezone.c .

**Comment by bmiklautz** [comment]
@rjcorrig awesome! Thank you.
+1

**Pull request merged**
