### PR TITLE
Pause playback on queue empty, free buffers on close.

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes an issue on mac os that audio stops playing after closing the first time. (open browser, play something, close, reopen -> no more sound)

### CODE REVIEW

**Comment by mgibson2** [comment]
@mfleisz 
@akallabeth 
Can you both please take care to get this into tcvier ASAP and make a new dmg for testing.
But please first test that this fix does not brake anything on Linux and Windows

**Comment by hardening** [comment]
@mgibson2 the changes are in some mac specific code, so no need to worry.

**Comment by akallabeth** [comment]
@mgibson2 The changes are in files only compiled when the target is iOS or MacOS, so no chance it breaks something on other platforms.

**Comment by mgibson2** [comment]
@akallabeth 
OK, thx

**Pull request merged**
