### PR TITLE
transport: fixed multiple errors in async thread

### PR DESCRIPTION
**Pull request by nfedera**
Should fix issue #2610 and issue #2609

### CODE REVIEW

**Comment by bmiklautz** [comment]
+1.
The part with WAIT_TIMEOUT is quite interesting maybe we can reproduce this somehow.

**Comment by hardening** [comment]
like @bmiklautz,  +1 but the WAIT_TIMEOUT part looks suspicious (sounds like SSL_ERROR_SYSCALL ;) )

**Comment by nfedera** [comment]
It seems to be related to poll(). If I comment ```#define HAVE_POLL_H``` the issue is not present.
BTW: I'm seeing this on Mac OS X 10.9.5 ... still have to check if this also happens on Linux.
For reference it is this poll - https://github.com/FreeRDP/FreeRDP/blob/e3236c2317abf88bb8634f493164367d4708cec9/winpr/libwinpr/synch/wait.c#L154 - which returns 0 although timeout is -1;

**Comment by nfedera** [comment]
Adding my debug output for reference:
```
[09:43:07:288] [24810:09d4d000] [ERROR][com.winpr.sync.wait] - calling poll with timeout = -1
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - poll returned 0, dumping pollfds ...
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[0].fd = 11
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[0].events = 0x0001 (POLLIN)
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[0].revents = 0
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[1].fd = 13
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[1].events = 0x0001 (POLLIN)
[09:43:07:288] [24810:09c47000] [ERROR][com.winpr.sync.wait] - pollfds[1].revents = 0
```

**Comment by nfedera** [comment]
Weird. I don't see the poll issue on Linux and neither on my iMac which is also still on OS X 10.9.5 like my MacBook where I've seen the issue first.
Will do some further investigation and update this PR to not accept WAIT_TIMEOUT ...

**Comment by nfedera** [comment]
Ok it seems the MacPorts installation is the culprit. otool -L revealed that some libraries (e.g. ssl) get loaded from /opt/local. Maybe the poll symbol gets overridden somewhere which might be quite possible if you look at he history of [broken poll issues on OS X](https://www.google.com/search?q=broken+poll+OS+X).
In addition this line https://github.com/FreeRDP/FreeRDP/blob/f219d341f1f88159cf67578390390a554a4b4083/CMakeLists.txt#L360  causes the issue that the openssl includes are taken from /opt/local/include but freerdp gets linked to the system libraries which might result in build or runtime failures of course. Not sure how to handle that ... @bmiklautz any ideas ?

However, IMHO the correct way is to fail when WaitForMultipleObjects returns WAIT_TIMEOUT if an infinite timeout was specified - contrary to what I've done in this PR.

**Comment by nfedera** [comment]
Update: There are link and runtime issues with MacPorts installed caused by CMakeList.txt addition of /opt/local/include to the head of the include path passed to the compiler.
However, the issue above with WaitForMultipleObjects is a faulty handling of the async transport in mfreerdp. Both, the async transport thread and the mfreerdp client thread check/treat the freerdp transport+channel handles. Of course mfreerdp should only do this if async transport is not enabled.
I'll fix this in an additional PR soon ...

**Pull request merged**
