### PR TITLE
Added wayland discrete axis events for mouse wheel

### PR DESCRIPTION
**Pull request by akallabeth**
the discrete axis event gives changes in steps just like the
xfreerdp version uses. This way scrolling can be implemented
consistent with the behaviour of xfreerdp

### CODE REVIEW

**Review by hardening — APPROVED** [review]
LGTM

**Comment by 0140454** [comment]
When only using discrete value, the problem I encountered is scrolling will not work if I decrease `Scrolling speed` in KDE system settings.

With level 5, discrete value is 1.
Screenshot_20210128_090537

However, discrete event will not be emitted if level is 4.
Screenshot_20210128_090647

**Comment by akallabeth** [comment]
@0140454 which values do you get with the axis event in these cases? this might actually also be an issue with kde (did they already finish their wayland support?)

**Comment by 0140454** [comment]
@akallabeth 

| Level | Axis | Discrete |
| :-----: | :----: | :---------: |
| 1 | 384 | No event |
| 2 | 1152 | No event |
| 3 | 1920 | No event |
| 4 | 2880 | No event |
| 5 | 3840 | 1 |
| 6 | 5760 | 1 |
| 7 | 7680 | 2 |
| 8 | 11520 | 3 |
| 9 | 15360 | 4 |
| 10 | 19200 | 5 |
| 11 | 26880 | 7 |
| 12 | 34560 | 9 |
| 13 | 46080 | 12 |
| 14 | 57600 | 15 |
| 15 | 76800 | 20 |

According to [news](https://www.omgubuntu.co.uk/2021/01/kde-plans-for-2021-wayland-fingerprint) about KDE Wayland support, I think they are still working on it.

**Pull request merged**
