### PR TITLE
Cmake multiconfig

### PR DESCRIPTION
**Pull request by akallabeth**
Refactor `CMake`:
* Support multiconfiguration builds (`Ninja Multi-Config`, visual studio, ...)
* Support per configuration `configure_file`

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@hardening @mfleisz ok, rebased this one.
please have a look, will merge next week.

**Review by hardening — APPROVED** [review]
Seems ok

**Pull request merged**
