### PR TITLE
Fixed TAG macro definition

### PR DESCRIPTION
**Pull request by Abhineet-Ayan-Verma**
+ TAG definition

### CODE REVIEW

**Comment by bmiklautz** [comment]
@Abhineet-Ayan-Verma thanks for you contribution would you give more details on what this pull request does.

**Comment by Abhineet-Ayan-Verma** [comment]
@bmiklautz  - I was building the project on VS 2012 and the file showed error "error C2605: 'TAG' : undeclared identifier". So, I added the "TAG" macro definition.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by Abhineet-Ayan-Verma** [comment]
@akallabeth : I don't know from where the code is getting reformatted. Even when I am just hitting the "Edit" and "Preview Changes", (without making any changes), the preview shows the whole code reformatted. So, closed the pull request.

**Comment by akallabeth** [comment]
do the change in a simple text editor, many ide have code reformatting enabled.

**Comment by Abhineet-Ayan-Verma** [comment]
[wf_mirage.txt](https://github.com/FreeRDP/FreeRDP/files/789389/wf_mirage.txt)

Added TAG macro definition

**Comment by Abhineet-Ayan-Verma** [comment]
@akallabeth - Added the text file with the fix. I have copied the RAW copy of this file, pasted it to Notepad, edited to add TAG def, saved as the .txt file and uploaded here. I don't know, whether the reformatting issue is resolved or not.

**Pull request closed without merging**
