### PR TITLE
remove horizontal scroll maping to forward/back

### PR DESCRIPTION
**Pull request by bsagal**
partal fix for #2302

### CODE REVIEW

**Comment by akallabeth** [comment]
@bsagal Sorry for the late response, missed that thread ;)
As for mouse wheel mapping, have a look at MS-RDPBCGR 2.2.8.1.1.3.1.1.3 Mouse Event (TS_POINTER_EVENT) for possible event mappings.

**Comment by hardening** [comment]
I feel like this patch could fix things for libinput based system but would break others. @bsagal can you confirm this ?

**Comment by bsagal** [comment]
I have not tested, but don't think it is libinput specify.

I have found various examples with evdev that map left/right scroll to 6/7

Also look at on the comments in the existing `client/X11/xf_event.c`
```
		case 6:		/* wheel left or back */
 		case 8:		/* back */
 
		case 7:		/* wheel right or forward */
 		case 9:		/* forward */
```

6/7 are wheel left/right and 8/9 are forward/back.

**Comment by akallabeth** [comment]
@bsagal You could map the wheel left / right stuff to ```PTRFLAGS_HWHEEL``` events (aka horizontal wheel)
except for that remark, LGTM +1

**Comment by bsagal** [comment]
@akallabeth I think that is the correct solution but not entirely sure how to do it. 

What is the flags 0x0078 and 0x0088 (in cases 4/5)

**Comment by akallabeth** [comment]
@bsagal As far as I can tell they are the number of rotation units for the scroll wheel (have a look at the spec I posted earlier, there is also the definition for ```PTRFLAGS_HWHEEL```, etc)

**Comment by bsagal** [comment]
@abergmeier I have looked at the spec and tried to define ```PTRFLAGS_HWHEEL``` but crashed the client when sending to the server, not had a chance to look more into it. Also i have no idea how to check the Input Capability Set.

**Comment by akallabeth** [comment]
@bsagal I've created a branch based on your pull with these fixes here: https://github.com/akallabeth/freerdp/tree/mouse_scroll
I have no mouse with a horizontal wheel / buttons, so could you check if it works for you?

**Comment by bsagal** [comment]
@abergmeier Tried the branch but discovered i cannot test it as server 2008R2 does not support ```TS_INPUT_FLAG_MOUSE_HWHEEL```.

looking at the code i was wondering why the test in ```libfreerdp/core/capabilities.c``` for
```TS_INPUT_FLAG_MOUSE_HWHEEL``` is in an ```if else``` with ```INPUT_FLAG_FASTPATH_INPUT``` should the test not be in a separate ```if```

**Comment by bsagal** [comment]
Found a server with 2012 to connect to and fixed the horizontal wheel support, this pull will now provide working horizontal.

**Comment by akallabeth** [comment]
LGTM +1

**Pull request merged**
