### PR TITLE
Shadow big endian

### PR DESCRIPTION
**Pull request by akallabeth**
@ondrejholy this should address #9925 but no way to properly test.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by ondrejholy** [comment]
Thanks for looking into it. I've just made a quick test and see just a black screen now, so this is obviously not correct...

**Comment by akallabeth** [comment]
@ondrejholy ok, did have a bug in there, should be fixed now. (new function now  did work on same color)

**Comment by ondrejholy** [comment]
It works fine now, except for cursor colors. The `shadow_subsystem_pointer_convert_alpha_pointer_data` function also needs to take the `subsystem->format` into account. I've just tested that reverse ordering of the https://github.com/FreeRDP/FreeRDP/blob/3.3.0/server/shadow/shadow_subsystem.c#L240-L243 lines fix cursor colors on big-endian...

**Comment by akallabeth** [comment]
@ondrejholy ok, did push a fix for the cursor color conversion function too

**Pull request merged**
