### PR TITLE
winpr: skip TestBacktrace when there is no viable backtrace implement…

### PR DESCRIPTION
**Pull request by floppym**
Fixes: https://github.com/FreeRDP/FreeRDP/issues/7773

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@floppym does `MUSL` provide some kind of stack trace API or none at all?
If it does not provide any, it may be the better option to implement the API and return success (although empty stack trace) so that  it will not fail during runtime. (guarded with a `MUSL` specific define if possible)

The intention of the test was to fail, if new platforms are added and the existing implementation does not support it. Default is to return error codes from the API (which is the case here)
If we are comfortable with the API not returning meaningful data, we can just add an `empty` implementation

**Comment by floppym** [comment]
> @floppym does `MUSL` provide some kind of stack trace API or none at all?

As far as I can tell, it does not provide any such API. There are third party libraries that could fill in, but I'm not sure this is worth adding additional dependencies.

**Comment by floppym** [comment]
> (guarded with a MUSL specific define if possible)

musl actually makes it difficult to detect itself via macros.

https://wiki.musl-libc.org/faq.html

**Comment by akallabeth** [comment]
@floppym well, then it might be a good idea to instead add a build option `I_DONT_WANT_BACKTRACE_SUPPORT_AND_WILL_NOT_COMPLAIN` (slightly exaggerated name, please feel free to use something less verbose ;)) which does the same as a `MUSL` specific check (e.g. provide a `empty` backtrace implementation).
I just feel it is not right to take the edge off the test by default, just because something we assume is there is missing.
Having to use some additional build option to disable it seems like the more sensible approach, as there will always be new backends (or however you call the new implementation of dependencies)

**Comment by akallabeth** [comment]
as for other backtrace `API` support, feel free to add any you like, nice to have a choice

**Comment by floppym** [comment]
Yeah, adding a build option seems reasonable.

**Comment by floppym** [comment]
As for adding an empty backtrace implementation: that pointless to me. The existing behavior is to simply return `NULL` from `winpr_backtrace`, and that seems like the most appropriate thing to do when we can't produce something useful.

**Pull request closed without merging**
