### PR TITLE
Some fixes for endian issues

### PR DESCRIPTION
**Pull request by joantolo**
Testing the FreeRDP server of gnome-remote-desktop on a s390x system I found some issues.

I still have to fix one issue about NTLM authentication not recognizing user/password on this architecture.
And another issue parsing the redirection fields.

### CODE REVIEW

**Comment by joantolo** [comment]
Could this be backported to stable-2 ?

**Comment by akallabeth** [comment]
@freerdp-bot test properly!

**Comment by akallabeth** [comment]
@joantolo should be possible, no api changes.
can you create a pr against `stable-2.0` with these commits `git cherry-pick -x`?

**Review by hardening — APPROVED** [review]
Looks ok, thanks for the contribution

**Pull request merged**
