### PR TITLE
[WIP] 2.1.2 fixes

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by joakim-tjernlund** [comment]
Could you merge to stable as you go? Merging and releasing in one go does not get any testing before release.

**Comment by akallabeth** [comment]
@joakim-tjernlund stable only receives cherry-picks from master, so feedback for master is the way to go ;)

**Comment by joakim-tjernlund** [comment]
> @joakim-tjernlund stable only receives cherry-picks from master, so feedback for master is the way to go ;)

master is not ABI compatible and new features I don't need. I do use stable , to test and possible get a bug fix I need ASAP.
The current method makes stable virtually untested before release, how do you know it is any good?
This bug could have been detected if you had pushed as you go.

**Comment by akallabeth** [comment]
@joakim-tjernlund this change is in there for at least a year now and this was the first feedback regarding that.
As for ABI compatible, ok, so you don´t want to test, that is fine.

**Comment by akallabeth** [comment]
Further investigation exposed the changes are not required.

**Pull request closed without merging**
