### PR TITLE
Replace deprecated ffmpeg functions:

### PR DESCRIPTION
**Pull request by jpulz**
avpicture_get_size -> av_image_get_buffer_size
  avpicture_fill -> av_image_fill_arrays
  av_picture_copy -> av_image_copy

Add missing includes.

This fixes build with ffmpeg-6.x.x

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@jpulz thank you for the pull request, just note that this channel is unmaintained and disabled by default.

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Comment by akallabeth** [comment]
@freerdp-bot test again

**Comment by VVD** [comment]
Can this pool be merged with the stable-2.0?

**Comment by jospezial** [comment]
> Can this pool be merged with the stable-2.0?

A lot of deprecated stuff has now been removed from ffmpeg git. https://bugs.gentoo.org/926787
Please backport this to stable-2.0!
krdc 24.02 depends on that branch.

**Comment by eegorov** [comment]
@jospezial 
I try backport this to stable-2.0
https://github.com/eegorov/FreeRDP/tree/stable-2.0

net-misc/freerdp-2.9999 build fine on my gentoo

**Pull request merged**
