### PR TITLE
Fix DPI issue when parent-window specified

### PR DESCRIPTION
**Pull request by StefanKoell**
2nd try (git hates me!)

This change should fix DPI scaling issue when wfreerdp.exe is started using parent-handle argument of a control/window with SystemAware or PerMonitorDpiAware mode.

This was tested on two machines but I'm not sure if the usage of these APIs is correct. Please let me know if there's a better way or if there are issues with my suggested implementation.

Thank you!

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@StefanKoell looks like this needs some preprocessor conditional ( https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170 ) as the 32bit build  is running an older windows version.

**Comment by StefanKoell** [comment]
Is it possible to just include the code branch (DPI check) on a certain Windows version? Or is there a Windows version I can use as preprocessor conditional which is suitable for wfreerdp.exe?

**Comment by akallabeth** [comment]
@StefanKoell did push a fix for that on your branch.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by mfleisz** [comment]
Since the DPI functions are only available since a certain Win10 version (1607) run-time dynamic linking should be used instead of load-time dynamic linkage.

For an example refer to `client/Windows/wf_cliprdr.c` (search for user32.dll).

**Comment by StefanKoell** [comment]
@akallabeth No, I didn't push anything else.

**Comment by akallabeth** [comment]
@mfleisz good point.

**Comment by akallabeth** [comment]
@StefanKoell I meant I did push ;)
but just as @mfleisz said, better way is to use `GetProcAddress` to get a function pointer to the library and only use it if it exists.

**Pull request merged**
