### PR TITLE
Removed use of empty_region

### PR DESCRIPTION
**Pull request by akallabeth**
* Simplify region handling
* Remove hacks that require freeing a const pointer

### CODE REVIEW

**Comment by hardening** [comment]
Well I like the empty region thing, because it allowed to completely remove tests on `data`. I'd rather propose to add a ref counter in `REGION16_DATA`, and if the empty region starts with a 1 counter, then it will never be freed and we can have a standard case in every places.
Not sure we will use it but it will also allow to do some region aliasing (2 region pointing on the same data).

**Comment by akallabeth** [comment]
@hardening that would break the API as `REGION16_DATA` is exposed.
Restructured it this way to avoid the hack (free on const data) and simplify tests while keeping compatibility with 2.1.2

**Comment by hardening** [comment]
I disagree `REGION16_DATA` is not exposed, it's presented as an opaque type.

**Comment by hardening** [comment]
@akallabeth what about https://github.com/hardening/FreeRDP/tree/region_ref ?

**Comment by bmiklautz** [comment]
@akallabeth I remove consider for stable (for now) as it's not necessary for stable.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request closed without merging**
