### PR TITLE
Android api upgrade and restructuring

### PR DESCRIPTION
**Pull request by akallabeth**
# What has changed:
* Fixes (some) return value checks for comand line parser
* Fixes wlog and environment issues with android
* Building shared libraries on android now
* Migrated to gradle (android studio) for android java code
* Added build scripts for native libraries
** Now supports ```armeabi armeabi-v7a and x86``` by default
** More architectures as soon as openssl builds there

# Usage:
* run ```./scripts/android-build-freerdp.sh```
* Import ```client/Android/Studio``` in Android Studio
* You're ready to go

### CODE REVIEW

**Comment by akallabeth** [comment]
Please ignore the failed android build, the pull request tester will need an update after this pull to accommodate the changes in the build system.

**Comment by mfleisz** [comment]
@akallabeth @bmiklautz I think we should fix the PR builder before merging this - who is able to do that?

**Comment by akallabeth** [comment]
I can do that, but it would require an immediate merge as the old android builds would fail from that point on.

**Comment by mfleisz** [comment]
@akallabeth OK - if you got time I will merge the PR so that we have it working asap!

**Comment by akallabeth** [comment]
@freerdp-bot test again

**Comment by akallabeth** [comment]
@freerdp-bot test once more

**Comment by akallabeth** [comment]
@freerdp-bot ok, test and now succeed!

**Comment by akallabeth** [comment]
@freerdp-bot test, this time with x86

**Comment by akallabeth** [comment]
@freerdp-bot Ok, test now also gradle

**Pull request merged**
