### PR TITLE
Inlined heavily used functions.

### PR DESCRIPTION
**Pull request by akallabeth**
Inlined a few gdi functions heavily used to improve performance.
@giox069 @antenore Could you check if current GDI rendering speed improved for you too?

### CODE REVIEW

**Comment by antenore** [comment]
@giox069 I'm busy the whole day :-\ sorry.

**Comment by akallabeth** [comment]
Related to #3530

**Comment by akallabeth** [comment]
@freerdp-bot come on, test please!

**Comment by giox069** [comment]
The PR works, but it's still slow.
You can find a couple of comparison video between FreeRDP of October 5 (commit 1d06087) and your akallabeth/gdi_speedup here: http://s1.casa.panozzo.it/remvideo/
Both video are taken with the same commandline:
``xfreerdp /v:192.168.56.2 /u:giovanni /d:mydomain /gdi:sw /size:1280x1024``
xfreerdp running on a Core i5-3570K desktop PC with ubuntu. The Windows 10 (Pro, ver 1607) machine is running inside qemu/kvm on a Core i3 CPU.

**Comment by bmiklautz** [comment]
@giox069 just to make sure you build FreeRDP as Release?

**Comment by giox069** [comment]
No, I built it as DEBUG, in both cases :( I would be able to do other testing only this night (CET), not now.

**Comment by bmiklautz** [comment]
@giox069 thanks!

**Comment by akallabeth** [comment]
@giox069 @antenore Ok, found the culprit. GDI_SRCCOPY and GDI_DSTCOPY are quite heavy if not using optimized versions. Could you give this another try, but please enable some optimizations (the inline code is really slow otherwise)

**Comment by akallabeth** [comment]
@freerdp-bot Would you be kind enough to not stop testing halfway through?

**Comment by giox069** [comment]
Very good! I tested it and it's faster. I have no way to measure the speed, but it seems to be at the same speed we had before Oct 6 big updates. I added a video, if you would like to compare speed.

I would like to test on a Raspberry PI 3 (for its slowness and ARM compatibility), but really I have no time to do it this week :(

My commandline for cmake is
```cmake -DWITH_SANITIZE_ADDRESS=on -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DWITH_PULSE=on -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp```

Removing both ` -DWITH_SANITIZE_ADDRESS=on` and `-DCMAKE_BUILD_TYPE=Debug` seems not to improve speed.

Are there other useful cmake switches optimizations ?

**Comment by akallabeth** [comment]
@giox069 Depends on your setup. Just to be sure to have the best flags pass ```-DCMAKE_BUILD_TYPE=Release```

**Pull request merged**
