### PR TITLE
FreeRDP multimonitor: Use first command line element, then primary, …

### PR DESCRIPTION
**Pull request by T3N4K4**
...then do a fallback to 0,0.

I tried to address the issue of #3439 and some more of the multimonitor / primary monitor problems for myself.
The FreeRDP code makes always a fallback to 0,0 since the primary monitor is always not found.

My fix may be still work in progress and I don't know if it is as FreeRDP intended this. But I am open for advice how to do it properly.

Currently I look up what the user specified on the command line with /monitors:x,y... and take x as the default monitor (primary). If no command line option was given I use the default monitor which I get with
```
screen = DefaultScreenOfDisplay(xfc->display);
monitor_index = XScreenNumberOfScreen(screen);
```
and last we try to make a fallback to 0,0 if still no primary monitor was found (I heard that it is a thing in newer *nix versions that there is no primary monitor set).

In my tests on ubuntu 15.10 / xfce4:
/monitors:0, /monitors:1, /monitors:1,0 /multimon:force (our server does not advertise multimonitor), /monitors:0,1 /multimon:force or /multimon:force only - did work.

### CODE REVIEW

**Comment by akallabeth** [comment]
@T3N4K4 looks like #4187 fixes the same issue? Sorry to have looked at that one first, but it was the highest in my listing.

**Comment by T3N4K4** [comment]
@akallabeth no problem, I submitted mine first, reworked the history and saw later that @hardening was on the same issue with an own commit.
My fix uses the "default"-monitor given back from the xinerama output though instead of only using /monitors:x1,x2... before doing a fallback to 0,0. I don't know though if my fix is best practice ;-)

**Comment by akallabeth** [comment]
@T3N4K4 Ok, I've merged #4187 first, as both your and @hardening s pull address two slightly different issues. Could you rebase to current master, as the last does have some conflicting changes? Sorry for the comment in the closed pull, did manage to overlook this one at my first search :/

**Comment by T3N4K4** [comment]
Sure I'll work on it as soon as I can :-)

**Comment by T3N4K4** [comment]
@akallabeth it could take a while ... unfortunately rebasing or merging hates me :-(

**Comment by akallabeth** [comment]
@T3N4K4 I know that feeling, take your time

**Comment by T3N4K4** [comment]
@akallabeth I hope I fixed it now.

**Comment by akallabeth** [comment]
@T3N4K4 Any update on this?

**Comment by T3N4K4** [comment]
@akallabeth no sorry, I haven't had the time to check your mentioned errors .. :-(, and I have to read a bit more on sanitizing arguments ;)

**Comment by T3N4K4** [comment]
@akallabeth just a question. Why strtol() ? In the cmdline.c file the MonitorIds are set with atoi().

**Comment by akallabeth** [comment]
@T3N4K4 atoi can not properly report if the argument is an integer or not. Should be replaced everywhere.

**Comment by akallabeth** [comment]
@T3N4K4 Have a look at #4237 
I've removed ```atoi``` in that pull completely.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@mfleisz @hardening Anyone time for a review of this one?

**Comment by hardening** [comment]
It's not clear for me what this PR is trying to solve, can you elaborate @T3N4K4 ?

**Comment by T3N4K4** [comment]
@hardening as said in my first post.
FreeRDP (before your PR) used the 0,0 point to look for the first monitor. But if you wanted to start it on the primary monitor there was no option for it.
/monitors did not work either.

In my PR we look if the user used the /monitors command line, then if not given use the primary monitor (which can be anything else) and as a fallback use the 0,0 point.

So if your primary monitor has 1920x1080+1920+0 and your second 1920x1080+0+0 always the second one was used if /monitors was not entered. In my opinion the primary monitor should be used if no /monitors are entered.

**Comment by mfleisz** [comment]
@T3N4K4 
What I don't understand is the need for the for-loop if the "default monitor" is not originated at 0/0. As far as I understand the "default monitor" id is either passed using the /monitors argument or is determined using XScreenNumberOfScreen() to get the id of the primary monitor (in case /monitors is absent). In both cases we want to use that monitor - no matter if it is at 0/0 or not?

**Comment by T3N4K4** [comment]
@mfleisz true. But I happen to stumble upon some test-machines which did not have a primary screen. At least not one which was set and could be read with tools like xrandr. I did not try this fix on those machines but I remembered this state and guessed that a fallback is better. I don't know in which state we would land if /monitors is not set and XScreenNumberOfScreen fails (or sth. like that).

But we can change it sure :-)

**Comment by mfleisz** [comment]
@T3N4K4 
Ah ok - didn't know that the API might return something stup ... I'm fine leaving it as is for now ...

**Pull request merged**
