### PR TITLE
fix Chinese title on mac

### PR DESCRIPTION
**Pull request by amazingfate**
Here are two issues when window title has Chinese characaters:
1, title string has to init with `stringWithCString`
2, NSString length method is not right for Chinese characaters, use `lengthOfBytesUsingEncoding:NSUTF8StringEncoding` instead.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by amazingfate** [comment]
clang-format changed `settings->ServerPort` for me. Should I change it back since there is a failure? 
https://ci.freerdp.com/job/code-quality-checker/4459/console
@akallabeth

**Comment by akallabeth** [comment]
@amazingfate looks like a formatter issue. you might want to deactivate it for these lines, see **https://clang.llvm.org/docs/ClangFormatStyleOptions.html**

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Pull request merged**
