### PR TITLE
Bugfix in RDP Gateway HTTP: read/skip full HTTP body

### PR DESCRIPTION
**Pull request by ccpp**
Bugfix in RDP Gateway HTTP: read/skip full HTTP body for non-RPC responses

This fixes issues #3300 and #3479, but it reveals that there might be a timeout issue with /gt:http and /gt:auto

So test with both options /gt:rpc and /gt:http please

### CODE REVIEW

**Comment by akallabeth** [comment]
@ccpp Nice catch! Just had a look at the whole code, looks like there is still an issue.
The whole data reading part must be done before any parsing is attempted as ```strtok``` modifies the data and if only a part of the header is read the next attempt will fail.

**Comment by ccpp** [comment]
Hi akallabeth,
I do not think there is a problem, because:

1. The `Content-Length` header MUST have been parsed before this step, otherwise we do not even know how much data is missing.
2. The header parsing has been fully accomplished. This code is in an if-block which even breaks the outer reading loop.
3. Header lines are counted beforehand, therefore `strtok` is only called for the HTTP header lines; HTTP body will never be `strtok`'d (save there's another bug. The code looks a little complicated, but I guess they had to do it this way because you cannot give `strtok` a buffer length)

**Comment by hardening** [comment]
The design of these code should be retreated completely, anyway your fix seems to do the job.

just a note not part of your changes: if the content-length is really big we take the risk to memory explode when reallocating the stream

**Comment by hardening** [comment]
@freerdp-bot test good bot, test !

**Comment by akallabeth** [comment]
@ccpp Yes, you're right. Just don't like the overall state of the code for http gateway as @hardening already stated.
@hardening I'd suggest lets merge it to fix the gateway issues for the time being and create a new issue for refactoring the module?

**Comment by hardening** [comment]
@akallabeth +1

**Pull request merged**
