### PR TITLE
warning & cross compile fixes

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by hardening** [comment]
ccmake says:
```
CMake Error at client/SDL/common/res/CMakeLists.txt:51 (add_custom_command):
   Error evaluating generator expression:

     $<TARGET_FILE:sdl-common-res2bin>

   No target "sdl-common-res2bin"
 Call Stack (most recent call first):
   client/SDL/common/res/CMakeLists.txt:94 (convert_to_bin)

 CMake Error at client/SDL/common/res/CMakeLists.txt:51 (add_custom_command):
   Error evaluating generator expression:

     $<TARGET_FILE:sdl-common-res2bin>

   No target "sdl-common-res2bin"
 Call Stack (most recent call first):
   client/SDL/common/res/CMakeLists.txt:94 (convert_to_bin)

```
and during build that gives:
```
[ 98%] Built target sdl-common-aad-view
make[2]: *** No rule to make target 'client/SDL/common/res/sdl-common-res2bin', needed by 'client/SDL/common/res/bin/OpenSans_VariableFont_wdth_wght_ttf.hpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:3065: client/SDL/common/res/CMakeFiles/sdl-common-client-res.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

**Comment by akallabeth** [comment]
@hardening you did build as suggested in https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html ?

**Comment by hardening** [comment]
> @hardening you did build as suggested in https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html ?

Yes, that's not my first cross compile build with mingw. But it was the first time I was trying to build with SDL3 support.

**Comment by akallabeth** [comment]
@hardening ok, then this is the first one you use with host tools to run ;)
basic steps:
1. do a native build  in `build-native`
2. do a mingw build in `build-mingw`
3. you need to tell `CMake` where the native tools can be found (e.g. `-DSdlCommonRes2bin_DIR=<full path to native build>`
4. run your build

**Comment by hardening** [comment]
Ok that makes the build process so complex, perhaps `sdl-common-res2bin` that is so trivial would deserve to be any arch independent script. Python would have my preference, but it could also be perl as we need it to build openssl...

**Comment by akallabeth** [comment]
@hardening pull requests welcome ;)
under linux the `xxd` tool might be a suitable replacement.

**Comment by akallabeth** [comment]
ok, building as expected if path to native build is supplied.
@hardening do you need to build with `-DSDL_USE_COMPILED_RESOURCES=ON`? if you turn it off the whole thing is not required.

**Comment by mu-ki** [comment]
Im facing the below issue

CMake Error at client/SDL/common/res/CMakeLists.txt:51 (add_custom_command):
   Error evaluating generator expression:

     $<TARGET_FILE:sdl-common-res2bin>

   No target "sdl-common-res2bin"
 Call Stack (most recent call first):
   client/SDL/common/res/CMakeLists.txt:94 (convert_to_bin)

 CMake Error at client/SDL/common/res/CMakeLists.txt:51 (add_custom_command):
   Error evaluating generator expression:

     $<TARGET_FILE:sdl-common-res2bin>

   No target "sdl-common-res2bin"
 Call Stack (most recent call first):
   client/SDL/common/res/CMakeLists.txt:94 (convert_to_bin)
   
   When executing
   
   cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=D:/FreeRDP/SupportFiles/toolchain.cmake -B freerdp-build -S freerdp -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=D:/FreeRDP/BuildFiles -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DWITH_SWSCALE=OFF -DWITH_FFMPEG=OFF -DWITH_WEBVIEW=OFF -DCMAKE_INSTALL_PREFIX=D:/FreeRDP/BuildFiles -DSDL_USE_COMPILED_RESOURCES=ON

**Pull request merged**
