### PR TITLE
MD4, MD5 and HMAC-MD5 replacements

### PR DESCRIPTION
**Pull request by akallabeth**
RDP requires some outdated hash algorithms to function.
OpenSSL et al start dropping support for these, but we´re stuck unless microsoft releases some updates to the protocol :/

### CODE REVIEW

**Comment by MartinHaimberger** [comment]
LGTM +1
tested under ubuntu 22.04 with openssl 3.0.2 and legacy mode disabled, NTLM now working again.

**Review by MartinHaimberger — APPROVED** [review]
LGTM +1
tested under ubuntu 22.04 with openssl 3.0.2 and legacy mode disabled, NTLM now working again.

**Comment by akallabeth** [comment]
will update the pr and clean up some stuff first

**Comment by MartinHaimberger** [comment]
tested again under ubuntu 22.04 with openssl 3.0.2 and legacy mode disabled, NTLM working

**Review by hardening — APPROVED** [review]
LGTM

**Pull request merged**
