### PR TITLE
Fix raw surfaces displaying + misc other changes

### PR DESCRIPTION
**Pull request by hardening**

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
youhou, after tons of failed tests, it finally works !

**Comment by bmiklautz** [comment]
@hardening what did you use for re-formatting? - astyle does ugly thing - right but it at least enforces some kind of standard ;)

**Comment by hardening** [comment]
Well I think we've accepted ugly things introduced by astyle too quickly. This was a rollback attempt. We all agreed that astyle's output with 80 char / line limitation doesn't provide any gain in terms of readability.

**Comment by akallabeth** [comment]
@hardening It does, think 3-way diff ;)

**Comment by bmiklautz** [comment]
@hardening @akallabeth I'd suggest we sort out the formatting and what we really want once and for all including a script/config that needs to be used and format all at one shot (as in pull request).

**Comment by bmiklautz** [comment]
If the last commit in this PR is just formatting you maybe want to remove it and we do it as suggested in a different one.

**Comment by hardening** [comment]
he he my git skills are improving, I managed to do the commit drop !

**Comment by bmiklautz** [comment]
@hardening nice \o/. Thanks.

**Pull request merged**
