### PR TITLE
Updated OpenBSD changes

### PR DESCRIPTION
**Pull request by bceverly**
Took into account feedback on previous pull request

### CODE REVIEW

**Comment by akallabeth** [comment]
@bceverly You should have a look at the ```FindXXX.cmake``` files and fix the search paths there. This way it should not be necessary to add a global link directory. As for ```execinfo``` libraries should be linked by the library or executable actually using them and not globally. Still missing the revert for the ```#ifdef``` that is not necessary if properly adding the include path for the libraries detected.

**Comment by bceverly** [comment]
I believe my latest push addresses everything.  Turns out we didn't need
the library on OpenBSD so I made its inclusion for FreeBSD only.


Thanks,
Bryan

**Comment by bmiklautz** [comment]
@bceverly if possible try not to have merges within your pull request.

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
Ok, looks good now ;)

**Comment by hardening** [comment]
LGTM too, so I'm merging it too fast like the last time ;)

**Pull request merged**
