### PR TITLE
Fix some warnings in MinGW

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by akallabeth — APPROVED** [review]
Changes look good, lets see what @freerdp-bot has to say.

**Comment by akallabeth** [comment]
Looks like you need to run `git clang-format` on the changes

**Comment by Biswa96** [comment]
In CI, the requested clang-format output looks horrible.

**Comment by akallabeth** [comment]
@Biswa96 that is the style. too much hassle if everyone uses their own one. (`git diff` was a nightmare back then)

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@Biswa96 thank you for this nice contribution!

**Comment by Biswa96** [comment]
BTW, there are other fixes required which are in other PRs. Can those be merged? Some of them are needed.

**Comment by akallabeth** [comment]
@Biswa96 if they are cleaned up yes. Currently they are in no state to be merged.

**Pull request merged**
