### PR TITLE
[CMake] add public headers to targets

### PR DESCRIPTION
**Pull request by akallabeth**
Add all public headers to the respective library targets.
This helps an IDE to show the headers grouped to the correct target.

current mapping (directories of sub targets excluded from base target):
* `winpr/include/winpr` to target `winpr`
* `winpr/include/winpr/tools` to target `winpr-tools`
* `include/freerdp` to target `freerdp`
* `include/freerdp/client*` to target `freerdp-client`
* `include/freerdp/server*` to target `freerdp-server`
* `include/freerdp/server/proxy*` to target `freerdp-server-proxy`

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by mfleisz — APPROVED** [review]

**Pull request merged**
