### PR TITLE
Fix surface bit with RFX codec after color conversion fix

### PR DESCRIPTION
**Pull request by realjiangms**
Fixes issue #3543

### CODE REVIEW

**Comment by akallabeth** [comment]
@realjiangms Isn't this what I've done with #3545?

**Comment by realjiangms** [comment]
@akallabeth Yes :). Let's keep it as reference and close it once #3545 is merged

**Comment by realjiangms** [comment]
All my changes have been included in #3545 
Will close after it is merged

**Comment by bmiklautz** [comment]
@realjiangms thanks.
Superseded by #3545

**Pull request closed without merging**
