### PR TITLE
Fix hang.

### PR DESCRIPTION
**Pull request by xsumbe00**

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by awakecoding** [comment]
@xsumbe00 can you tell me how you got the server to hang in that place? I'm pretty sure it was intentionally made this way. It was made such that it kept looping until the subsystem resets the event, otherwise we could go in some weird state IIRC.

**Comment by xsumbe00** [comment]
It hangs ALWAYS on VirtualBox with just one CPU:

------------  lwp# 3 / thread# 3  ---------------
 071ae765 pollsys  (6e0ec04, 1, 0, 0)
 070f488e poll     (6e0ec04, 1, ffffffff, 0, 71f23b0, 22) + 7e
 0768d53e waitOnFd (22, ffffffff, 6e0ec84, 70c76e6, 71f23b0, 0) + 3e
 0768d9af WaitForSingleObject (8d670e0, ffffffff, 0, 8062d68, 3, 1) + 453
 0768b362 EnterSynchronizationBarrier (806a4d8, 0, 7d0, b0, b0, 290) + 6b
 07c10222 x11_shadow_screen_grab (806a340, 0, 0, 0, 0, 0) + 414
 07c105f5 x11_shadow_subsystem_thread (806a340, 0, 0, 0, 6e10a40, 71f1000) + 1f5
 076c3632 thread_launcher (83d42a8, 71f1000, 6e0efa8, 71a9de7) + 135
 071a9e39 _thrp_setup (6e10a40) + 99
 071aa0d0 _lwp_start (0, 0, 0, 0, 0, 0)
------------  lwp# 4 / thread# 4  ---------------
 071ae765 __pollsys (6d0fcc4, 1, 6d0fc98, 0) + 15
 070f488e poll     (6d0fcc4, 1, 0, 76a0844, 83f2ae0, 9) + 7e
 0768d53e waitOnFd (9, 0, 6d0fd44, 70e7128, 8d615e8, 0) + 3e
 0768d9af WaitForSingleObject (8062d68, 0, 0, ffffffff, 0, 0) + 453
 07c0b265 shadow_client_thread (83d4fb0, 0, 0, 0, 6e11240, 71f1000) + 2d9
 076c3632 thread_launcher (8d60088, 71f1000, 6d0ff88, 71a9de7) + 135
 071a9e39 _thrp_setup (6e11240) + 99
 071aa0d0 _lwp_start (0, 0, 0, 0, 0, 0)

---
With two CPUs it's much better. But I would almost swear it happens there too.

But now looking at it. My fix is probably really bad since without it the input from keyboard and mouse works much better (with two CPUs).

**Comment by xsumbe00** [comment]
Ok. It definitely hangs on real system with two CPUs too. Stack for shadow_client_thread looks little bit different though.

------------  lwp# 1 / thread# 1  ---------------
 071ae765 pollsys  (feffe9b4, 1, 0, 0)
 070f488e poll     (feffe9b4, 1, ffffffff, 0, a, f) + 7e
 0768d53e waitOnFd (f, ffffffff, feffea34, 0, 1, 0) + 3e
 0768d642 WaitForSingleObject (88bcf08, ffffffff, feffeb08, 0, 80507a5, feffeb98) + e6
 0805135b main     (2, feffeb08, feffeb14, 8047030, feffeafc, 8051012) + 11b
 08051073 _start   (2, feffec08, feffec25, 0, feffec2b, feffec4f) + 83
------------  lwp# 2 / thread# 2  ---------------
 071ae765 pollsys  (6f2ad20, 3, 0, 0)
 070f488e poll     (6f2ad20, 3, ffffffff, 1000000, d, 1) + 7e
 0768e6e8 WaitForMultipleObjects (3, 6f2ae8c, 0, ffffffff, 0, 0) + 72c
 07c0e3ad shadow_server_thread (8061e60, 0, 0, 0, 6e10240, 71f1000) + 12e
 076c3632 thread_launcher (88bcf08, 71f1000, 6f2afc8, 71a9de7) + 135
 071a9e39 _thrp_setup (6e10240) + 99
 071aa0d0 _lwp_start (0, 0, 0, 0, 0, 0)
------------  lwp# 3 / thread# 3  ---------------
 071ae765 pollsys  (6e0ec04, 1, 0, 0)
 070f488e poll     (6e0ec04, 1, ffffffff, 0, 71f23b0, 22) + 7e
 0768d53e waitOnFd (22, ffffffff, 6e0ec84, 70c76e6, 71f23b0, 0) + 3e
 0768d9af WaitForSingleObject (9f31f40, ffffffff, 0, 8062d48, 3, 1) + 453
 0768b362 EnterSynchronizationBarrier (806a4d8, 0, 7d0, 1a0, 90, 490) + 6b
 07c10222 x11_shadow_screen_grab (806a340, 0, 0, 0, 0, 0) + 414
 07c105f5 x11_shadow_subsystem_thread (806a340, 0, 0, 0, 6e10a40, 71f1000) + 1f5
 076c3632 thread_launcher (88bd380, 71f1000, 6e0efa8, 71a9de7) + 135
 071a9e39 _thrp_setup (6e10a40) + 99
 071aa0d0 _lwp_start (0, 0, 0, 0, 0, 0)
------------  lwp# 4 / thread# 4  ---------------
 071ae765 __pollsys (6d0fcc4, 1, 6d0fc98, 0) + 15
 070f488e poll     (6d0fcc4, 1, 0, 71a2501, 97438d0, 9) + 7e
 0768d53e waitOnFd (9, 0, 6d0fd44, 70e7128, 71f23b0, 0) + 3e
 0768d9af WaitForSingleObject (8062d48, 0, 80840d8, ffffffff, 0, 0) + 453
 07c0b265 shadow_client_thread (88be590, 0, 0, 0, 6e11240, 71f1000) + 2d9
 076c3632 thread_launcher (9741b28, 71f1000, 6d0ff88, 71a9de7) + 135
 071a9e39 _thrp_setup (6e11240) + 99
 071aa0d0 _lwp_start (0, 0, 0, 0, 0, 0)

**Comment by xsumbe00** [comment]
I was trying to fix the situation (with one CPU) where:

1) x11_shadow_subsystem_thread entres EnterSynchronizationBarrier here (and waits):
https://github.com/FreeRDP/FreeRDP/blob/master/server/shadow/X11/x11_shadow.c#L715
2) shadow_client_thread entres also EnterSynchronizationBarrier here (and both threads exits):
https://github.com/FreeRDP/FreeRDP/blob/master/server/shadow/shadow_client.c#L984
3) thread x11_shadow_subsystem_thread starts first and reset the event and set it again
https://github.com/FreeRDP/FreeRDP/blob/master/server/shadow/X11/x11_shadow.c#L731
https://github.com/FreeRDP/FreeRDP/blob/master/server/shadow/X11/x11_shadow.c#L713
4) shadow_client_thread awakes later and will spin forever here:
https://github.com/FreeRDP/FreeRDP/blob/master/server/shadow/shadow_client.c#L986

Does it make any sense? Any idea?

**Comment by awakecoding** [comment]
@xsumbe00 I know there was something odd going on with that complex synchronization case... but it's been a while and I'd need to jump into it again. Basically we want to wake up all the client threads when an update is ready, have them encode from the buffer, wait until all of them are done and then move on. The problem that happened IIRC is that if the client thread doesn't wait until all threads are done, the update event will still be set, so the thread may try encoding a second time and entering the barrier again, which isn't what we want.

**Comment by realjiangms** [comment]
I think the original code works. It just consume CPU while it is waiting for server reset UpdateEvent.
But EnterSynchronizationBarrier function itself doesn't work.
In EnterSynchronizationBarrier(), consider following case:
           
       count = InterlockedIncrement(&(pBarrier->count)); // Now count = pBarrier->lTotalThreads -1

                 /* ======> what happen if now some one reached the count released other threads?
                 * Other thread will be released. subsystem may reinitialized anther barrier
                 * And we then waiting for the new one. We never increase the count of the new one
                 * Then we stops everyone
                 */

// Now count == pBarrier->lTotalThreads and another thread had already notified all other threads including the subsystem (update event owner).
                       if (count < pBarrier->lTotalThreads)
                          {
                                     WaitForSingleObject(pBarrier->event, INFINITE);
                                      }
                                           else

**Comment by awakecoding** [comment]
@realjiangms if we could have the synchronization barrier fixed it would be great, even better if it can be tested with a unit test. as long as it behaves the same way it does on Windows.

**Comment by realjiangms** [comment]
@awakecoding
I don't come up with a way to fix the barrier itself with only the 'event' primitive. 
We can implement it with Linux mutex and condition, but then Barrier can't be used with WaitForSingleObject and WaitForMultipleObject.

**Comment by hardening** [comment]
@xsumbe00 the PR from @realjiangms has been merged, could you verify that the current master works as expected and close the issue if so. Thank you.

**Comment by xsumbe00** [comment]
I can no longer reproduce the issue. Thank you!

**Pull request closed without merging**
