### PR TITLE
Fixed capability checks for mouse and unicode input.

### PR DESCRIPTION
**Pull request by akallabeth**
* Check support for extended mouse events before sending to server.
* Check support for unicode input before sending to server.
* Some cleanup for internal functions in ```input.c```

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot you got your funny day? Test please!

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot you're a stubborn one, test please!

**Comment by hardening** [comment]
@freerdp-bot would you be so nice to test correctly please ?

**Pull request merged**
