### PR TITLE
fix graphics glitching for windows client with smart sizing

### PR DESCRIPTION
**Pull request by garbb**

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot test that please.

**Comment by hardening** [comment]
Note: this PR should be merged in squash mode to compress the history in a single commit.

**Comment by garbb** [comment]
Hi, I am new to this. Is there anything I need to do to fix my code?
It looks like the code quality check failed?
https://ci.freerdp.com/job/PullRequestTester/7873/
I looked at the output for it but nothing stands out to me about what could be wrong.
https://ci.freerdp.com/job/code-quality-checker/3579/console
Maybe it just crashed for some reason?

**Comment by hardening** [comment]
@garbb you're not passing the code quality-check, needs to apply what is suggested

**Comment by garbb** [comment]
I think maybe it was a blank line with two tab characters just above `wf_scale_rect(wfc, &updateRect);` ?
I have deleted it, will see if this fixes it.

**Comment by hardening** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
@akallabeth I'm rather uncomfortable with smartsizing, can you do the review for this one ?

**Review by akallabeth — APPROVED** [review]

**Pull request merged**
