### PR TITLE
Allow client build to be disabled

### PR DESCRIPTION
**Pull request by akallabeth**
* Adds ```WITH_CLIENT``` check to build platform dependent client.
* Fixes broken return values for ```PathCchIsRoot```

### CODE REVIEW

**Comment by bmiklautz** [comment]
@akallabeth is WITH_CLIENT currently the default? If not we should definitely define the option.

**Comment by akallabeth** [comment]
@bmiklautz Yes, it was already existing and I corrected my pull, ```WITH_CLIENT``` is now a dependent option of ```WITH_CLIENT_COMMON```. This way it is possible to create the client common library without any platform dependent stuff.

**Comment by nfedera** [comment]
Not a cmake expert but LGTM

**Comment by hardening** [comment]
+1

**Pull request merged**
