### PR TITLE
spnego: add missing check

### PR DESCRIPTION
**Pull request by fifthdegree**

### CODE REVIEW

**Comment by mfleisz** [comment]
@freerdp-bot test

**Comment by mfleisz** [comment]
@fifthdegree code quality checker is unhappy

**Comment by fifthdegree** [comment]
@mfleisz I ran it through clang-format now, apparently my editor did something weird to the spacing

**Comment by mfleisz** [comment]
@freerdp-bot test

**Review by mfleisz — APPROVED** [review]

**Pull request merged**
