### PR TITLE
Implemented FFMPEG based encoder.

### PR DESCRIPTION
**Pull request by akallabeth**
Does work rudimentary, will need some FFMPEG parameter adjustments.

### CODE REVIEW

**Comment by SriRamanujam** [comment]
Stacktrace when a Win10 client connects. Ubuntu 16.04 with libavcodec-ffmpeg56 7:2.8.6-1ubuntu2 amd64:

```
#0  0x00007ffff2c6eea8 in avcodec_encode_video2 () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#1  0x00007ffff69b87db in libavcodec_compress (h264=<optimized out>, ppDstData=0x7fffe9e65aa0, pDstSize=0x7fffe9e65a98)
    at /root/builds/freerdp-nightly/FreeRDP/libfreerdp/codec/h264_ffmpeg.c:259
#2  0x00007ffff69b4cb9 in avc420_compress (h264=0x7fffd885c5a0, pSrcData=pSrcData@entry=0x7fffc9fff010 "", SrcFormat=537135240, nSrcStep=nSrcStep@entry=5760, 
    nSrcWidth=nSrcWidth@entry=1440, nSrcHeight=nSrcHeight@entry=900, ppDstData=0x7fffe9e65aa0, pDstSize=0x7fffe9e65a98) at /root/builds/freerdp-nightly/FreeRDP/libfreerdp/codec/h264.c:210
#3  0x00007ffff63da8f7 in shadow_client_send_surface_gfx (nXSrc=0, nYSrc=0, nHeight=900, nWidth=1440, nSrcStep=5760, pSrcData=0x7fffc9fff010 "", client=0x7fffc000e2f0)
    at /root/builds/freerdp-nightly/FreeRDP/server/shadow/shadow_client.c:816
#4  shadow_client_send_surface_update (pStatus=<synthetic pointer>, client=0x7fffc000e2f0) at /root/builds/freerdp-nightly/FreeRDP/server/shadow/shadow_client.c:1323
#5  shadow_client_thread (client=<optimized out>) at /root/builds/freerdp-nightly/FreeRDP/server/shadow/shadow_client.c:1630
#6  0x00007ffff6652322 in thread_launcher (arg=0x7fffc0045ec0) at /root/builds/freerdp-nightly/FreeRDP/winpr/libwinpr/thread/thread.c:320
#7  0x00007ffff79b96fa in start_thread (arg=0x7fffe9e66700) at pthread_create.c:333
#8  0x00007ffff56f5b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by akallabeth** [comment]
@SriRamanujam Works with debian stretch (libavcodec57).  Could you have a look at the arguments passed to ```avcodec_encode_video2``` to trace the source of the crash? The input parameters are exactly the same as in my path, just the other API used.

**Comment by SriRamanujam** [comment]
Ah, it seems like you mistakenly pass `codecDecoderContext` instead of `codecEncoderContext` to `libavcodec_encode_video2`. `codecDecoderContext` is NULL, of course, which triggered the crash. 

Fixing that, however, led to a different crash:

```
[12:29:21:742] [10879:12013] [INFO][com.freerdp.client.shadow] - Gfx Pipeline Opened
[libx264 @ 0x7fffd4fc11a0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x7fffd4fc11a0] profile High, level 3.1
[libx264 @ 0x7fffd4fc11a0] Provided packet is too small, needs to be 383
[12:29:21:777] [10879:12013] [ERROR][com.freerdp.codec] - FFMPEG: Failed to encode video frame (Operation not permitted [-1])
```

I still don't know why libx264 insists on being involved in this process. I added the "FFMPEG:" tag to that specific error message (libfreerdp/codec/h264_ffmpeg.c:269) just to be sure that it was in fact libavcodec that was throwing that error. The actual segfault is the exact same one that I reported in #3978 , indicating that there was no data to send.

**Comment by akallabeth** [comment]
@SriRamanujam Ah, that explains it, oops ^^ As for x264, as far as I know FFMPEG uses it, so don't worry. The errors indicate some H264 encoder settings are still not optimal.
As for the crash, would be interesting to get the missing return check that leads to this crash.

**Comment by akallabeth** [comment]
@SriRamanujam Ok, got the crash ;)

**Comment by SriRamanujam** [comment]
It got further this time, and no crashing, but the frame still failed to encode:

```
[libx264 @ 0x7fa075a1cc40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x7fa075a1cc40] profile High, level 4.0
[libx264 @ 0x7fa075a1cc40] Provided packet is too small, needs to be 447
[14:55:32:732] [6936:10009] [ERROR][com.freerdp.codec] - FFMPEG: Failed to encode video frame (Operation not permitted [-1])
[14:55:32:732] [6936:10009] [ERROR][com.freerdp.client.shadow] - Failed to send surface update
[libx264 @ 0x7fa075a1cc40] frame I:3     Avg QP:15.33  size:   653
[libx264 @ 0x7fa075a1cc40] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x7fa075a1cc40] final ratefactor: 25.74
[libx264 @ 0x7fa075a1cc40] 8x8 transform intra:0.0%
[libx264 @ 0x7fa075a1cc40] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0%
[libx264 @ 0x7fa075a1cc40] i16 v,h,dc,p: 93%  0%  7%  0%
[libx264 @ 0x7fa075a1cc40] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x7fa075a1cc40] kb/s:156.64
```
My guess is that the problem from before is still there, but since the program isn't crashing anymore we can see some debug output from the frame encode afterwards now.

**Comment by SriRamanujam** [comment]
Any updates on this PR?

**Comment by akallabeth** [comment]
@SriRamanujam Sorry, currently busy with other stuff :/

**Comment by SriRamanujam** [comment]
I had some free time this week, so I decided to see if I couldn't figure out some libav tuning stuff myself. 

I managed to get the code into a state where both FreeRDP and Windows' RDP software decoder are able to render the stream. Windows' RDP hardware decoder for some reason renders the frames with a few seconds' delay, honestly not sure what to do about that but at least you can force software decoding in Group Policy. 

I want to stress that I am by no means a libavcodec or H.264 tuning genius or anything of the sort, I only barely know what the options do and I mostly just adapted recommendations from the ffmpeg wiki article on live streaming. There is almost certainly lots more that can be done. The work is here: https://github.com/SriRamanujam/FreeRDP/commit/b656b3e2db0ab2bdf9a00de1539760b139fbd83e

**Comment by akallabeth** [comment]
@hardening Any chance merging this one? Still needs fine tuning, but at least it is there and people can start debugging the remaining stuff ;)

**Comment by hardening** [comment]
Yeah sure, I wanted to do it but forget it

**Pull request merged**
