### PR TITLE
proxy dynamic channel passthrough support

### PR DESCRIPTION
**Pull request by alexandru-bagu**
this PR adds support for dynamic channel passthrough
the proxy config now allows you to set which channels you want proxied both for static as well as dynamic and it gives some hints as to what you may want to proxy
additionally this PR adds a log to inform you whether a channel is being actively ignored or not

### CODE REVIEW

**Comment by alexandru-bagu** [comment]
PR for #7123

**Comment by hardening** [comment]
I'm wondering about `freerdp/client/dynamic_passthrough.h` and `freerdp/server/dynamic_passthrough.h`, I'm not sure it has its place in public headers.

**Comment by hardening** [comment]
I'm also wondering about all these extra threads, 2 new threads per passed-through dynamic channel looks like overkill.

**Comment by kubistika** [comment]
There's no need for all of these changes.
The only thing is that the (already implemented) static vc passthrough needs to be fixed to buffer the VC messages and only then call the callback to forward them to the other side of the connection (currently it is not done so long messages like in drdynvc won't passthrough). After fixing this, you could just add "drdynvc" and "urbdrc" to the static passthrough channels list in proxy config and everything will work.

I already did fix it but I can't find the branch I did it in. Currently have no time for that, but I could elaborate if you need more info.

**Comment by alexandru-bagu** [comment]
> I'm wondering about `freerdp/client/dynamic_passthrough.h` and `freerdp/server/dynamic_passthrough.h`, I'm not sure it has its place in public headers.
 `freerdp/server/dynamic_passthrough.h` shouldn't be public true. issue with `client` one is that is needed by both drydvnc client plugin and proxy.

> I'm also wondering about all these extra threads, 2 new threads per passed-through dynamic channel looks like overkill.
I just followed the 'standard' I saw in the code. Though I suppose there's only 1 new thread, since one channel is handled by drydvnc plugin.

> There's no need for all of these changes.
> The only thing is that the (already implemented) static vc passthrough needs to be fixed to buffer the VC messages and only then call the callback to forward them to the other side of the connection (currently it is not done so long messages like in drdynvc won't passthrough). After fixing this, you could just add "drdynvc" and "urbdrc" to the static passthrough channels list in proxy config and everything will work.
> 
> I already did fix it but I can't find the branch I did it in. Currently have no time for that, but I could elaborate if you need more info.
I welcome another PR that does this better. What you are describing is maybe the client side, but for the server-side you still have to join the dynamic channel and handle it somehow.

**Comment by kubistika** [comment]
No, what I wrote is relevant to both server & client side.
Currently the passthrough callbacks just pass on the data to the other side of the connection (server -> client, client -> server), instead of first buffering the data (vc messages can be sent in chunks, and currently chunks are not handled by the proxy). That's why proxying the `drydnvc` isn't working now. But that could be easily fixed by properly handling the VC flags (CHANNEL_FIRST, CHANNEL_LAST, etc). Unfortunately I'm too busy now for creating a PR for that, but for sure, all of these changes are not needed for supporting `drdynvc` passthrough.

**Comment by akallabeth** [comment]
Refactoring proxy in https://github.com/FreeRDP/FreeRDP/tree/proxy
@kubistika if you are not too busy, would love to have your feedback to that.

**Pull request closed without merging**
