### PR TITLE
Stable 2.0 backports

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by antenore** [comment]
@akallabeth this will be released as FreeRDP 2.3.0?
Any idea when (more or less)?

We are planning Remmina v1.4.8 release and it would be nice to synchronize with the latest FreeRDP stable…

No rush, just asking

Thanks!

**Comment by akallabeth** [comment]
@antenore no timeline currently, I only do these so I don´t forget to backport. (If no API breaking changes, as in new symbols),occur then it will be `2.2.1`)
If you have a timeline for your release, just let us know, we can create a tag for that.

**Comment by antenore** [comment]
@akallabeth no rush, as I saw this PR I was just curious.

Since 2.2.0 we didn't get any new issues, so there's no need for an urgent release.

Thanks!

**Comment by joakim-tjernlund** [comment]
> @akallabeth no rush, as I saw this PR I was just curious.
> 
> Since 2.2.0 we didn't get any new issues, so there's no need for an urgent release.
> 
> Thanks!

Would be nice with a new release soon though, quite a lot has been fixed since last release.

**Comment by joakim-tjernlund** [comment]
Been a while now since last stable release, maybe do another ?

**Comment by joakim-tjernlund** [comment]
Has stable 2.0 become a dead end? Seems like this PR is the last stop.

**Comment by Fantu** [comment]
@akallabeth can you add also https://github.com/FreeRDP/FreeRDP/commit/d9d22aa42207e4d8e23ec5337bce83f87726cd20 please? I already tested it with 2.2: http://debomatic-armhf.debian.net/distribution#buster-backports/freerdp2/2.2.0+dfsg1-1~bpo10+1.1

**Review by kubistika — APPROVED** [review]

**Comment by hendwolt** [comment]
@akallabeth : Can #6516 be back-ported too, please? Otherwise stable-2.0 will not build on openSUSE.

**Comment by akallabeth** [comment]
@hendwolt created https://github.com/FreeRDP/FreeRDP/issues/6622 to request a backport, if you require anything else, please open such an issue so we can track the remaining required backports.

**Pull request merged**
