### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by kevin147147**
Explain how to enable H264 (otherwise the user thinks you cannot enable this)

## This is how are pull requests handled by FreeRDP
1. Every new pull request needs to build and pass the unit tests at https://ci.freerdp.com
1. At least 1 (better two) people need to review and test a pull request and agree to accept

## Preparations before creating a pull
* Rebase your branch to current master, no merges allowed!
* Try to clean up your commit history, group changes to commits
* Check your formatting! A _clang-format_ script can be found at ```.clang-format```
  * The cmake target ```clangformat``` reformats the whole codebase
* Optional (but higly recommended)
  * Run a clang scanbuild before and after your changes to avoid introducing new bugs
  * Run your compiler at pedantic level to check for new warnings

## To ease accepting your contribution
* Give the pull request a proper name so people looking at it have an basic idea what it is for
* Add at least a brief description what it does (or should do :) and what it's good for
* Give instructions on how to test your changes
* Ideally add unit tests if adding new features

## What you should be prepared for
* fix issues found during the review phase
* Joining our chat to talk to other developers or help them test your pull might accelerate acceptance
  * Matrix room : #FreeRDP:matrix.org (main)
  * XMPP channel: #FreeRDP#matrix.org@matrix.org (bridged)
  * IRC channel : #freerdp @ irc.oftc.net (bridged)
* Joining our mailing list <freerdp-devel@lists.sourceforge.net> may be helpful too.

### CODE REVIEW

**Review by akallabeth — CHANGES_REQUESTED** [review]
useless information, the string is used in a dependent setting (deactivated as long as you do not activate gfx)

**Comment by kevin147147** [comment]
Screenshot_20231019_133254

It is always visible here

**Comment by mfleisz** [comment]
@kevin147147 but you cannot tick it unless you enable GFX before

**Comment by kevin147147** [comment]
Sure I cannot click it. But as a user I don't know I have to click GFX in the first place. I thought maybe H264 is not supported and that's why I cannot click/enable it!

**Comment by kevin147147** [comment]
There is even this issue which I looked up. That's why I thought ok this feature is not working 

https://github.com/FreeRDP/FreeRDP/issues/6439

**Comment by akallabeth** [comment]
@kevin147147 issue #6439 is something completely unrelated?

**Comment by kevin147147** [comment]
yes and no. i wanted to try H264 but could not enable it, because i didn't know how. I even went into the code for building the library until i found out i just had to enable GFX and H264 works fine. So why not also close the issue

**Comment by kevin147147** [comment]
What about considering to enable this by default?

**Comment by akallabeth** [comment]
@kevin147147 closed the issue, true, nothing to do any more. as for enabling by default:
pull requests very welcome :+1:

**Pull request closed without merging**
