### PR TITLE
Send correct buttons when using a left-handed mouse

### PR DESCRIPTION
**Pull request by RolKau**
If you connect to a Windows server which is set up to use the left button as primary, from an X.org client which is also configured this way, the mouse buttons will appear switched in the RDP session!

This is because RDP expects physical button values to be sent whereas the client currently sends the X.org button event argument which are logical buttons values. The buttons are thus mapped twice.

This changeset implements an indirection where the logical buttons are first unmapped/reverse mapped back to the physical buttons, which are then sent over the wire and can then be mapped by the server. This enables a user to keep the same configuration at both the console and in a remote session.

I have enabled this mapping by default since a remote session should ideally behave like a console session. Left-handed server administrators that only configured their workstation but didn't bother to set the option at the server can use an option to get the back the old behaviour.

For those using a right-handed mouse (at both client and server), there should be no changes.

Tested with Ubuntu Precise 12.04 connecting to Windows 7 SP1.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by RolKau** [comment]
Reduced patch footprint, hopefully without reducing readability. There should be no effective change, but to be on the safe side: @freerdp-bot test

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by RolKau** [comment]
The logic of the flag was inverse of the wording; updated and squashed into the commit.

**Comment by akallabeth** [comment]
LGTM +1

**Comment by hardening** [comment]
Looks like this PR doesn't apply cleanly anymore. @RolKau any chance that you could update it ?

**Comment by RolKau** [comment]
@hardening Rebased onto 1b177fa (current master)

**Comment by hardening** [comment]
@RolKau I have reviewed again the patch, and I feel like the UnmapButton should be in the ABI stable part of settings, probably in the Input Capabilities section. @akallabeth any comment on this ?

**Comment by akallabeth** [comment]
@RolKau @hardening Yes, I agree. Would suggest the section labeled ```/* Miscellaneous */```.

**Comment by RolKau** [comment]
@akallabeth @hardening Like 6f6f0b0?

**Pull request merged**
