### PR TITLE
make help wording consistent with +/- command line attributes 

### PR DESCRIPTION
**Pull request by hendwolt**
make help wording consistent with +/- command line attributes (implements #4636)
- I synced +/- with enable/disable.
- Every line with +/- contains now one of the two words enable/disable.

Please check the results. There are a few lines, which sound "not good"; at least to me.
Especially:
   +gestures                   Enable consume multitouch input locally (default:off)
   +unmap-buttons              Enable letting the server see real physical pointer button (default:off)

### CODE REVIEW

**Comment by hendwolt** [comment]
That means, #4636 is invalid?

**Comment by hendwolt** [comment]
Or should we use both words?
instead of "Disable bitmap cache"
something like "Enable(+) or disable(-) bitmap cache"
?

**Comment by akallabeth** [comment]
The latter sounds more reasonable

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@hendwolt Thanks for the pull, and since I don't only want to complain, I've created a patched version here https://github.com/akallabeth/FreeRDP/tree/wording_consistent
what do you think? Wording might still be changed, but it is no longer necessary to change the text when the default changes (and that is often forgotten)

**Comment by hendwolt** [comment]
@akallabeth 
I like the idea, that enable/disable is set automatically according to the default values.
Will it be clear enough - from enable/disable, respective "+"/"-" - what the actual default is?

**Comment by hendwolt** [comment]
For some BOOL options, which did not have enable/disable until now, I'd consider little text changes. I'm not a native English speaker, but e.g.:
"Enable Redirect multitouch input" sounds not good to me.
I like "Enable redirection of multitouch input" better.

**Comment by akallabeth** [comment]
@hendwolt you're right, the text needs refinement :)

**Comment by akallabeth** [comment]
Replaced by #4681

**Pull request closed without merging**
