### PR TITLE
Mutualize dynamic channel stuff

### PR DESCRIPTION
**Pull request by hardening**
This is an effort to mutualize the code of dynamic channels.

### CODE REVIEW

**Comment by akallabeth** [comment]
@hardening nice! only `TSMF` and `sshagent` channels are left :)

**Comment by hardening** [comment]
Just rebased on last master. I've not done TSMF nor SSH yet (left as exercises for young contributors ;) )

**Comment by akallabeth** [comment]
@hardening ready for review or still work in progress?

**Comment by hardening** [comment]
@akallabeth that's ready for review. It has passed all my tests in valgrind, no leaks so far.

**Pull request merged**
