### PR TITLE
Monitor check verbose

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@xBr0th3rx does this work for you now?

**Comment by xBr0th3rx** [comment]
I'll check it right away and give you feedback.

**Comment by xBr0th3rx** [comment]
@akallabeth 

How can I test this exactly?

Do I have to compile it myself or how does it work?

I have never done this using the PullTester.

**Comment by akallabeth** [comment]
@xBr0th3rx 
1. check out this pull request
2. run `./packaging/scripts/create_rpm.sh` (if you are on fedora you said?) - you may need to install a few packages
3. install the generated `nightly` `RPM` packages you can find in `~/rpmbuild/RPMS/x86_64/`
4. run like every nightly package from `/opt/free...`

**Comment by xBr0th3rx** [comment]
I'm sorry but I don't quite understand what is meant by the check pull request.

I have only ever used git pull and git clone.

Could you please explain this to me step by step so that I can do this in the future.

We are using Debian 11

**Comment by akallabeth** [comment]
@xBr0th3rx see the instructions below your comments ;)

image

**Comment by xBr0th3rx** [comment]
@akallabeth 

Many thanks 

I am now in the process of building the package and will get back to you with the tests.

**Comment by xBr0th3rx** [comment]
@akallabeth 

1 Test failed :/
```
99% tests passed, 1 tests failed out of 149

Total Test time (real) =  10.12 sec

The following tests FAILED:
         68 - TestNCryptSmartcard (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /opt/freerdp-build/FreeRDP/obj-x86_64-linux-gnu && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
dh_auto_test: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=4 ninja test returned exit code 1
make[1]: *** [debian/rules:81: override_dh_auto_test] Fehler 1
make[1]: Verzeichnis „/opt/freerdp-build/FreeRDP“ wird verlassen
make: *** [debian/rules:60: build] Fehler 2
dpkg-buildpackage: Fehler: Unterprozess debian/rules build lieferte Exitstatus 2
```

**Comment by akallabeth** [comment]
@xBr0th3rx interesting. this is the way we build our nightly packages.
which error does the test abort with? (some older  `opensc` or other libraries have some leaks that might break the test)

**Comment by xBr0th3rx** [comment]
@akallabeth 
Here is the complete test extract:

```
   debian/rules override_dh_auto_test
make[1]: Verzeichnis „/opt/freerdp-build/FreeRDP“ wird betreten
dh_auto_test
        cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=4 ninja test
[0/2] Re-checking globbed directories...
[0/1] Running tests...
Test project /opt/freerdp-build/FreeRDP/obj-x86_64-linux-gnu
        Start   1: TestSynchInit
  1/149 Test   #1: TestSynchInit ............................   Passed    0.71 sec
        Start   2: TestSynchEvent
  2/149 Test   #2: TestSynchEvent ...........................   Passed    0.02 sec
        Start   3: TestSynchMutex
  3/149 Test   #3: TestSynchMutex ...........................   Passed    0.12 sec
        Start   4: TestSynchBarrier
  4/149 Test   #4: TestSynchBarrier .........................   Passed    0.69 sec
        Start   5: TestSynchCritical
  5/149 Test   #5: TestSynchCritical ........................   Passed    0.27 sec
        Start   6: TestSynchSemaphore
  6/149 Test   #6: TestSynchSemaphore .......................   Passed    0.01 sec
        Start   7: TestSynchThread
  7/149 Test   #7: TestSynchThread ..........................   Passed    0.21 sec
        Start   8: TestSynchTimerQueue
  8/149 Test   #8: TestSynchTimerQueue ......................   Passed    0.52 sec
        Start   9: TestSynchWaitableTimer
  9/149 Test   #9: TestSynchWaitableTimer ...................   Passed    0.61 sec
        Start  10: TestSynchWaitableTimerAPC
 10/149 Test  #10: TestSynchWaitableTimerAPC ................   Passed    0.18 sec
        Start  11: TestSynchAPC
 11/149 Test  #11: TestSynchAPC .............................   Passed    0.61 sec
        Start  12: TestLibraryLoadLibrary
 12/149 Test  #12: TestLibraryLoadLibrary ...................   Passed    0.02 sec
        Start  13: TestLibraryGetProcAddress
 13/149 Test  #13: TestLibraryGetProcAddress ................   Passed    0.01 sec
        Start  14: TestLibraryGetModuleFileName
 14/149 Test  #14: TestLibraryGetModuleFileName .............   Passed    0.01 sec
        Start  15: TestFileCreateFile
 15/149 Test  #15: TestFileCreateFile .......................   Passed    0.01 sec
        Start  16: TestFileDeleteFile
 16/149 Test  #16: TestFileDeleteFile .......................   Passed    0.01 sec
        Start  17: TestFileReadFile
 17/149 Test  #17: TestFileReadFile .........................   Passed    0.01 sec
        Start  18: TestSetFileAttributes
 18/149 Test  #18: TestSetFileAttributes ....................   Passed    0.02 sec
        Start  19: TestFileWriteFile
 19/149 Test  #19: TestFileWriteFile ........................   Passed    0.02 sec
        Start  20: TestFilePatternMatch
 20/149 Test  #20: TestFilePatternMatch .....................   Passed    0.01 sec
        Start  21: TestFileFindFirstFile
 21/149 Test  #21: TestFileFindFirstFile ....................   Passed    0.07 sec
        Start  22: TestFileFindFirstFileEx
 22/149 Test  #22: TestFileFindFirstFileEx ..................   Passed    0.01 sec
        Start  23: TestFileFindNextFile
 23/149 Test  #23: TestFileFindNextFile .....................   Passed    0.01 sec
        Start  24: TestFileGetStdHandle
 24/149 Test  #24: TestFileGetStdHandle .....................   Passed    0.01 sec
        Start  25: TestPipeCreatePipe
 25/149 Test  #25: TestPipeCreatePipe .......................   Passed    0.01 sec
        Start  26: TestPipeCreateNamedPipe
 26/149 Test  #26: TestPipeCreateNamedPipe ..................   Passed    0.01 sec
        Start  27: TestPipeCreateNamedPipeOverlapped
 27/149 Test  #27: TestPipeCreateNamedPipeOverlapped ........   Passed    0.02 sec
        Start  28: TestInterlockedAccess
 28/149 Test  #28: TestInterlockedAccess ....................   Passed    0.01 sec
        Start  29: TestInterlockedSList
 29/149 Test  #29: TestInterlockedSList .....................   Passed    0.01 sec
        Start  30: TestInterlockedDList
 30/149 Test  #30: TestInterlockedDList .....................   Passed    0.02 sec
        Start  31: TestSecurityToken
 31/149 Test  #31: TestSecurityToken ........................   Passed    0.01 sec
        Start  32: TestEnvironmentGetEnvironmentStrings
 32/149 Test  #32: TestEnvironmentGetEnvironmentStrings .....   Passed    0.01 sec
        Start  33: TestEnvironmentSetEnvironmentVariable
 33/149 Test  #33: TestEnvironmentSetEnvironmentVariable ....   Passed    0.01 sec
        Start  34: TestEnvironmentMergeEnvironmentStrings
 34/149 Test  #34: TestEnvironmentMergeEnvironmentStrings ...   Passed    0.01 sec
        Start  35: TestEnvironmentGetSetEB
 35/149 Test  #35: TestEnvironmentGetSetEB ..................   Passed    0.01 sec
        Start  36: TestCryptoHash
 36/149 Test  #36: TestCryptoHash ...........................   Passed    0.02 sec
        Start  37: TestCryptoRand
 37/149 Test  #37: TestCryptoRand ...........................   Passed    0.01 sec
        Start  38: TestCryptoCipher
 38/149 Test  #38: TestCryptoCipher .........................   Passed    0.02 sec
        Start  39: TestCryptoProtectData
 39/149 Test  #39: TestCryptoProtectData ....................   Passed    0.01 sec
        Start  40: TestCryptoProtectMemory
 40/149 Test  #40: TestCryptoProtectMemory ..................   Passed    0.02 sec
        Start  41: TestCryptoCertEnumCertificatesInStore
 41/149 Test  #41: TestCryptoCertEnumCertificatesInStore ....   Passed    0.01 sec
        Start  42: TestPathCchAddBackslash
 42/149 Test  #42: TestPathCchAddBackslash ..................   Passed    0.01 sec
        Start  43: TestPathCchRemoveBackslash
 43/149 Test  #43: TestPathCchRemoveBackslash ...............   Passed    0.01 sec
        Start  44: TestPathCchAddBackslashEx
 44/149 Test  #44: TestPathCchAddBackslashEx ................   Passed    0.01 sec
        Start  45: TestPathCchRemoveBackslashEx
 45/149 Test  #45: TestPathCchRemoveBackslashEx .............   Passed    0.01 sec
        Start  46: TestPathCchAddExtension
 46/149 Test  #46: TestPathCchAddExtension ..................   Passed    0.01 sec
        Start  47: TestPathCchAppend
 47/149 Test  #47: TestPathCchAppend ........................   Passed    0.01 sec
        Start  48: TestPathCchAppendEx
 48/149 Test  #48: TestPathCchAppendEx ......................   Passed    0.01 sec
        Start  49: TestPathCchCanonicalize
 49/149 Test  #49: TestPathCchCanonicalize ..................   Passed    0.01 sec
        Start  50: TestPathCchCanonicalizeEx
 50/149 Test  #50: TestPathCchCanonicalizeEx ................   Passed    0.02 sec
        Start  51: TestPathAllocCanonicalize
 51/149 Test  #51: TestPathAllocCanonicalize ................   Passed    0.02 sec
        Start  52: TestPathCchCombine
 52/149 Test  #52: TestPathCchCombine .......................   Passed    0.02 sec
        Start  53: TestPathCchCombineEx
 53/149 Test  #53: TestPathCchCombineEx .....................   Passed    0.02 sec
        Start  54: TestPathAllocCombine
 54/149 Test  #54: TestPathAllocCombine .....................   Passed    0.02 sec
        Start  55: TestPathCchFindExtension
 55/149 Test  #55: TestPathCchFindExtension .................   Passed    0.01 sec
        Start  56: TestPathCchRenameExtension
 56/149 Test  #56: TestPathCchRenameExtension ...............   Passed    0.01 sec
        Start  57: TestPathCchRemoveExtension
 57/149 Test  #57: TestPathCchRemoveExtension ...............   Passed    0.01 sec
        Start  58: TestPathCchIsRoot
 58/149 Test  #58: TestPathCchIsRoot ........................   Passed    0.01 sec
        Start  59: TestPathIsUNCEx
 59/149 Test  #59: TestPathIsUNCEx ..........................   Passed    0.01 sec
        Start  60: TestPathCchSkipRoot
 60/149 Test  #60: TestPathCchSkipRoot ......................   Passed    0.01 sec
        Start  61: TestPathCchStripToRoot
 61/149 Test  #61: TestPathCchStripToRoot ...................   Passed    0.01 sec
        Start  62: TestPathCchStripPrefix
 62/149 Test  #62: TestPathCchStripPrefix ...................   Passed    0.01 sec
        Start  63: TestPathCchRemoveFileSpec
 63/149 Test  #63: TestPathCchRemoveFileSpec ................   Passed    0.01 sec
        Start  64: TestPathShell
 64/149 Test  #64: TestPathShell ............................   Passed    0.01 sec
        Start  65: TestPathMakePath
 65/149 Test  #65: TestPathMakePath .........................   Passed    0.01 sec
        Start  66: TestIoGetOverlappedResult
 66/149 Test  #66: TestIoGetOverlappedResult ................   Passed    0.01 sec
        Start  67: TestMemoryCreateFileMapping
 67/149 Test  #67: TestMemoryCreateFileMapping ..............   Passed    0.01 sec
        Start  68: TestNCryptSmartcard
 68/149 Test  #68: TestNCryptSmartcard ......................***Failed    0.15 sec

=================================================================
==12588==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4097 byte(s) in 1 object(s) allocated from:
    #0 0x7f8e7ada6e8f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f8e7ad3fd18 in __interceptor_realpath ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:3608
    #2 0x7f8e7498afad  (<unknown module>)

SUMMARY: AddressSanitizer: 4097 byte(s) leaked in 1 allocation(s).

        Start  69: TestNCryptProviders
 69/149 Test  #69: TestNCryptProviders ......................   Passed    0.01 sec
        Start  70: TestIni
 70/149 Test  #70: TestIni ..................................   Passed    0.01 sec
        Start  71: TestVersion
 71/149 Test  #71: TestVersion ..............................   Passed    0.01 sec
        Start  72: TestImage
 72/149 Test  #72: TestImage ................................   Passed    0.13 sec
        Start  73: TestBacktrace
 73/149 Test  #73: TestBacktrace ............................   Passed    0.01 sec
        Start  74: TestQueue
 74/149 Test  #74: TestQueue ................................   Passed    0.01 sec
        Start  75: TestPrint
 75/149 Test  #75: TestPrint ................................   Passed    0.01 sec
        Start  76: TestPubSub
 76/149 Test  #76: TestPubSub ...............................   Passed    0.01 sec
        Start  77: TestStream
 77/149 Test  #77: TestStream ...............................   Passed    0.01 sec
        Start  78: TestBitStream
 78/149 Test  #78: TestBitStream ............................   Passed    0.01 sec
        Start  79: TestArrayList
 79/149 Test  #79: TestArrayList ............................   Passed    0.01 sec
        Start  80: TestLinkedList
 80/149 Test  #80: TestLinkedList ...........................   Passed    0.01 sec
        Start  81: TestListDictionary
 81/149 Test  #81: TestListDictionary .......................   Passed    0.01 sec
        Start  82: TestCmdLine
 82/149 Test  #82: TestCmdLine ..............................   Passed    0.01 sec
        Start  83: TestASN1
 83/149 Test  #83: TestASN1 .................................   Passed    0.02 sec
        Start  84: TestWLog
 84/149 Test  #84: TestWLog .................................   Passed    0.01 sec
        Start  85: TestWLogCallback
 85/149 Test  #85: TestWLogCallback .........................   Passed    0.01 sec
        Start  86: TestHashTable
 86/149 Test  #86: TestHashTable ............................   Passed    0.01 sec
        Start  87: TestBufferPool
 87/149 Test  #87: TestBufferPool ...........................   Passed    0.01 sec
        Start  88: TestStreamPool
 88/149 Test  #88: TestStreamPool ...........................   Passed    0.01 sec
        Start  89: TestMessageQueue
 89/149 Test  #89: TestMessageQueue .........................   Passed    0.01 sec
        Start  90: TestMessagePipe
 90/149 Test  #90: TestMessagePipe ..........................   Passed    0.02 sec
        Start  91: TestErrorSetLastError
 91/149 Test  #91: TestErrorSetLastError ....................   Passed    0.24 sec
        Start  92: TestGetNativeSystemInfo
 92/149 Test  #92: TestGetNativeSystemInfo ..................   Passed    0.01 sec
        Start  93: TestCPUFeatures
 93/149 Test  #93: TestCPUFeatures ..........................   Passed    0.01 sec
        Start  94: TestGetComputerName
 94/149 Test  #94: TestGetComputerName ......................   Passed    0.01 sec
        Start  95: TestSystemTime
 95/149 Test  #95: TestSystemTime ...........................   Passed    0.01 sec
        Start  96: TestLocalTime
 96/149 Test  #96: TestLocalTime ............................   Passed    0.01 sec
        Start  97: TestPoolIO
 97/149 Test  #97: TestPoolIO ...............................   Passed    0.01 sec
        Start  98: TestPoolSynch
 98/149 Test  #98: TestPoolSynch ............................   Passed    0.01 sec
        Start  99: TestPoolThread
 99/149 Test  #99: TestPoolThread ...........................   Passed    0.01 sec
        Start 100: TestPoolTimer
100/149 Test #100: TestPoolTimer ............................   Passed    0.01 sec
        Start 101: TestPoolWork
101/149 Test #101: TestPoolWork .............................   Passed    0.02 sec
        Start 102: TestThreadCommandLineToArgv
102/149 Test #102: TestThreadCommandLineToArgv ..............   Passed    0.01 sec
        Start 103: TestThreadCreateProcess
103/149 Test #103: TestThreadCreateProcess ..................   Passed    0.03 sec
        Start 104: TestThreadExitThread
104/149 Test #104: TestThreadExitThread .....................   Passed    0.03 sec
        Start 105: TestQuerySecurityPackageInfo
105/149 Test #105: TestQuerySecurityPackageInfo .............   Passed    0.02 sec
        Start 106: TestEnumerateSecurityPackages
106/149 Test #106: TestEnumerateSecurityPackages ............   Passed    0.02 sec
        Start 107: TestInitializeSecurityContext
107/149 Test #107: TestInitializeSecurityContext ............   Passed    0.02 sec
        Start 108: TestAcquireCredentialsHandle
108/149 Test #108: TestAcquireCredentialsHandle .............   Passed    0.01 sec
        Start 109: TestCredSSP
109/149 Test #109: TestCredSSP ..............................   Passed    0.01 sec
        Start 110: TestNTLM
110/149 Test #110: TestNTLM .................................   Passed    0.02 sec
        Start 111: TestTypes
111/149 Test #111: TestTypes ................................   Passed    0.01 sec
        Start 112: TestFormatSpecifiers
112/149 Test #112: TestFormatSpecifiers .....................   Passed    0.01 sec
        Start 113: TestAlignment
113/149 Test #113: TestAlignment ............................   Passed    0.01 sec
        Start 114: TestString
114/149 Test #114: TestString ...............................   Passed    0.01 sec
        Start 115: TestUnicodeConversion
115/149 Test #115: TestUnicodeConversion ....................   Passed    0.01 sec
        Start 116: TestWtsApiEnumerateProcesses
116/149 Test #116: TestWtsApiEnumerateProcesses .............   Passed    0.01 sec
        Start 117: TestWtsApiEnumerateSessions
117/149 Test #117: TestWtsApiEnumerateSessions ..............   Passed    0.01 sec
        Start 118: TestWtsApiQuerySessionInformation
118/149 Test #118: TestWtsApiQuerySessionInformation ........   Passed    0.01 sec
        Start 119: TestWtsApiSessionNotification
119/149 Test #119: TestWtsApiSessionNotification ............   Passed    0.01 sec
        Start 120: TestWtsApiShutdownSystem
120/149 Test #120: TestWtsApiShutdownSystem .................   Passed    0.01 sec
        Start 121: TestWtsApiWaitSystemEvent
121/149 Test #121: TestWtsApiWaitSystemEvent ................   Passed    0.01 sec
        Start 122: TestDsMakeSpn
122/149 Test #122: TestDsMakeSpn ............................   Passed    0.01 sec
        Start 123: TestSmartCardListReaders
123/149 Test #123: TestSmartCardListReaders .................   Passed    0.01 sec
        Start 124: TestNtCurrentTeb
124/149 Test #124: TestNtCurrentTeb .........................   Passed    0.01 sec
        Start 125: TestClipboardFormats
125/149 Test #125: TestClipboardFormats .....................   Passed    0.02 sec
        Start 126: TestIntrinsics
126/149 Test #126: TestIntrinsics ...........................   Passed    0.01 sec
        Start 127: TestTypes
127/149 Test #127: TestTypes ................................   Passed    0.01 sec
        Start 128: TestRdTkNinePatch
128/149 Test #128: TestRdTkNinePatch ........................   Passed    0.01 sec
        Start 129: TestRingBuffer
129/149 Test #129: TestRingBuffer ...........................   Passed    0.20 sec
        Start 130: TestPodArrays
130/149 Test #130: TestPodArrays ............................   Passed    0.04 sec
        Start 131: TestEncodedTypes
131/149 Test #131: TestEncodedTypes .........................   Passed    0.68 sec
        Start 132: TestAddinArgv
132/149 Test #132: TestAddinArgv ............................   Passed    0.04 sec
        Start 133: TestCommonAssistance
133/149 Test #133: TestCommonAssistance .....................   Passed    0.07 sec
        Start 134: TestKnownHosts
134/149 Test #134: TestKnownHosts ...........................   Passed    0.06 sec
        Start 135: TestBase64
135/149 Test #135: TestBase64 ...............................   Passed    0.04 sec
        Start 136: TestVersion
136/149 Test #136: TestVersion ..............................   Passed    0.04 sec
        Start 137: TestSettings
137/149 Test #137: TestSettings .............................   Passed    1.61 sec
        Start 138: TestFreeRDPRegion
138/149 Test #138: TestFreeRDPRegion ........................   Passed    0.04 sec
        Start 139: TestFreeRDPCodecZGfx
139/149 Test #139: TestFreeRDPCodecZGfx .....................   Passed    0.04 sec
        Start 140: TestFreeRDPCodecPlanar
140/149 Test #140: TestFreeRDPCodecPlanar ...................   Passed    0.12 sec
        Start 141: TestFreeRDPCodecCopy
141/149 Test #141: TestFreeRDPCodecCopy .....................   Passed    0.43 sec
        Start 142: TestFreeRDPCodecClear
142/149 Test #142: TestFreeRDPCodecClear ....................   Passed    0.05 sec
        Start 143: TestFreeRDPCodecInterleaved
143/149 Test #143: TestFreeRDPCodecInterleaved ..............   Passed    0.10 sec
        Start 144: TestFreeRDPCodecProgressive
144/149 Test #144: TestFreeRDPCodecProgressive ..............   Passed    0.12 sec
        Start 145: TestFreeRDPCodecRemoteFX
145/149 Test #145: TestFreeRDPCodecRemoteFX .................   Passed    0.05 sec
        Start 146: TestClientRdpFile
146/149 Test #146: TestClientRdpFile ........................   Passed    0.07 sec
        Start 147: TestClientChannels
147/149 Test #147: TestClientChannels .......................   Passed    0.06 sec
        Start 148: TestClientCmdLine
148/149 Test #148: TestClientCmdLine ........................   Passed    0.11 sec
        Start 149: TestSDLPrefs
149/149 Test #149: TestSDLPrefs .............................   Passed    0.01 sec

99% tests passed, 1 tests failed out of 149

Total Test time (real) =  10.12 sec

The following tests FAILED:
         68 - TestNCryptSmartcard (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /opt/freerdp-build/FreeRDP/obj-x86_64-linux-gnu && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
dh_auto_test: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=4 ninja test returned exit code 1
make[1]: *** [debian/rules:81: override_dh_auto_test] Fehler 1
make[1]: Verzeichnis „/opt/freerdp-build/FreeRDP“ wird verlassen
make: *** [debian/rules:60: build] Fehler 2
dpkg-buildpackage: Fehler: Unterprozess debian/rules build lieferte Exitstatus 2
```

**Comment by akallabeth** [comment]
@xBr0th3rx ok, dependency library leaks some memory, false positive.

change the following in `packaging/deb/freerdp-nightly/rules`:
```
override_dh_auto_test:
       dh_auto_test
```

to 
```
override_dh_auto_test:
```

this will disable running the unit tests during build.

**Comment by xBr0th3rx** [comment]
So I have installed the package.

If of my 3 monitors I use the one in the middle as main monitor and connect and set the option that monitor 1. and 2. are used (2,0) then it does not start.
3-monitor-middle-primary

```
[11:52:37:507] [1586782:0018365e] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: This build is using [runtime-check] build options:
[11:52:37:507] [1586782:0018365e] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[11:52:37:507] [1586782:0018365e] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: 
[11:52:37:507] [1586782:0018365e] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: [runtime-check] build options might slow down the application
[11:52:37:507] [1586782:0018365e] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
[11:52:37:508] [1586782:0018365e] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: /cert-ignore is deprecated, use /cert:ignore instead
[11:52:37:691] [1586782:00183664] [ERROR][com.freerdp.settings] - [monitor_operlaps]: Mulitimonitor mode requested, but local layout has gaps or overlapping areas!
[11:52:37:691] [1586782:00183664] [ERROR][com.freerdp.settings] - [monitor_operlaps]: Please reconfigure your local monitor setup so that there are no gaps or overlapping areas!
[11:52:37:691] [1586782:00183664] [ERROR][com.freerdp.core] - [freerdp_connect_begin]: ERRCONNECT_PRE_CONNECT_FAILED [0x00020001]
[11:52:37:691] [1586782:00183664] [ERROR][com.freerdp.core] - [freerdp_connect_begin]: freerdp_pre_connect failed: CLIENT_STATE_PRECONNECT_PASSED
```
However, if I only specify fullscreen so that it runs on all monitors, it works and I have Windows Session on 3 monitors.
[wints2012.kikxxl.corp03-11-55.txt](https://github.com/user-attachments/files/17991670/wints2012.kikxxl.corp03-11-55.txt)

But if I use the left monitor as the main monitor:
3-monitor-left-primary

Can I use the left and center monitors for Windows session without an error message:
[wints2012.kikxxl.corp03-11-57.txt](https://github.com/user-attachments/files/17991726/wints2012.kikxxl.corp03-11-57.txt)

**Comment by akallabeth** [comment]
@xBr0th3rx please list for all configurations the output of `xfreerdp /list:monitor` (and if they work or not, and if not the error log)

**Comment by akallabeth** [comment]
@xBr0th3rx ok, this means the fix works.
for the rest:
* create an issue with the requested details from above

**Comment by xBr0th3rx** [comment]
> @xBr0th3rx please list for all configurations the output of `xfreerdp /list:monitor` (and if they work or not, and if not the error log)

With Middle main Monitor:
```
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: This build is using [runtime-check] build options:
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: 
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: [runtime-check] build options might slow down the application
[12:48:54:676] [1623377:0018c551] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
      * [0] 1920x1080   +1920+0
        [1] 1920x1080   +3840+0
        [2] 1920x1080   +0+0
```


With Left main Monitor:
```
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: This build is using [runtime-check] build options:
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: 
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: [runtime-check] build options might slow down the application
[12:50:02:075] [1623951:0018c78f] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
      * [0] 1920x1080   +0+0
        [1] 1920x1080   +3840+0
        [2] 1920x1080   +1920+0
```

**Comment by xBr0th3rx** [comment]
But I still don't quite understand why it is relevant where the main monitor is set.

I have a script for us that checks the order of the monitors and determines the order +0+0 is always on the left and +1920+0 would be the center and +3840+0 would be on the right.

This gives the users a selection where they can say I want to work on monitor 1 & 2. The users know that if they were to select 1 & 3, for example, this would move across the middle and that doesn't work because 2 is in between.

Then we also have desktop workstations where they have 2 monitors at the bottom and 1 at the top and then they select, for example, both at the bottom together or just one at the top. The users know that they can only do multimonitor if the Windows session windows are next to each other and not across or in the middle.

It didn't matter whether the main monitor was on the left, center or right, what I passed as monitors counted.

Now it is the case that if I do not have the main monitor on the left, the /monitors: seems to be misinterpreted because it thinks that the monitors overlap, which they do not do at all.

In my place with main monitor in the center and “/opt/freerdp-nightly/bin/xfreerdp3 /list:monitor”:         
   [2] 1920x1080 +0+0
* [0] 1920x1080 +1920+0
   [1] 1920x1080 +3840+0

I know if I want to have monitors 1 & 2 I have to pass the option /monitors: 2,0 but this fails because the monitors supposedly overlap or are not properly aligned, which is not true.

Log: 
[log.txt](https://github.com/user-attachments/files/17992598/log.txt)

**Comment by akallabeth** [comment]
@xBr0th3rx your local monitor layout and the thing known as `monitor layout` in `RDP` are not the same thing.
I´ve added some error logging so you can see which layout `RDP` has
as mentioned, this pr only fixes a bug in checking the requirements, it does not magically implement what was not there before

**Comment by akallabeth** [comment]
@xBr0th3rx please add more details to your comments.
this PR did address the bug in the `dijkstra` implementation, improved unit tests and log messages.

your comments do mix these and add some other stuff - and then you start with a completely different scenario without proper details
the only question that should be answered here is: does the one setup from yesterday with 3 monitors attached and order `0 2 1`  (e.g. 0 connected to 1 connected to 2 but ordered differently in the list) work. (it does, now part of the unit test).

anyway, merging this now as it improves the current implementation and adds some more details about error reporting.

anything else, please create *one* issue for *one* bug and do not start to mix them together during discussion (the monitor layout thing is different from `/monitors:0,2` not working as expected for example)

**Pull request merged**
