### PR TITLE
Mac os ssl warning fix

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by mfleisz** [comment]
+1

**Comment by hardening** [comment]
@akallabeth I guess it will only build with recent of MacOS X then ?

**Comment by akallabeth** [comment]
@hardening Should only depend on the OpenSSL version used or do you know another reason for this removed const argument?

**Comment by hardening** [comment]
@akallabeth yeah you're right, so the fix should be that the #ifdef would be a #if openssl_version > XXX isn't it ?

**Comment by akallabeth** [comment]
@hardening  Just checked, this (old) API applies to all OpenSSL versions < 1.0.0. But neither gcc nor clang complain about the const argument when compiling against 0.9.8zh

**Comment by akallabeth** [comment]
@hardening Ok, clang actually does complain. Looks like my cache was not up to date, forget the comment above.

**Comment by mfleisz** [comment]
Any objections on merging this one?

**Comment by hardening** [comment]
+1

**Pull request merged**
