### PR TITLE
Color conversion improvement

### PR DESCRIPTION
**Pull request by akallabeth**
This (quite large) pull request tries to achieve the following:
* Unify color conversion to allow simple switching between local display formats
* Add support for most commonly used formats to all decoding functions
* Local framebuffer always has local color format
* As a result of having to touch quite a lot of internals refactor the API to expose only required functions

This pull is currently work in progress, but already quite far.
Remaining issues (as currently known)
* ~~GDI: CMD scroll bar switches to black when scrolling~~
* GDI: Font Cache does not work well
* Windows Client hardware GDI color issues Looks like this was not working for a long time, not fixing in this pull
* ~~iOS client needs testing~~
* ~~Android client needs testing~~
* ~~Wayland client needs testing~~

Please feel free to test out this pull and give feedback when appropriate.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@realjiangms Could you have a look at https://github.com/akallabeth/FreeRDP/tree/color_conversion_fix_v6 ? I've rebased this branch on current master including your encoder fixes, so it would be good to know I did not break them.

**Comment by ondrejholy** [comment]
Hmm, I've tried color_conversion_fix_v6 and color_conversion_fix_v4 branches, and xfreerdp segfaults, or exits with various errors on both of them...

There are outputs from some my tries:
```
$ client/X11/xfreerdp /u:U /p:P /gdi:sw /v:V # color_conversion_fix_v4
[11:15:04:649] [6228:6228] [INFO][com.freerdp.utils] - Registering signal hook...
[11:15:04:881] [6228:6229] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[11:15:04:881] [6228:6229] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[11:15:05:652] [6228:6229] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap index: 0x7FFF
Segmentation fault (core dumped)

$ client/X11/xfreerdp /u:U /p:P /gdi:hw /v:V # color_conversion_fix_v4
[11:15:10:156] [6267:6267] [INFO][com.freerdp.utils] - Registering signal hook...
[11:15:10:378] [6267:6268] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[11:15:10:378] [6267:6268] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core.orders] - Invalid Primary Drawing Order (0x53)
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core.fastpath] - FASTPATH_UPDATETYPE_ORDERS - fastpath_recv_orders()
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[11:15:11:110] [6267:6268] [INFO][com.freerdp.client.x11] - Network disconnect!
[11:15:11:110] [6267:6268] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

$ client/X11/xfreerdp /u:U /p:P /gdi:sw /v:V # color_conversion_fix_v6
[10:31:31:592] [1956:1956] [INFO][com.freerdp.utils] - Registering signal hook...
[10:31:32:948] [1956:1957] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[10:31:32:948] [1956:1957] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[10:31:32:564] [1956:1957] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x0200
[10:31:32:564] [1956:1957] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap index: 0x0900
[10:31:32:564] [1956:1957] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap index: 0xBC0C
[10:31:32:564] [1956:1957] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x0016
Segmentation fault (core dumped)

$ client/X11/xfreerdp /u:U /p:P /gdi:hw /v:V # color_conversion_fix_v6
[10:31:39:187] [2027:2027] [INFO][com.freerdp.utils] - Registering signal hook...
[10:31:39:525] [2027:2028] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[10:31:39:525] [2027:2028] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  61 (X_ClearArea)
  Value in failed request:  0xe
  Serial number of failed request:  3753
  Current serial number in output stream:  5340
```
So not sure this patches are ready to merge. Don't you have any idea why?

**Comment by akallabeth** [comment]
@ondrejholy What server are you testing with? Tried against MS (xp up to 10) and no issues so far. Maybe I'm missing something?

**Comment by ondrejholy** [comment]
I tested against MS Windows Server 2008 SP2. It seems that some of those problems I am able to reproduce only in gdb and it doesn't happen always. I see the problems with /gdi:sw only on 2008 currently (it seems it works properly on XP and 2012). I can reproduce the problems with /gdi:hw also on Windows XP (it seems it works properly on 2012).

Apart from that I also see various glitches with /bpp:8 on XP and 2008 (e.g. weird color of icons/images, black stripes over the screen...).

**Comment by akallabeth** [comment]
@ondrejholy Ah, ok. Don't have 2008 here :/ As for the weired color stuff, could you try with ```-glyph-cache```? That one I was still not able to fix properly :/

**Comment by akallabeth** [comment]
@ondrejholy Ah, and could you try to compile with ```-DWITH_SANITIZE_ADDRESS=ON```, then a stack trace with memory and thread information is printed when a memory corruption occurs.

**Comment by ondrejholy** [comment]
Hmm, the crashes and failures were caused by the configuration of my server and they are not specific to this pull request. The configuration was made by "IIS Crypto" tool using the "Best Practices" button. IIS Crypto is a tool that allows to enable or disable protocols, ciphers, hashes... so I am sorry for spamming this thread, I will file a separate bug with stacktraces...

I still see `X Error of failed request:  BadValue` with /gdi:hw on this branch only...

`-glyph-cache` fixes some glitches, but I still see some, e.g.:

screenshot from 2016-08-26 16-32-52

**Comment by ondrejholy** [comment]
Try your branch on X11 server with `DefaultDepth 16`, it crashes almost in all cases and has wrong colors if does not crash anyway!

I've tried your branch on big endian, good job! Colors are still wrong, but it seems that all the color handling is endian-independent. See my patches on top of yours `color_conversion_fix_v6`:
https://github.com/ondrejholy/FreeRDP/commits/endianness3

I can't test the 16/15bpp fixes, because it doesn't work correctly on little endian also, but it fixes colors for 32/24bpp on big endian.

**Comment by akallabeth** [comment]
@ondrejholy Interesting. Tried against xrdp (debian jessie, x86_64) and did not have any crashing issues. The mouse pointer was a black rectangle though.

**Comment by akallabeth** [comment]
@ondrejholy Ok, just figured it out. X11 cursor is always 32 bit RGBA data, that's why it was crashing.

**Comment by realjiangms** [comment]
OK I'll try the new v6 branchfrom android-------- 原始邮件 --------主题：Re: [FreeRDP/FreeRDP] Color conversion improvement (#3450)发件人：akallabeth 收件人：FreeRDP/FreeRDP 抄送："Jiang, Zihao" ,Mention @realjiangms Could you have a look at https://github.com/akallabeth/FreeRDP/tree/color_conversion_fix_v6 ? I've rebased this branch on current master including your encoder fixes, so it would be good to know I did not break them.

**Pull request closed without merging**
