### PR TITLE
winpr: Updates time zones and fixes bias values

### PR DESCRIPTION
**Pull request by rjcorrig**
Updates time zone information database in libwinpr/timezone/timezone.c to Microsoft's December 2015 update. This was critical as many of my client stations incorrectly jumped forward to US Daylight Savings Time a week early.

Corrects casing in the scripts/TimeZones.cs generator script to fix build errors when compiling libwinpr/timezone/timezone.c .

Changes Bias values from unsigned to signed integer to properly capture negative bias values. Bias should be the number of minutes to add to local time to get to UTC. Bias has the opposite sign value of glibc's tm_gmtoff and .NET's BaseUtcOffset. For example, America/New_York should have a Bias of 300 and Asia/Katmandu should have a bias of -345. The results can be verified by issuing "w32tm /tz" at a command prompt inside the RDP connection.

In cases where the time zone cannot be looked up in the database, the client attempts to compute the proper Bias value from tm_gmtoff so that the client's local time appears inside the RDP connection. Since this is not strict GMT, the client time zone is labeled "Client Local Time" to avoid confusion.

### CODE REVIEW

**Comment by rjcorrig** [comment]
If accepted, this patch addresses issue #3198

**Comment by akallabeth** [comment]
@rjcorrig Could you rebase your pull to master to get rid of the many merges?

**Comment by rjcorrig** [comment]
Yes, sorry. I'm new at this :-)

**Comment by rjcorrig** [comment]
Better?

**Comment by akallabeth** [comment]
@rjcorrig Much better. @bmiklautz What do you think about this?

**Comment by mfleisz** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@rjcorrig If you spend ```winpr_detect_windows_time_zone()``` a ```void ``` argument a +1 from me ;)

**Comment by rjcorrig** [comment]
Done!

**Comment by akallabeth** [comment]
and merged!

**Comment by rjcorrig** [comment]
Thanks! I'll keep an eye out for future time zone updates from Microsoft and submit patches as needed. Glad to help!

**Comment by bmiklautz** [comment]
@rjcorrig nice one thanks!

**Pull request merged**
