### PR TITLE
Fixed mixed declarations and code.

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by mfleisz** [comment]
+1

**Comment by realjiangms** [comment]
The mixed declarations and code should cause compile failure on win32. I'm curious why I didn't have this reported when I compile the FreeRDP on windows without your fix.

**Comment by realjiangms** [comment]
My local copy don't have the line 'int ret = 0;'. My workspace may be out-of-date.
This PR may need to be merged ASAP as the issue it resolved may cause compile error on win32

**Pull request merged**
