### PR TITLE
Fix for rdpsnd mac memory leaks

### PR DESCRIPTION
**Pull request by lemonmojo**
The macOS implementation of the rdpsnd channel had some serious memory leaks which this PR fixes.
* In `rdpsnd_mac_play`, `AVAudioFormat` was only released when the creation of `AVAudioPCMBuffer` failed and the buffer was actually never(!) released.
* Autorelease Pools were missing in `rdpsnd_mac_open`, `rdpsnd_mac_close`, `rdpsnd_mac_set_volume`, `rdpsnd_mac_start` and `rdpsnd_mac_play` where ObjC methods were called which caused autoreleased objects to be created behind the scenes.

Just FYI: To check for missing autorelease pools, just run xfreerdp or any other client with the environment variable `OBJC_DEBUG_MISSING_POOLS` set to `YES`. On my machine, this yielded log output like this as soon as I started sound playback in the remote session:

```
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacb70 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010b5fc0 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacab0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac920 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac940 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010acc80 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010acd80 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac960 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacb10 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacb40 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacae0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacba0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac980 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac9a0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ad080 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacbd0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacc00 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacc30 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacc60 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ad2a0 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacc90 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eaccc0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eaccf0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac9c0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacd20 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacd50 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacd80 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacdb0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacde0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ac9e0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eace10 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eace40 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eace70 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacea0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eaced0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacf00 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacf30 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600000595000 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacf90 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacfc0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacff0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead020 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead050 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead080 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead0b0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead0e0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead110 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead140 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead170 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead1a0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead1d0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead200 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead230 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead260 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead290 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead2c0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead2f0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead320 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead350 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead380 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead3b0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead3e0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead410 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead440 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead470 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead4a0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead4d0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead500 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead530 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead560 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead590 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead5c0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead5f0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead620 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead650 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead680 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead6b0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead6e0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead710 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead740 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead770 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead7a0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead7d0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead800 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead830 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead860 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead890 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead8c0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead8f0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead920 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead950 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead980 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead9b0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001ead9e0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eada10 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eada40 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eada70 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadaa0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadad0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadb00 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadb30 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadb60 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010ad580 of class NSTaggedPointerStringCStringContainer autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eacf60 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadb90 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600001eadbc0 of class __NSCFString autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x7f93cd0072a0 of class AUHALOutputUnit autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000010a4700 of class ATDefaultDeviceAggregate autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600000584100 of class __NSMallocBlock__ autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x60000108e220 of class AVAudioChannelLayout autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033a0190 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033a0190 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600000595140 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x7f93cd109270 of class AUAudioUnitV2Bridge autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b50c0 of class __NSMallocBlock__ autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5080 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033908c0 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x7f93cd10b5e0 of class AUAudioUnitV2Bridge autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5740 of class __NSMallocBlock__ autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600003e85580 of class AUParameter autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600003390a00 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600000595140 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600000595140 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5080 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5540 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5540 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5540 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600003e96e80 of class AUParameter autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5540 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5080 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600003e96e80 of class AUParameter autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600002ba8b60 of class AUParameterTree autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x600003e97300 of class AUParameter autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033a0190 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033b4eb0 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033a0190 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033b0d70 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033b1090 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000033a0190 of class AVAudioFormat autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000034b0ea0 of class AVAudioTime autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003bbd000) Object 0x6000034b0e40 of class AVAudioTime autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003c40000) Object 0x600000595140 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003c40000) Object 0x6000005b5780 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003c40000) Object 0x6000005b5540 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003c40000) Object 0x6000005b5080 of class AUV2BridgeBusArray autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
objc[3094]: MISSING POOLS: (0x700003c40000) Object 0x6000010a4700 of class ATDefaultDeviceAggregate autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
```

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM.
Would suggest a force push with a proper rebase to `master` though to squash the merge commits.

Anyway, thank you for the fix and the hint on how to debug.

Most likely a backport will be in order for this, correct?

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@lemonmojo is `audin` channel not affected by this? I assume it will feature similar shortcomings?

**Comment by lemonmojo** [comment]
@akallabeth 
* Thx for merging and sorry for the merge commits. I'll look out for them with the next PR.
* Yes, this should be backported.
* I was planning to investigate the `audin` channel separately and will also create a separate PR if necessary.
* I ran some quick tests against the `audin` channel with `OBJC_DEBUG_MISSING_POOLS` enabled and only saw a single occurrence of a missing pool while recording for about a minute. I guess since there's much less ObjC involved it's not that big of a deal but again, I'll look at that separately.

**Pull request merged**
