### PR TITLE
This array is so big that it eats whole stack for the thread and makes

### PR DESCRIPTION
**Pull request by psumbera**
the process dump core on some systems (e.g. Solaris).

### CODE REVIEW

**Comment by bmiklautz** [comment]
@psumbera what about increasing the stack size?

**Comment by psumbera** [comment]
I was thinking about increasing stack size. But didn't went into details yet. It would have to be done probably during pthread_create call. Where should I have look?

**Comment by psumbera** [comment]
It seems that I can add stack size to CreateThread call in x11_shadow_subsystem_start and it helps. But is it sane to have on stack:

BOOL grid[1024][1024];

which is 4MB? Where stack according pthread_create man page on Solaris has by default just 2MB.

**Comment by hardening** [comment]
-1
setting this big array as static is a non-sense. The array is allocated on the stack to prevent constant malloc / free, but perhaps it would be the safest thing to do...

**Comment by nfedera** [comment]
Why not simply delete it. This variable does not seem to be used ;)

**Comment by nfedera** [comment]
Also cols[1024] is only used for some disabled debug code ( by using if(0) ... sick) .
This should be en/disabled using a define.
And instead of using 4 bytes (BOOL) for one flag this shoud be changed to use simple bit magic which would reduce the size down to 1/32.

**Comment by nfedera** [comment]
@psumbera Are you up to this task?

**Comment by psumbera** [comment]
Nice! I can do removal part tomorrow. Not sure about the rest now. But if you can do both I wouldn't object ;-)

**Comment by bmiklautz** [comment]
@nfedera nice solution!

**Comment by psumbera** [comment]
Please see my new commit. I didn't play with bit magic though...

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
+1

**Pull request merged**
