### PR TITLE
fix not accepted mask: after /gfx-h264:

### PR DESCRIPTION
**Pull request by ifsdk**

### CODE REVIEW

**Comment by ifsdk** [comment]
this should make work mask: not only after /gfx: but also there as the code suggests. if useless then the code cheking for mask should be removed there.

**Comment by akallabeth** [comment]
@ifsdk no, it just moves a check down... This is done in a loop, order does not matter...

**Comment by ifsdk** [comment]
check the command line, it doesn't work as the check point for avc420 there aborts

**Comment by ifsdk** [comment]
so xfreerdp /gfx-h264 works only with :avc{444,420} but not with :mask in any place there

**Comment by akallabeth** [comment]
Ah, I see, the check is wrong. but so is your pr ;)
Closing and creating a new one.

**Comment by ifsdk** [comment]
just for clarity my pr isn't wrong, thou it would be better to delete the mask code there

**Pull request closed without merging**
