### PR TITLE
[channels,rdpdr] fix state check

### PR DESCRIPTION
**Pull request by fujames1**

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM,
nice catch!

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@fujames1 thank you for the pull request.
could you run `git clang-format` on your changes please? (you can `git commit --amend` and `git push --force` to replace your current commit, so that it passes the ci checks.

**Comment by fujames1** [comment]
hi @akallabeth,  I reformatted the code and force-pushed.

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Review by akallabeth — APPROVED** [review]
LGTM, thx!

**Pull request merged**
