### PR TITLE
Added audin support for mac os.

### PR DESCRIPTION
**Pull request by akallabeth**
* Basic microphone redirection for MacOS X (may also work with iOS, but not tested)
* Currently only ```PCM``` format is supported, others need some work.

### CODE REVIEW

**Comment by mfleisz** [comment]
+1

**Comment by hardening** [comment]
Looks good AFAI know the subject.

Just a remark: the patch defines WAVE_FORMAT_AAC_MS but never use it

**Comment by akallabeth** [comment]
@hardening Added the format define for later use.
@awakecoding @bmiklautz @hardening any objections to this pull?

**Comment by awakecoding** [comment]
can't hurt, as it wasn't supported before. no objections.

**Pull request merged**
