### PR TITLE
Audin winmm

### PR DESCRIPTION
**Pull request by Pollux42**
Small fixes about audin and winmm.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test
@Pollux42 thanks you for the pr, but could you please add a description which issue this fixes (and how to test)?

**Comment by Pollux42** [comment]
@akallabeth Indeed.

In a recent commit, in audin_winmm_set_format, you have forced the number of channels to one. But this should also be done in audin_winmm_format_supported so the dsp is properly initialized to do a proper channel mix.
This is the purpose of the first commit.

Unfortunately, this still does not work because waveInOpen refuse the format if the channel number and the block alignment are not consistent.
So this is the purpose of the second commit.

The last commit makes sure we always first try the same number of channels for each sample rate attempt. (plus some refactoring)

**Review by akallabeth — CHANGES_REQUESTED** [review]
The changes in `channels/audin/client/audin_main.c` might work for you, but you change these windows backend limitations for every supported platform.

**Comment by akallabeth** [comment]
Ok, refactored your pr slightly and created a new pr.
Thank you for your contribution, indeed a nice bugfix!

**Comment by Pollux42** [comment]
> The changes in channels/audin/client/audin_main.c might work for you, but you change these windows backend limitations for every supported platform.

I did not report those windows limitations for every supported platform. All changes I did in `channels/audin/client/audin_main.c` should have no negative impact. Which change in this file makes you suspicious?

**Comment by akallabeth** [comment]
@Pollux42 I should stop reviewing before coffee, formulated the issue badly.

**Pull request closed without merging**
