### PR TITLE
Clear openssl error queue after connecting with nla

### PR DESCRIPTION
**Pull request by fifthdegree**
This is necessary when using pkcs11 due to a bug in openssl where errors emitted by unrelated operations can cause BIO_should_retry() to report false negatives (see [Issue #11889](https://github.com/openssl/openssl/issues/11889))

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
Just wondering if the correct fix would not be to do a `ERR_clear_error()` before all `SSL_Read` / `SSL_Write` calls ? That's what suggest the openSSL post...

**Comment by akallabeth** [comment]
@fifthdegree could you run `git clang-format` on your commit? looks like formatting is not in required style.
as for what @hardening said, that might actually be a good idea

**Comment by fifthdegree** [comment]
I think I got all of them; let me know if I missed anything

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@fifthdegree you did miss a few, but I´ve pushed these changes too.
left out the ones in a `BIO` method as they call recursivly

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by akallabeth — APPROVED** [review]

**Pull request merged**
