### PR TITLE
Moved wayland cursor handling to seat.

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
confirmed by @hendwolt

**Comment by hendwolt** [comment]
I'm sorry, but I have to withdraw my confirmation somewhat. Today I connected with wlfreerdp including this patch to an Windows7 Prof. instance instead of my usual test target (Windows10 Insider Preview) and got another  crash:
` wlfreerdp /u:<user> /d:<domain> /f +clipboard -wallpaper /v:192.168....
[16:12:12:892] [8575:8575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[16:12:12:892] [8575:8575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[16:12:12:892] [8575:8575] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[16:12:18:637] [8575:8575] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRA32
[16:12:18:637] [8575:8575] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[16:12:18:640] [8575:8575] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[16:12:18:668] [8575:8585] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime text/plain
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime text/html
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime TARGETS
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime MULTIPLE
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime TIMESTAMP
[16:12:19:221] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime SAVE_TARGETS
[16:12:19:880] [8575:8575] [INFO][com.freerdp.client.wayland] - Logon Error Info SESSION_ID [LOGON_MSG_SESSION_CONTINUE]
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime text/plain
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime text/html
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime TARGETS
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime MULTIPLE
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime TIMESTAMP
[16:12:36:742] [8575:8575] [INFO][com.freerdp.client.wayland.cliprdr] - client announces mime SAVE_TARGETS
[16:14:47:890] [8575:8575] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
[16:14:47:890] [8575:8575] [ERROR][com.freerdp.core.rdp] - rdp_recv_tpkt_pdu: rdp_recv_deactivate_all() fail
[16:14:47:890] [8575:8575] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
free(): corrupted unsorted chunks
Abgebrochen (Speicherabzug geschrieben)
`

backtrace:
`Program terminated with signal SIGABRT, Aborted.
#0  0x00007f48f1c48d8b in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f48f1c48d8b in raise () from /lib64/libc.so.6
#1  0x00007f48f1f0c0a0 in fatal_handler (signum=6) at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/libfreerdp/utils/signal.c:67
#2  <signal handler called>
#3  0x00007f48f1c48d8b in raise () from /lib64/libc.so.6
#4  0x00007f48f1c32549 in abort () from /lib64/libc.so.6
#5  0x00007f48f1c8b287 in __libc_message () from /lib64/libc.so.6
#6  0x00007f48f1c91a4c in malloc_printerr () from /lib64/libc.so.6
#7  0x00007f48f1c93597 in _int_free () from /lib64/libc.so.6
#8  0x00007f48f21a10f3 in UwacSeatDestroy (s=0x564295536530) at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/uwac/libuwac/uwac-input.c:975
#9  0x00007f48f219f455 in UwacCloseDisplay (pdisplay=0x5642954db830) at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/uwac/libuwac/uwac-display.c:540
#10 0x000056429495fcff in wlf_client_free (instance=<optimized out>, context=<optimized out>)
    at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/client/Wayland/wlfreerdp.c:520
#11 0x00007f48f1f63d57 in freerdp_context_free (instance=instance@entry=0x5642954db150)
    at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/libfreerdp/core/freerdp.c:754
#12 0x00007f48f21b432f in freerdp_client_context_free (context=<optimized out>) at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/client/common/client.c:110
#13 0x000056429495f709 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/freerdp-2.0.0~git20190213-1.1.x86_64/client/Wayland/wlfreerdp.c:582
`

**Comment by akallabeth** [comment]
@hendwolt Ok, used unsafe iteration when destroying the list elements. hope it is fixed now.

**Comment by hendwolt** [comment]
@akallabeth: I did a few tests with the new version and got no crashes so far. I keep on testing ...

**Pull request merged**
