### PR TITLE
Update Strings for Simplified Chinese 

### PR DESCRIPTION
**Pull request by sr093906**
## This is how are pull requests handled by FreeRDP
1. Every new pull request needs to build and pass the unit tests at https://ci.freerdp.com
1. At least 1 (better two) people need to review and test a pull request and agree to accept

## Preparations before creating a pull
* Rebase your branch to current master, no merges allowed!
* Try to clean up your commit history, group changes to commits
* Check your formatting! A _clang-format_ script can be found at ```.clang-format```
  * The cmake target ```clangformat``` reformats the whole codebase
* Optional (but higly recommended)
  * Run a clang scanbuild before and after your changes to avoid introducing new bugs
  * Run your compiler at pedantic level to check for new warnings

## To ease accepting your contribution
* Give the pull request a proper name so people looking at it have an basic idea what it is for
* Add at least a brief description what it does (or should do :) and what it's good for
* Give instructions on how to test your changes
* Ideally add unit tests if adding new features

## What you should be prepared for
* fix issues found during the review phase
* Joining IRC _#freerdp_ to talk to other developers or help them test your pull might accelerate acceptance
* Joining our mailing list <freerdp-devel@lists.sourceforge.net> may be helpful too.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@sr093906 Thank you for the updated translations.
Could you please remove the `translatable=false` strings you added?
Also a quick check with `google translate` got a weird translation for `settings_hostname`, does google need an update?

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by sr093906** [comment]
> hostname

@akallabeth removed such strings. hostname means "主机名" in Simplified Chinese. What do you expect?

**Comment by sr093906** [comment]
image

**Comment by akallabeth** [comment]
@sr093906 ok, funny. for me google translates it to `CPU name`, so google indeed needs an update :)

**Review by akallabeth — APPROVED** [review]

**Comment by akallabeth** [comment]
@sr093906 again, thank you for this and sorry for me being lost in translation :)

**Comment by sr093906** [comment]
@akallabeth Welcome. I just feel strange to that.

**Pull request merged**
