### PR TITLE
Fixes for software GDI issues #2732 and #2137

### PR DESCRIPTION
**Pull request by giox069**

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by nfedera** [comment]
@giox069 thanks! The fix seems ok, but a proper solution involves solving much more return value weirdness. I'll see if I can do that come up with something until tomorrow.
So Admins don't merge yet please.

**Comment by giox069** [comment]
@nfedera thank you. Don't forget the fix/commit I added for issue #2137, it has nothing to do with return values, just a wrong sign extension calculation.

**Comment by nfedera** [comment]
@giox069 I'll merge this PR and rebase mine afterwards

**Comment by bmiklautz** [comment]
@giox069 @nfedera thx!

**Pull request merged**
