### PR TITLE
fix async input.

### PR DESCRIPTION
**Pull request by realjiangms**
The async-input is not really async. We create a thread to peek input event from X, but the event is pushed into FREERDP_INPUT_MESSAGE_QUEUE as message and FREERDP_INPUT_MESSAGE_QUEUE is processed in main client thread. Therefore the input event is still processed in main client thread actually.
The fix make the message also be processed in input thread.

The original issue is discussed in #2338. When we have heavy image update, the input event will hardly  get a chance to be handled. In this case we may want to use async input but it does't actually work in this case.

But I'm not sure if I understand the purpose of async input correctly.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@realjiangms there are different "types" of async (input, update, channel, transport). What did you test your pull request with?

**Comment by realjiangms** [comment]
@bmiklautz I tested with +async-input, without any other 'async' inputs. The fix proposed is for +async-input

Actually I agree that this fix is not really necessary. The issue reported in #2338 could be resolved by using +async-transport or +async-update instead of +async-input. (+async-update may finally panic with out-of-memory as we have unlimited update message queue) 

I raise this pull-request just for discussion on the 'meaning' of async-input, and the difference in detail behavior for 'async-input' between (android/X11) and (Windows/Mac).

These days I kept trying +async-transport to test if it could workaround issue in #2338, unfortunately I found another race condition which could cause thread hung.
After several day's investigation, I've just found the root cause and I'll reorganize wording at this weekend.to report it

**Comment by bmiklautz** [comment]
@realjiangms thanks for the information.

**Comment by realjiangms** [comment]
I would want to close this pull request as it's not really necessary. The issue could be resolved by using +async-transport instead of +async-input. We don't even need +async-input in x11 client.

The hung issue mentioned in previous note is described in #2519

**Comment by realjiangms** [comment]
The hung issue is completely fixed by #3364

**Pull request closed without merging**
