### PR TITLE
Fix leaks in certificate and identity handling

### PR DESCRIPTION
**Pull request by bmiklautz**
Thanks to @akallabeth for finding/fixing the nla_identity_free.

### CODE REVIEW

**Comment by akallabeth** [comment]
+1

**Comment by mfleisz** [comment]
+1

**Comment by nfedera** [comment]
+1 and just two non-blocking remarks
- from a security point of view it might make sense that nla_identity_free clears the user, password, domain blobs before releasing the memory
- nla_identity_free() frees a SEC_WINNT_AUTH_IDENTITY and seems to me independent of nla (not sure if that is true). However, if that's the case it might be good to rename it to sec_winnt_auth_identity_free().

**Comment by bmiklautz** [comment]
@nfedera the password and username is cleared now. Regarding the function name you are right it's not really suiting but all functions are called nla_ in this file and it's a static function therefore I think it's ok.

**Comment by bmiklautz** [comment]
@freerdp-bot test it right this time!

**Comment by nfedera** [comment]
Another +1 now

**Pull request merged**
