### PR TITLE
transport_write sometimes returns directly without cleanup.

### PR DESCRIPTION
**Pull request by realjiangms**
I happened to get a deadlock thread with following stack trace:
#0  0x00007f2e0af1cfd0 in sem_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f2e0ceed297 in EnterCriticalSection () from /usr/local/lib/libwinpr.so.1.1
#2  0x00007f2e0b6e26a3 in transport_write () from /usr/local/lib/libfreerdp.so.1.2
#3  0x00007f2e0b6e07f5 in fastpath_send_multiple_input_pdu () from /usr/local/lib/libfreerdp.so.1.2
#4  0x00007f2e0d41068f in xf_generic_MotionNotify () from /usr/local/lib/libxfreerdp-client.so.1.2
#5  0x00007f2e0d410e2b in xf_event_process () from /usr/local/lib/libxfreerdp-client.so.1.2
#6  0x00007f2e0d41ab74 in xf_process_x_events () from /usr/local/lib/libxfreerdp-client.so.1.2
#7  0x00007f2e0d41b428 in xf_client_thread () from /usr/local/lib/libxfreerdp-client.so.1.2
#8  0x00007f2e0cf20051 in thread_launcher () from /usr/local/lib/libwinpr.so.1.1
#9  0x00007f2e0af16e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f2e0cbeccbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x0000000000000000 in ?? ()

It's the only thread which is in transport_write. 
So then I found transport_write sometimes returns directly without cleanup. 
This fix the code path to always do cleanup job.

Not sure whether it's the first report. If the fix had already been included in some on-going change or some other pull request, we can just close this pull request

### CODE REVIEW

**Comment by hardening** [comment]
exit for a label name is really a bad idea !

**Comment by hardening** [comment]
except for the label name, seems good to me

**Comment by hardening** [comment]
@freerdp-bot test this please

**Comment by bmiklautz** [comment]
@realjiangms as @hardening noted exit might not be a good idea for a label maybe you can update the PR and rename it to something like out_fail or out _error anything that isn't a function name or keyword ;)
Otherwise +1

**Comment by bmiklautz** [comment]
@realjiangms would you update your PR accordingly to the notes?

**Comment by realjiangms** [comment]
@hardening @bmiklautz 
Done. I finally pick 'out_cleanup'.

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@realjiangms thank you. Just for reference what command did you use when you run into this problem?

**Comment by realjiangms** [comment]
I use +async-transport.
Much issue is exposed with this multi-thread option :)
But this issue is hard to reproduce. Last time I was testing with sudden network down condition. But this issue only happen once.

**Pull request merged**
