### PR TITLE
Added memory and thread sanitizer.

### PR DESCRIPTION
**Pull request by akallabeth**
Allow enabling of memory and thread sanitizer with cmake option.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@akallabeth would you be so kind and rebase this branch to the latest master. Then I'll have a look as well.

**Comment by bmiklautz** [comment]
Just updated to the PR branch and compilation failed with:
cc: error: unrecognized command line option ‘-fsanitize-blacklist=/home/bunny/src/freerdp/FreeRDP-master/scripts/blacklist-leak-sanitizer.txt

**Comment by bmiklautz** [comment]
Works great with clang-3.8+

**Comment by akallabeth** [comment]
@bmiklautz Done

**Comment by hardening** [comment]
This PR is there from quite a long time, @bmiklautz if changes are ok perhaps you could merge it ?

**Comment by bmiklautz** [comment]
@hardening I'll give it a retry.

**Comment by akallabeth** [comment]
@hardening @bmiklautz Rebased this one to master, can we merge it?

**Comment by hardening** [comment]
@akallabeth Just curious, what's the problem with the sanitizer and gcc.c ?

**Comment by hardening** [comment]
@akallabeth forget my comment

**Comment by hardening** [comment]
@bmiklautz are the changes ok for you on this one ? If so perhaps we could merge it...

**Pull request merged**
