### PR TITLE
Winmm dev caps

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@vscfreire ok, did test the AAC encoding on windows.
Just found a few issues with audio recording (maybe device specific) but nothing with AAC / ALAW / ...
The 'noise' you reported can not be reproduced.

Also created #7179 to fix detection of `ffmpeg` on windows.

**Comment by vscfreire** [comment]
@akallabeth 
I used 2.3.2 with #7006 and WAVE_FORMAT_AAC_MS (0xa106) for the mic. What version of ffmpeg did you end up using?

**Comment by vscfreire** [comment]
@akallabeth The good news is that if I join 2.3.2, #7006 and #7180, the AAC distortion is fixed in a simple browser recording test. If I use Audacity I still get some clipping, but not as severe as before.

The bad news is that with AAC, from Windows, with #7180 or without, if I record consecutively, the session is disconnected. With PCM this doesn't happen: just go to https://webcammictest.com/check-mic.html, do the check microphone two times by reloading.

**Comment by akallabeth** [comment]
@vscfreire some logs would help, this is a guessing in the dark game here.
If there is a disconnect, there should be something in the log about why?

**Comment by vscfreire** [comment]
@akallabeth Sorry, here it is:

[aac @ 0000022E495B9280] Qavg: 228.996
[aac @ 0000022E495B9280] 2 frames left in the queue on closing
[aac @ 0000022E495B8DC0] Input contains (near) NaN/+-Inf
[10:03:42:962] [18648:00000a64] [ERROR][com.freerdp.dsp.ffmpeg] - Error submitting the packet to the encoder Invalid arg
ument [-22]
[10:03:42:962] [18648:000013f4] [ERROR][com.freerdp.core] - waveInProc reported an error. Error was 1359
[10:03:42:962] [18648:000013f4] [ERROR][com.freerdp.core] - checkChannelErrorEvent() failed - 0
[aac @ 0000022E495B8DC0] Input contains (near) NaN/+-Inf
[10:03:42:972] [18648:00000a64] [ERROR][com.freerdp.dsp.ffmpeg] - Error submitting the packet to the encoder Invalid arg
ument [-22]
[10:03:43:082] [18648:00004308] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeW failed with error
 SCARD_E_CANCELLED [-2146435070]
[10:03:43:082] [18648:00002090] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeW failed with error
 SCARD_E_CANCELLED [-2146435070]
[10:03:43:082] [18648:00004308] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetStatusChangeW (0x00
0900A4), status: SCARD_E_CANCELLED (0x80100002)
[10:03:43:082] [18648:00002090] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetStatusChangeW (0x00
0900A4), status: SCARD_E_CANCELLED (0x80100002)
[10:03:43:082] [18648:00006ba8] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_
RC_BAD_CHANNEL_HANDLE [00000007]
[10:03:43:082] [18648:00006ba8] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_
RC_BAD_CHANNEL_HANDLE [00000007]
[10:03:43:083] [18648:00006ba8] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_
RC_BAD_CHANNEL_HANDLE [00000007]
[10:03:43:083] [18648:00006ba8] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_
RC_BAD_CHANNEL_HANDLE [00000007]
[aac @ 0000022E495B8DC0] Qavg: 209.456
[aac @ 0000022E495B8DC0] 4 frames left in the queue on closing

**Comment by akallabeth** [comment]
@vscfreire ok, so it was indeed an issue with the backend and not the encoder.
I did just download the latest binaries https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z and compiled freerdp against that (#7179 fixed an issue that the libraries were not detected automatically)
Sound with this one is same as PCM and I did not encounter the `[aac @ 0000022E495B8DC0] Input contains (near) NaN/+-Inf` bug you had, but I´ve seen that one (looks like a format conversion bug in ffmpeg as input is signed int 16?)

**Pull request merged**
