### PR TITLE
Fix FreeRDP crashes on system in FIPS mode

### PR DESCRIPTION
**Pull request by ondrejholy**
Crypto algorithms, which aren't FIPS-compliant (i.e. MD5, RC4), can be still used for some functionality, which isn't security-relevant, on systems with enabled FIPS mode. Let's allow weak ciphers in specific cases (i.e. licensing).

Thanks to this patches, FreeRDP works properly with RDP, or TLS security on systems with enabled FIPS mode.

See https://github.com/FreeRDP/FreeRDP/issues/3412 for more details.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by hardening** [comment]
Hi @ondrejholy,
I like the patch but not the way it's done.
I really think the checks for FIPS should not be done at the winPr level but at a higher level. So not adding an argument to ```winpr_HMAC_Init```, but by checking the callers:

* looking at the patch all the calls ```if (!winpr_Digest(WINPR_MD_MD5, ...., FALSE)``` just means ```if (fipsMode) return FALSE;```
* I guess that in many places we can even return false at a higher level (don't even need to start looking at licence things if RC4 is forbidden by FIPS). I gave a look with eclipse, looking at call hierarchies and it would do a much smaller patch (and would let winpr do crypto without caring of FIPS)

Just curious, but I guess lots of things aren't working in RDP with FIPS enabled (can you even do a negotiation ?)

**Comment by ondrejholy** [comment]
@hardening Thanks for the review. I'm not also really happy with the non_fips_allow arguments, but the EVP_CIPH_FLAG_NON_FIPS_ALLOW and EVP_MD_CTX_FLAG_NON_FIPS_ALLOW flags need to be set somehow. I can change the codes to "if (fipsMode) return FALSE" logic, but not sure how to set the flags when needed. I don't really think that it is a good idea to set those flags by default. 

Yes, a lot of things doesn't work under the FIPS mode and can't work apparently. However, some basic functionality may work under the FIPS mode and that's the reason why I proposed those patches. FreeRDP works on systems with enabled FIPS mode with those patches, but /sec:tls, or /sec:rdp has to be specified explicitly. So, yes, the protocol security negotiation needs to be also updated...

Hmm, it seems that PullRequestTester doesn't like my patches. Maybe some special handling is needed if OpenSSL is not built with FIPS support. I will try to solve this somehow...

**Comment by bjcollins** [comment]
@ondrejholy @hardening check out my new pull request #3904, I worked on it some time ago and it takes a different approach then this PR. I think we will have to keep some logic in the winpr to set flags for fips overrides. I have inline documentation for where we override ciphers and since I use an explicit option - I am able to do things like override NLA automatically. One big thing I did different was just to make unique override functions with fips in their name so it is easier to keep track of where we are overriding specific ciphers for fips.

**Comment by ondrejholy** [comment]
Let's close this request in favor of https://github.com/FreeRDP/FreeRDP/pull/3904 .

**Pull request closed without merging**
