### PR TITLE
add gdi_DrawLine and gdi_Polygon/gdi_PolyPolygon.

### PR DESCRIPTION
**Pull request by XR-stb**
## This is how are pull requests handled by FreeRDP
1. Every new pull request needs to build and pass the unit tests at https://ci.freerdp.com
1. At least 1 (better two) people need to review and test a pull request and agree to accept

## Preparations before creating a pull
* Rebase your branch to current master, no merges allowed!
* Try to clean up your commit history, group changes to commits
* Check your formatting! A _clang-format_ script can be found at ```.clang-format```
  * The cmake target ```clangformat``` reformats the whole codebase
* Optional (but higly recommended)
  * Run a clang scanbuild before and after your changes to avoid introducing new bugs
  * Run your compiler at pedantic level to check for new warnings

## To ease accepting your contribution
* Give the pull request a proper name so people looking at it have an basic idea what it is for
* Add at least a brief description what it does (or should do :) and what it's good for
* Give instructions on how to test your changes
* Ideally add unit tests if adding new features

## What you should be prepared for
* fix issues found during the review phase
* Joining our chat to talk to other developers or help them test your pull might accelerate acceptance
  * Matrix room : #FreeRDP:matrix.org (main)
  * XMPP channel: #FreeRDP#matrix.org@matrix.org (bridged)
  * IRC channel : #freerdp @ irc.oftc.net (bridged)
* Joining our mailing list <freerdp-devel@lists.sourceforge.net> may be helpful too.

### CODE REVIEW

**Comment by akallabeth** [comment]
@XR-stb looks correct, but what is this for? All functions you implemented here are unused and pending removal for that reason?

**Comment by XR-stb** [comment]
> @XR-stb looks correct, but what is this for? All functions you implemented here are unused and pending removal for that reason?

for study ! haha
and I want know  What did  windows gdi do in this project. 
I would like to know where the code section for improving network IO efficiency using gdi is.
I have been looking at the source code for a while, but there is still no progress. The functions related to gdi in this project have either not been used, such as the incomplete implementation of floatbar.
Either it was not called, only implemented or not fully implemented this function.
If I could get your help, it would be great.

**Comment by akallabeth** [comment]
@XR-stb that has historic reasons.
Older versions of the `RDP` protocol did redirect windows `GDI` calls. (think windows XP and older)
so `FreeRDP` must implement these to draw the operations to a bitmap/framebuffer that can be shown.

newer versions of the protocol prefer video codecs to do that (`RFX` with windows 7) or use their own channel (`GFX` modes starting with windows 8)

what you mean with floatbar I don´t fully understand though.

**Comment by XR-stb** [comment]
> @XR-stb that has historic reasons. Older versions of the `RDP` protocol did redirect windows `GDI` calls. (think windows XP and older) so `FreeRDP` must implement these to draw the operations to a bitmap/framebuffer that can be shown.
> 
> newer versions of the protocol prefer video codecs to do that (`RFX` with windows 7) or use their own channel (`GFX` modes starting with windows 8)
> 
> what you mean with floatbar I don´t fully understand though.

you can see in wf_floatbar.c

https://github.com/FreeRDP/FreeRDP/blob/639a36225e67023ed2c0eb6d86b142229a3cd998/client/Windows/wf_floatbar.c#L653

**Comment by akallabeth** [comment]
@XR-stb ah, the windows client?
we´ve added the `CMake` and startup deprecation log messages for a reason ;)

**Pull request closed without merging**
