### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by mfleisz — COMMENTED** [review]
Not a cmake expert but wouldn't it be cleaner to use `list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/)` or `list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/)` instead of `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../cmake/)`?

**Comment by akallabeth** [comment]
> Not a cmake expert but wouldn't it be cleaner to use `list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/)` or `list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/)` instead of `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../cmake/)`?

does not work for subprojects as the `PROJECT_PATH` is the path this is in.

**Pull request merged**
