### PR TITLE
Sdl connect dialog

### PR DESCRIPTION
**Pull request by akallabeth**
* add a generic connection dialog to show status
* integrate that dialog to SDL event loop
* call the dialog with appropriate messages and types (reconnect, connect, ...)
* add new callback on reconnect (`RetryDialog`)
* add signal termination handler to quit SDL on `<ctrl>+c` et al
* Timeout for error messages (delay termination to show the user a reason first)
* prevent termination while a dialog with timeout is shown.
* add icon drawing capability
* Add message icons depending on type
 
TODO: #9666 
* Drawing of dialog message could be improved (a lot) (markup/html)

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test again please

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Comment by akallabeth** [comment]
@freerdp-bot test again...

**Review by hardening — APPROVED** [review]
Looks ok

**Pull request merged**
