### PR TITLE
Return FREERDP_ERROR_AUTHENTICATION_FAILED on an authentication failure

### PR DESCRIPTION
**Pull request by bjcollins**
when using NLA with xfreerdp.

### CODE REVIEW

**Comment by akallabeth** [comment]
@bjcollins Would it not be easier just to use ```SetLastError(ERROR_MUTUAL_AUTH_FAILED)``` (or similar) instead of all the new functions?

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@bjcollins any comment on @akallabeth suggestion?

**Comment by bjcollins** [comment]
@bmiklautz @akallabeth I think this patch could cut down, SetLastError can probably just be called a little deeper without passing the failure boolean up the call stack and I called the callback "test_function" which is not really a great name. Not sure about using ERROR_MUTUAL_AUTH_FAILED as I wanted the exit code to reflect that it was an NLA auth failure. Either way, I want to look at this again and try to rework this patch.

**Comment by bjcollins** [comment]
@akallabeth @bmiklautz  Ok, I reworked this. I wanted to make sure the xfreerdp process return code could be used to determine if process had an authentication failure - so I was unsure about trying to use ERROR_MUTUAL_AUTH_FAILED, but the PR is definitely in better shape than my first submission.

**Comment by akallabeth** [comment]
@bjcollins Looks good so far, just a question, why don't you call ```freerdp_set_last_error(rdp->context, FREERDP_ERROR_AUTHENTICATION_FAILED)``` directly instead of using the new boolean value ```nlaFailure```?

**Comment by bjcollins** [comment]
@akallabeth I think the variable might be useful in the future and this approach keeps setting of the error in the same location it already is. I think you can definitely just set call freerdp_set_last_error directly from the callback, but I like using a variable better. I will gladly remove the variable if you want.

**Comment by akallabeth** [comment]
@bjcollins Would be nice, it usually is easier to find a bug if the error is set where it occured.

**Comment by bjcollins** [comment]
@akallabeth Ok, removed the extra variable and just set the error in the callback.

**Comment by giox069** [comment]
I really would like to see this pull request merged. Could please someone merge ?
It also should fix issue #2760 #2434 and helps for #2432

@bjcollins: in issue 2760 you mentioned "TLS ALERT for ACCESS DENIED". Is this the same problem reported [here](https://social.msdn.microsoft.com/Forums/es-ES/d59c3535-43be-45da-a458-19f4003c5294/mscssp-authentication-failure-notification-with-tls-alerts?forum=os_windowsprotocols) by Marc André ?

**Comment by lemonmojo** [comment]
+1 definitely need better error handling in FreeRDP - this would be a first step.

**Comment by antenore** [comment]
:+1: I also join @lemonmojo and @giox069 , this is a must have for several uses cases. 

Great job @bjcollins!

**Comment by bjcollins** [comment]
@giox069 yes it is the same problem. He discovered the problem and put in the server-side code to send the alert. This adds in the code to detect that "Access Denied" alert on the client side and set an exit code accordingly. Sorry, that is not obvious in the code and I did not put in any comments.

I can probably improve the "transport_ssl_cb" function to make that more clear. I am currently looking at the raw numerical value, but there is an ssl function "SSL_alert_desc_string" which can decipher that value into a 2 character string value "AD". That change along with some comments should help make this PR more readable.

**Comment by giox069** [comment]
@bjcollins: thanks for the explanation. I was just looking for the cause of the bad return code, and I came to the same conclusion. I asked to you just for a confirmation.

The only need I have now is... **please merge this PR**. I'm a Remmina developer/maintainer. I would like to update the "remmina-next Ubuntu PPA" where FreeRDP is very old (before issue #2434). But issues #2760 #2434 will eventually create issues in the PPA with remmina password saving, so I'm blocked on these issues and this PR.

Please, please, **merge**. Thank you :)

**Comment by hardening** [comment]
ok ok I'm not so happy with the thing implemented in the OpenSSL callback, but let's merge it as is.

**Comment by giox069** [comment]
Thank you very much :+1:  :+1: :+1:

**Comment by antenore** [comment]
Thanks!

**Comment by bjcollins** [comment]
@hardening Is your issue with the OpenSSL callback similar to what I said about about just using the raw value instead of using a helper function such as "SSL_alert_desc_string" to translate the code? Or is there more? I am just curious as this is something I would like to fix up a little better in the nearish future as I do not really like the callback code either.

**Pull request merged**
