### PR TITLE
codec/color: support for 8bpp and 16bpp color pointer

### PR DESCRIPTION
**Pull request by nfedera**
This should fix issue #2679 and issue #2460

### CODE REVIEW

**Comment by lemonmojo** [comment]
@nfedera Would this also work for 8-bit cursors?

**Comment by nfedera** [comment]
@lemonmojo 8bit support is/was already there

**Comment by lemonmojo** [comment]
@nfedera Have you tested this? In my tests both, 8 and 16 bit cursors were not being displayed.

**Comment by endriu0** [comment]
@nfedera Tested your commit now. Worked like a charm for me.

**Comment by nfedera** [comment]
@lemonmojo monochrome pointers are working perfectly fine with xp (just tested it).
Please try again and if you still see an issue, please report it in your issue #2460

**Comment by nfedera** [comment]
@lemonmojo I was wrong: 8bit support was never there. I've mixed this up with monochrome.

**Comment by lemonmojo** [comment]
@nfedera I see... So are you planning on adding support for 8-bit?

**Comment by nfedera** [comment]
@lemonmojo Not right now. I'll need to install a Windows 2000 VM. Maybe next week.
Do you know if it also happens with XP RTM (as in without any Service packs)

**Comment by nfedera** [comment]
@lemonmojo ahh easy to reproduce also with XP, just connect with /bpp:8  ;)

**Comment by lemonmojo** [comment]
@nfedera Nice finding! =)

**Comment by nfedera** [comment]
@lemonmojo I've added a commit to this pr for 8bit, please test.

**Comment by lemonmojo** [comment]
@nfedera Seems to work fine in xfreerdp using /gdi:hw. However, when using /gdi:sw 8-bit cursors are completely black. Furthermore, in my own FreeRDP client (which is always using software gdi), I'm passing NULL to the palette parameter which results in the function returning -1. Could you give me some pointers on how to obtain the palette?

**Comment by nfedera** [comment]
@lemonmojo Sure? I don't have any issues with /gdi:sw
I'm running client/X11/xfreerdp /v:xp-server /bpp:8 /gdi:sw 
What is the bpp of your xserver ?
Does this happen only with Server 2000 or also with xp + /bpp:8 ?

**Comment by lemonmojo** [comment]
./xfreerdp /v:win2k /bpp:8 /gdi:sw == Bad (Black Cursors)
./xfreerdp /v:win2k /bpp:8 /gdi:hw == Good

./xfreerdp /v:winxp /bpp:8 /gdi:sw == Bad (No Cursor at all)
./xfreerdp /v:winxp /bpp:8 /gdi:hw == Good

./xfreerdp /v:winxp /bpp:16 /gdi:sw == Good
./xfreerdp /v:winxp /bpp:16 /gdi:hw == Good

X Server is set to 32 bit.

**Comment by nfedera** [comment]
@lemonmojo very weird and this is definitely built from my branch without any other modifications ?

**Comment by nfedera** [comment]
@lemonmojo Re. your question: With 8 bit the stored values are not colors but indexes in a corresponding palette. Thus you cannot pass a NULL palette if you want the conversion to succeed.
The palette is transferred in a rdp update PDU:
- https://msdn.microsoft.com/en-us/library/cc240609.aspx (Slow-Path)
- https://msdn.microsoft.com/en-us/library/cc240623.aspx (Fast-Path)

The X11 hw gdi callback for this order is xf_gdi.c/xf_gdi_palette_update() and the software gdi is gdi.c/gdi_pallete_update()

These functions store the received palette data in the appropriate context to be passed to or accessed by functions who need it.

**Comment by lemonmojo** [comment]
@nfedera Just did a fresh clone and build:
```
git clone -b 'add-16bit-cursor-conversion' https://github.com/nfedera/FreeRDP.git
cd FreeRDP
cmake "-DWITH_CHANNELS=ON" "-DSTATIC_CHANNELS=ON" "-DBUILD_SHARED_LIBS=OFF" "-DWITH_FFMPEG=OFF" "-DWITH_X11=ON" "-DWITH_MACAUDIO=ON" "-DWITH_CUPS=ON" "-DWITH_CLIENT=ON" "-DWITH_PCSC=ON" "-DCMAKE_BUILD_TYPE=Release" -D "CMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.8" -D "CMAKE_OSX_SYSROOT:STRING=/Applications/Xcode5.11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk" -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" .
make
cd client/X11/ 
```

Then I redid the tests for the bad cases.
On Win2k using gdi:sw I still get a black cursor. Same as before.
On WinXP however, the first time I connected the cursor was colored but as soon as I switched to another cursor, it became all black.
I then reconnected to the XP machine and now I get an all black cursor all the time.

**Comment by hardening** [comment]
+1 even if some cases don't work yet, as it's an improvement for @endriu0

**Comment by nfedera** [comment]
@lemonmojo what's your platform?  Linux/x86?

**Comment by lemonmojo** [comment]
@nfedera OS X/x64

**Comment by nfedera** [comment]
@lemonmojo also experienced the black cursor now with /gdi:sw.
The issue is that xfc->palette never gets updated since gdi_pallete_update() only writes to gdi->palette

**Comment by nfedera** [comment]
@lemonmojo shoud be fixed now. Please confirm.

**Comment by lemonmojo** [comment]
@nfedera Yep, 8-bit cursors are now working too! thx!

**Comment by endriu0** [comment]
@nfedera @hardening Thanks for the fix - tried with another affected user and also worked perfectly.

**Comment by nfedera** [comment]
@lemonmojo ok cool. @hardening @awakecoding any objections regarding the last commit f04bb6c53dc5193b35652cb58f1db0732e494fbb ? If not this can be merged.

**Comment by nfedera** [comment]
@endriu0 once this PR is merged please close issue #2679 and @lemonmojo please do the same for issue #2460. Thanks.

**Comment by endriu0** [comment]
@nfedera sure will do

**Comment by bmiklautz** [comment]
+1

**Pull request merged**
