### PR TITLE
Fix Format List PDU is not sent when the Clipboard Redirection Virtual Channel is initialized for the second time. (X11 client)

### PR DESCRIPTION
**Pull request by XiaopengZHOU**

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot can you test please ?

**Comment by KangLin** [comment]
If you modify it this way, you will not be able to send the format list the first time.

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@Ka

> If you modify it this way, you will not be able to send the format list the first time.

Why should that be the case?
`xf_clipboard_formats_free` just resets `lastSentFormats` so the current clipboard content is detected as change to the state the server has.
There might be an issue, if the local clipboard is empty though...

**Comment by KangLin** [comment]
Sorry. I was misled by the function name of the xf_clipboard_formats_free.
It is recommended to rename to xf_clipboard_last_sent_formats_free.

**Pull request merged**
