### PR TITLE
Fixed error on exit about pthread_mutex_destroy with waiters

### PR DESCRIPTION
**Pull request by bceverly**
There was a lingering error message on OpenBSD about destroying a mutex with waiters.  I have made a one-line change (ifdef'ed to just OpenBSD) to correct this.  It might be legit on other platforms but I didn't want to make that call b/c of risk.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@bceverly what error message did you get?

**Comment by bceverly** [comment]
The error message that prints on the command line is:

pthread_mutex_destroy on mutex with waiters

It's a debug message built into OpenBSD and is meant to discourage people
from releasing code where they haven't cleaned up things waiting on a
mutex.  It's a bit annoying honestly but I'd prefer to have the message not
show up on OpenBSD for a released version of an updated FreeRDP port to
avoid people mis-reporting it as an error.

It's pretty easy to generate without the patch in that every time you run
xfreerdp you get it so:

xfreerdp --version

generates the warning on the command-line.  This seems to have fixed it and
I'm not getting any crashes in the testing that I've done.


Thanks,
Bryan

On Fri, Apr 24, 2015 at 1:40 PM, Bernhard Miklautz <notifications@github.com

**Comment by akallabeth** [comment]
@bceverly This patch looks like it will hide an issue. Probably better to trace down the culprit.

**Comment by akallabeth** [comment]
@bceverly Ok, have opened #2579 for a generic solution with a little explanation of why this is necessary. You can close this one now, thx for pointing this out.

**Pull request closed without merging**
