### PR TITLE
Export connectErrorCode

### PR DESCRIPTION
**Pull request by itsmikeeng**
It is commit https://github.com/FreeRDP/FreeRDP/commit/354027bcd3332be994dfcc630f4944d031a8fafc on the master branch, but I couldn't figure out how to request that pull to the stable-1.1 branch.

### CODE REVIEW

**Comment by awakecoding** [comment]
@freerdp-bot test.

**Comment by bmiklautz** [comment]
@itsmikeeng what problem does this pull request fix for you?

**Comment by itsmikeeng** [comment]
When referencing the freerdp dll externally and I'm unable to get the connectErrorCode, as it is not exposed.

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Pull request closed without merging**
