### PR TITLE
Enable clipboard channel per default

### LINKED ISSUE #4141: Enable clipboard redirection by default.
At least for xfreerdp it should be enabled by default (if built in).

### PR DESCRIPTION
**Pull request by bmiklautz**
Closes #4141.

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot can't you do a proper test ?

**Comment by hardening** [comment]
@freerdp-bot come on and succeed the connect test !

**Comment by akallabeth** [comment]
@freerdp-bot please be so kind, test!

**Comment by akallabeth** [comment]
@freerdp-bot really, test this proper!

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
@freerdp-bot test again my friend !

**Comment by akallabeth** [comment]
@hardening This one will not succeed at all, see #4152 for a fix to that

**Comment by akallabeth** [comment]
@hardening The resource leak stuff (hopefully) fixed the frequent failures, but this one introduced/uncovered another issue :/

**Comment by hardening** [comment]
@bmiklautz rebasing that branch should fix things IMHO

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Pull request merged**
