### PR TITLE
Stable 2.0.android

### PR DESCRIPTION
**Pull request by akallabeth**
Backport #7550

### CODE REVIEW

**Comment by ccpp** [comment]
> @ccpp could you check that with this pr you can build it without failure?

Testing. Can't promise to have results until next week ;)

**Comment by ccpp** [comment]
@akallabeth please see report here: https://gitlab.com/c7np6r/fdroiddata/-/jobs/1979788158 (building d09ea1e).
```
CMake Error at CMakeLists.txt:849 (message):
  FFMPEG support requested but not detected
-- Configuring incomplete, errors occurred!
```

**Comment by akallabeth** [comment]
@ccpp thank you, found it. stupid typo :sweat:

**Comment by ccpp** [comment]
I tried to build this (00900c5cb), still got the same error. @akallabeth  Can I modify build instructions to make it build?

    CMake Error at CMakeLists.txt:845 (message):
      FFMPEG support requested but not detected

see https://gitlab.com/c7np6r/fdroiddata/-/jobs/2025113676

**Comment by akallabeth** [comment]
@ccpp did try on current `stable-2.0` branch (548e96d3bca37298ba56bd844783dcfa64f5d7d5) with ` ./scripts/android-build-freerdp.sh --conf scripts/android-build-release.conf` and it works as desired (`ANDROID_SDK` and `ANDROID_NDK` set via environment)

`objdump` output for all 4 architectures is similar to:
```
objdump -x ./client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/libfreerdp2.so

./client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/libfreerdp2.so:     file format elf32-little
./client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/libfreerdp2.so
architecture: UNKNOWN!, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000

Program Header:
    PHDR off    0x00000034 vaddr 0x00000034 paddr 0x00000034 align 2**2
         filesz 0x00000100 memsz 0x00000100 flags r--
    LOAD off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**12
         filesz 0x000c3be4 memsz 0x000c3be4 flags r-x
    LOAD off    0x000c3d98 vaddr 0x000c4d98 paddr 0x000c4d98 align 2**12
         filesz 0x00007b64 memsz 0x0004c6e8 flags rw-
 DYNAMIC off    0x000ca170 vaddr 0x000cb170 paddr 0x000cb170 align 2**2
         filesz 0x00000140 memsz 0x00000140 flags rw-
    NOTE off    0x00000134 vaddr 0x00000134 paddr 0x00000134 align 2**2
         filesz 0x000000bc memsz 0x000000bc flags r--
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rw-
0x70000001 off    0x00090acc vaddr 0x00090acc paddr 0x00090acc align 2**2
         filesz 0x00004208 memsz 0x00004208 flags r--
   RELRO off    0x000c3d98 vaddr 0x000c4d98 paddr 0x000c4d98 align 2**3
         filesz 0x00007268 memsz 0x00007268 flags rw-

Dynamic Section:
  PLTGOT               0x000cb364
  PLTRELSZ             0x00001920
  JMPREL               0x000150b8
  PLTREL               0x00000011
  REL                  0x0000db78
  RELSZ                0x00007540
  RELENT               0x00000008
  RELCOUNT             0x00000e7f
  SYMTAB               0x000001f0
  SYMENT               0x00000010
  STRTAB               0x00004630
  STRSZ                0x0000566b
  GNU_HASH             0x00009c9c
  HASH                 0x0000b0a0
  NEEDED               libswscale.so
  NEEDED               libcrypto.so
  NEEDED               libssl.so
  NEEDED               libavcodec.so
  NEEDED               libavutil.so
  NEEDED               libswresample.so
  NEEDED               libwinpr2.so
  NEEDED               libm.so
  NEEDED               libdl.so
  NEEDED               libc.so
  SONAME               libfreerdp2.so
  FINI_ARRAY           0x000cb168
  FINI_ARRAYSZ         0x00000008
  FLAGS                0x00000008
  FLAGS_1              0x00000001
  VERSYM               0x0000d1d4
  VERDEF               0x0000da5c
  VERDEFNUM            0x00000001
  VERNEED              0x0000da78
  VERNEEDNUM           0x00000008

```

**Comment by akallabeth** [comment]
@ccpp and my hope that `OpenH264` finally fixes this long standing bug have just been shattered, see https://github.com/cisco/openh264/issues/3476

**Comment by akallabeth** [comment]
@ccpp also, when running the build with the commit you mentioned locally `FFMPEG` is detected as it should be, see 
[android-build-log.00900c5.zip](https://github.com/FreeRDP/FreeRDP/files/7957114/android-build-log.00900c5.zip)

**Comment by akallabeth** [comment]
@ccpp ok, found something that might be realated:
OpenSSL installs to `/builds/c7np6r/fdroiddata/build/com.freerdp.afreerdp/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/`
but FFMPEG to `/builds/c7np6r/fdroiddata/build/com.freerdp.afreerdp/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/lib/libavcodec.so`

so, depending on what is available in `CMake` search path that might explain why it is found for me and not for you.
I´ve used `/opt/Android/Sdk/ndk/21.3.6528147`

**Pull request merged**
