### PR TITLE
Automatic gradle version code from git tag

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes the issues with FDroid automatic visioning pointed out in #4183

### CODE REVIEW

**Comment by ccpp** [comment]
Sorry, I'm not sure this helps... According to [this quotation](https://github.com/FreeRDP/FreeRDP/issues/4183#issuecomment-341995883), the versionCode should be hardcoded into the gradle file to work

**Comment by akallabeth** [comment]
@ccpp Well, it works as long as the build is done on a git branch. You get a sequential increasing numbering from the version tag

**Comment by ccpp** [comment]
I tried it on the fdroidserver... it always finds versionCode "None":
```
DEBUG: Check tag: '2.0.0-rc1'
DEBUG: Directory: build/com.freerdp.afreerdp
DEBUG: > git rev-parse --show-toplevel
DEBUG: Directory: build/com.freerdp.afreerdp
DEBUG: > git submodule foreach --recursive git reset --hard
DEBUG: Directory: build/com.freerdp.afreerdp
DEBUG: > git submodule foreach --recursive git clean -dffx
DEBUG: Directory: build/com.freerdp.afreerdp
DEBUG: > git checkout -f 2.0.0-rc1
DEBUG: Directory: build/com.freerdp.afreerdp
DEBUG: > git clean -dffx
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/build.gradle'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/src/main/AndroidManifest.xml'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/build.gradle'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Adding possible subdir client/Android/Studio/aFreeRDP
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/src/main/AndroidManifest.xml'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/build.gradle'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/src/main/AndroidManifest.xml'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Adding possible subdir client/Android/Studio/aFreeRDP/src/main
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/aFreeRDP/src/main/AndroidManifest.xml'
DEBUG: ..got package=com.freerdp.afreerdp, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/freeRDPCore/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/freeRDPCore/build.gradle'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.freerdp.afreerdp/client/Android/Studio/freeRDPCore/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
```

**Comment by akallabeth** [comment]
https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode tells me that you can check for new tags of a specific format, just don't know if that is sufficient?

**Comment by ccpp** [comment]
@akallabeth Yes, you can do that. But they do not actually execute gradle on the file to extract data, but they just scan the file itself. I found this in fdroidserver's code ([here](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/common.py#L1231)):
```python
vcsearch_g = re.compile(r'''.*[Vv]ersionCode[ =]+["']*([0-9]+)["']*''').search
vnsearch_g = re.compile(r'.*[Vv]ersionName *=* *(["\'])((?:(?=(\\?))\3.)*?)\1.*').search
psearch_g = re.compile(r'.*(packageName|applicationId) *=* *["\']([^"]+)["\'].*').search
```

**Comment by akallabeth** [comment]
@ccpp Ah, ok, so the new tag is not sufficient but the gradle needs a new version too? Damn, is there no way just to check for tags?

**Comment by ccpp** [comment]
@akallabeth Actually, there might be a way using your code, using the `HTTP` option of the [Update Check Mode](https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode): We just need any web resource containing both version code and the (computed) version code *of the most recent release / tag* anywhere in its body.

Can this be implemented by the FreeRDP team somewhere on http://www.freerdp.com/, or as a Jenkins job build result page with a permanent URL? (who can be asked about this?)

**Comment by ccpp** [comment]
@akallabeth Continuing my thoughts above: we might get it to work with a web resource similar to the [latest stable android build console output on Jenkins](https://ci.freerdp.com/job/android/lastSuccessfulBuild/consoleText), where the FreeRDP version can be extracted already, only the versionCode is missing there.
(Note however, to get the most recent *master branch* and not other branches, a Jenkins Multi-Branch Pipeline might become necessary... which would be nice anyway!)

As soon as that works, F-Droid can be configured similar to this (see [the docs](https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode): (assuming `FREERDP_VERCODE` is present on the page)
```
Auto Update Mode:Auto Update Mode:None
Update Check Mode:HTTP
Update Check Data:https://ci.freerdp.com/job/android/lastSuccessfulBuild/consoleText|FREERDP_VERSION=(.*)|.|FREERDP_VERCODE=(.*)
```

**Comment by akallabeth** [comment]
@ccpp Have thought a lot about this, I think the easiest will be to change to manual build versions.
Closing this now, opened #4366 as a reminder

**Pull request closed without merging**
