### PR TITLE
X11: Scale cursor when SmartSizing is enabled

### PR DESCRIPTION
**Pull request by nloewen**
Continued from #6462

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@nloewen nicely done! Works as intended now.
As for the failing mac build, you might want to add
```
#if !defined(XcursorPixel)
typedef XcursorUInt	XcursorPixel;
#endif
```
or replace the type as that is not available for older X11 versions.

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@nloewen ok, needs a `clang-format` on the source...

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by nloewen** [comment]
@freerdp-bot test

**Comment by nloewen** [comment]
That mac build is picky eh? As far as I can tell, those defines should exist within the libraries included with XQuartz

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by akallabeth — APPROVED** [review]
LGTM

**Pull request merged**
