### PR TITLE
Allow autonegotiation of tls/ssl version for tls 1.2 compatibilty

### PR DESCRIPTION
**Pull request by mbbush**
This is the fix referenced in the discussion of issue #2828. I have not tested it outside my own environment, but it works great for me and is reported to be working well by other users in that issue thread.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by hardening** [comment]
With this patch we allow to do unsecure versions of SSL aka v2 and v3. Looks like a bad idea isn't it ?

**Comment by bmiklautz** [comment]
@mbbush SSLv23_client_method was deprecated recently in openssl. I'd suggest using TLSv1_2_method instead. Could you try this as well?

**Comment by bmiklautz** [comment]
When using TLS_method we could just disable SSLv3 with
```
options |= SSL_OP_NO_SSLv3;
```
This way TLS 1+ works but the Fallback to v3 is disabled. Sounds like the best solution for me.
@hardening @mbbush what do you think?

**Comment by bmiklautz** [comment]
I've just checked and for now there is a compatibility macro available in openssl. So using SSLv23_client_method should be ok but still should disable sslv3 as commented above.

**Comment by hardening** [comment]
SSL_OP_NO_SSLv2 would be nice too

**Comment by bmiklautz** [comment]
@hardening absolutely :).

**Comment by bmiklautz** [comment]
@hardening @mbbush have a look to PR #3046 I've added the options to disable SSL v2 and v3.

**Pull request closed without merging**
