### PR TITLE
avoid blurry filter when scaling factor is 2x, 3x, etc

### PR DESCRIPTION
**Pull request by volth**
Useful when the client has high-dpi monitor.

For example, when the client has 4k (3160x2160) monitor, `xfreerdp /w:1920 /h:1080 /smart-sizing /f` and `xfreerdp /w:1280 /h:720 /smart-sizing /f` will create crispy 1920x1080 and 1280x720 RDP sessions.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by akallabeth** [comment]
@volth nice one, thank you!

**Comment by hardening** [comment]
@freerdp-bot can you test that ?

**Comment by ikeboy** [comment]
this isn't working for me on Ubuntu 19.10. Tried the latest nightly and using your exact command on a 4k monitor (precision 5530). Logging into a Windows server.

**Comment by bparker06** [comment]
Same issue here for me.

**Comment by volth** [comment]
It was refactored in https://github.com/FreeRDP/FreeRDP/pull/5657
probably it broke something
cc @mfleisz

**Comment by volth** [comment]
As far as remember, `0.001` was used because `DBL_EPSILON` is too small, those scaling factor values were not exact `3840 / 1280`  but something 1 pixel more or less, so that `0.001` was chosen as "at least (1 / screenwidth)"

**Pull request merged**
