### PR TITLE
[build] make OpenSSL and mbedtls mutually exclusive

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by hardening** [comment]
I guess this can only be a temporary workaround, as IIRC some people (devolution) do build with mbed and openssl, but in the meantime it would do the job.

**Comment by awakecoding** [comment]
We build WinPR with mbedTLS, and then FreeRDP with OpenSSL against the prebuilt WinPR that uses mbedTLS. Please do not break this build scenario 🙏

**Comment by akallabeth** [comment]
@awakecoding should not be an issue with this, it just ensures that not both `mbedTLS` and `OpenSSL` can be defined at once.

**Comment by awakecoding** [comment]
I think that should be fine, we build WinPR in a first step with mbedTLS only, and then FreeRDP with OpenSSL only, against WinPR which is linked against mbedTLS. You can see our build recipes here, there's one for freerdp separate from winpr: https://github.com/Devolutions/conan-public/tree/master/recipes

**Review by bmiklautz — APPROVED** [review]

**Comment by bmiklautz** [comment]
Also think that this shouldn't cause any problems as only openssl or mbedTLS at a time makes sense (and works ;)

**Pull request merged**
