### PR TITLE
[utils,unwind] fix path to log.h

### PR DESCRIPTION
**Pull request by floppym**
Bug: https://bugs.gentoo.org/936406

### CODE REVIEW

**Review by akallabeth — CHANGES_REQUESTED** [review]
Looks like a `CMake` issue here:
in `winpr/libwinpr/utils/CMakeLists.txt` there should be a `winpr_include_directory_add(${CMAKE_CURRENT_SOURCE_DIR})` but there is `set(CMAKE_INCLUDE_CURRENT_DIR ON)` (which might be turned on/off externally

**Comment by akallabeth** [comment]
@floppym fixed the missing `CMake` include path with https://github.com/FreeRDP/FreeRDP/pull/10410 - is this still required?

**Comment by floppym** [comment]
I wasn't able to reproduce the error personally. I will apply #10410 on top of 3.6.3 in Gentoo and see if the bug gets re-opened.

**Comment by floppym** [comment]
Closing for now.

**Pull request closed without merging**
