### PR TITLE
Fixed #6760: Use wide char file operations on windows.

### LINKED ISSUE #6760: Move cliprdr_parse_file_list() outside of freerdp-client3 library
The function `cliprdr_parse_file_list()` allows the conversion of a packet file list into an array of `FILEDESCRIPTORW`s and is useful for both server- and client- implementations of the `CLIPRDR` channel.

However, the function is only available when the implementation links against the `freerdp-client` library, which is inconvenient for server implementations, as linking against the `freerdp-client` library should only be needed for client implementations.

To solve this situation, this function should be moved outside of `freerdp-client` into the `freerdp` library for FreeRDP 3.0 (current master), so neither the linkage against `freerdp-client` or `freerdp-server` library is necessary (, as this function is useful for both server side and client side `CLIPRDR` implementations).

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by mfleisz** [comment]
#6760 references a clipboard channel issue and looks unrelated to this PR - I guess this is supposed to fix #6759

**Review by mfleisz — COMMENTED** [review]
Fix LGTM - but what is that `fopen_wrap` function actually for?

**Comment by akallabeth** [comment]
@mfleisz to open files with unicode names in it (windows only)

**Comment by mfleisz** [comment]
Just wondering why this is necessary:
- `PathFileExistsA` is used to check `licenseStorePath` for existance
- The appended file name (`"hash_of_hostname.cal"`) won't contain any chars that require Unicode.

**Review by hardening — DISMISSED** [review]

**Comment by akallabeth** [comment]
@mfleisz ok, fixed the remaining non wide char calls.
the end of the path may not contain unicode, but the username et al might (which is part of the path)

**Comment by pnowack** [comment]
> Fixed #6760: Use wide char file operations on windows.

Typo: This should probably be https://github.com/FreeRDP/FreeRDP/issues/6759, not https://github.com/FreeRDP/FreeRDP/issues/6760

**Review by mfleisz — APPROVED** [review]
LGTM

**Pull request merged**
