### PR TITLE
Revert "Possible fix for #4081 and #2707 (#4087)" (Part of #4096)

### PR DESCRIPTION
**Pull request by abma**
This reverts most of commit 6b7b60237042a891221d71a596fc683d850bcb4e.

Part of #4096, this fixes /f

### CODE REVIEW

**Comment by hardening** [comment]
@freerdp-bot test that my friend

**Comment by hardening** [comment]
@freerdp-bot you're boring with the connect test !

**Comment by hendwolt** [comment]
I tested the patch on openSUSE Tumbleweed (32bit) and it works for me in fullscreen mode.

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by hardening** [comment]
@freerdp-bot can you test correctly this time ?

**Comment by hardening** [comment]
@freerdp-bot the " test connect" fails almost all the time, come on !

**Pull request merged**
